/**
 * Marks — the drawn icons that replaced the app's emoji.
 *
 * Every tier, badge, check-in habit, sport, quest, pillar, onboarding option
 * and mood step has a keyed webp under public/marks/<family>/<id>.webp,
 * generated by scripts/mark-art.mjs in one style (hard-enamel pin: gold
 * metal, plum inlay, ember accents). This resolves an id to its file; the
 * test in src/lib/__tests__/marks.test.ts checks every catalog id has one.
 */
export type MarkFamily = "tier" | "badge" | "habit" | "sport" | "quest" | "pillar" | "onboarding" | "mood";

/** badges.name → file slug (the DB has no key column; names are unique). */
export const badgeSlug = (name: string): string =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

/** `normal` is the second recruit rung and shares its mark. */
const TIER_ALIAS: Record<string, string> = { normal: "recruit" };

export const markUrl = (family: MarkFamily, id: string): string => {
  const file = family === "badge" ? badgeSlug(id) : family === "tier" ? TIER_ALIAS[id] ?? id : id;
  return `/marks/${family}/${file}.webp`;
};
