// Bundle the technique frames (Everkinetic SVGs, CC BY-SA 4.0) for every
// movement the coach can prescribe — ILLUSTRATION_BY_CATALOG's targets — so the
// runner draws from disk: offline, instant, crisp at any pixel density. The
// rest of the library keeps loading its vectors from the CDN.
//   npx vite-node scripts/generate-illustration-frames.mts
import { existsSync, mkdirSync, writeFileSync, readdirSync } from "node:fs";
import { ILLUSTRATION_BY_CATALOG } from "../src/data/illustration-map";
import { ILLUSTRATED_EXERCISES, illustrationUrl } from "../src/data/exercises-illustrated";

const DIR = "public/illustrations/frames";
const STATES = ["relaxation", "tension"] as const;
mkdirSync(DIR, { recursive: true });

const bySlug = new Map(ILLUSTRATED_EXERCISES.map((e) => [e.slug, e.idNum]));
const ids = [...new Set(Object.values(ILLUSTRATION_BY_CATALOG).map((slug) => {
  const id = bySlug.get(slug);
  if (!id) throw new Error(`no illustrated exercise for ${slug}`);
  return id;
}))].sort();

const jobs = ids.flatMap((id) => STATES.map((state) => ({ id, state })));
let done = 0, fetched = 0;
const worker = async () => {
  for (;;) {
    const job = jobs.shift();
    if (!job) return;
    const file = `${DIR}/${job.id}-${job.state}.svg`;
    if (!existsSync(file)) {
      for (let attempt = 1; ; attempt++) {
        try {
          const res = await fetch(illustrationUrl(job.id, job.state));
          if (!res.ok) throw new Error(`${res.status}`);
          const svg = await res.text();
          if (!svg.startsWith("<svg")) throw new Error("not an svg");
          writeFileSync(file, svg);
          fetched++;
          break;
        } catch (e) {
          if (attempt >= 4) throw e;
          await new Promise((r) => setTimeout(r, 400 * attempt));
        }
      }
    }
    done++;
  }
};
await Promise.all(Array.from({ length: 8 }, worker));

const bundled = [...new Set(readdirSync(DIR).filter((f) => f.endsWith(".svg")).map((f) => f.slice(0, 4)))].sort();
writeFileSync(
  "src/data/illustration-frame-ids.ts",
  `// AUTO-GENERATED by scripts/generate-illustration-frames.mts — do not hand-edit.
// Illustration ids whose two technique frames ship in public/illustrations/frames/.
export const BUNDLED_FRAME_IDS: ReadonlySet<string> = new Set<string>(${JSON.stringify(bundled)});
`,
);
console.log(`frames: ${done} checked, ${fetched} fetched, ${bundled.length} movements bundled`);
