// What each mark draws — the generation side of public/marks/. Ids are the
// app's own keys (status-tiers, badges.name slug, checkin-habits, sports,
// DailyQuests, wellness-framework pillars, onboarding options, MoodSnapshot).
// src/lib/marks.ts resolves an id to its file; src/lib/__tests__/marks.test.ts
// checks every id in every catalog has one.

/** badges.name → file slug (mirrors slugify in src/lib/marks.ts). */
export const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export const FAMILIES = {
  tier: [
    ["recruit", "a plain square shield with a single horizontal bar"],
    ["operator", "a shield with a single chevron"],
    ["performer", "a shield with two stacked chevrons"],
    ["high_performer", "a shield with three stacked chevrons and a small star above"],
    ["elite", "a royal crown"],
    ["apex", "a mountain peak with a lightning bolt striking its summit"],
    ["legend", "a trident with laurel leaves either side"],
  ],
  badge: [
    ["3-Day Streak", "a small flame"],
    ["7-Day Streak", "a flame with the numeral 7 shape suggested by its inner tongue, no actual text"],
    ["30-Day Streak", "a cut diamond gem with a small flame inside"],
    ["Cold Warrior", "an ice cube with a crack and frost sparkles"],
    ["Iron Discipline", "two crossed swords"],
    ["Proof Poster", "a camera"],
    ["Battle Victor", "a trophy cup"],
    ["Top 10 Percent", "a bar chart with the tallest bar highlighted"],
    ["Top 1 Percent", "a crown with a single gem"],
    ["Founder", "a five-pointed star with rays"],
    ["Spring 26", "a cherry blossom"],
    ["Double Down", "a flexed arm"],
    ["Kudos Master", "a trophy with a speech bubble"],
    ["Season Champion", "a trophy on a podium"],
    ["Founders Circle", "a trident inside a ring"],
    ["First Recruit", "an archery target with an arrow in the centre"],
    ["Brand Ambassador", "a bright star with sparkles"],
    ["Inner Circle Founder", "a lightning bolt inside a ring"],
    ["Kingmaker", "a crown resting on a trophy"],
    ["One of the Winners", "a trophy with a laurel wreath"],
    ["Spark Brother", "two flames side by side sharing one base"],
    ["Tribe Ember", "a log with glowing embers"],
    ["Tribe Inferno", "an erupting volcano"],
    ["Eternal Pyre", "a comet with a long tail"],
    ["Tribe Founder", "a crown over a small campfire"],
    ["First Tribe Blood", "a single sword"],
    ["War Chief", "a shield with a boss in the centre"],
    ["Tribe Conqueror", "a trophy with crossed swords behind it"],
    ["Apex Reached", "a cut diamond gem"],
    ["Apex Stronghold", "a snow-capped mountain"],
    ["Founding Apex", "four-pointed sparkles around a small diamond"],
    ["Legend Ascendant", "a shooting star"],
    ["Eternal Legend", "an all-seeing eye"],
    ["Inferno Personal", "a tall roaring flame"],
    ["Phoenix", "a phoenix rising with spread wings"],
    ["Integrator", "a hand mirror"],
    ["Wayfinder", "a compass rose"],
    ["Shadow Explorer", "a new moon with a thin crescent of light"],
    ["Stoic Path", "a Greek temple with columns"],
    ["Meaning Seeker", "a lantern with a beam of light"],
    ["Discipline Builder", "a hammer and a chisel crossed"],
    ["Mastery Builder", "an ornate old key"],
    // ── Live rows the migrations never seeded (read from the badge table) ──
    ["10 Check-ins", "a clipboard with a ticked checklist"],
    ["100 Check-ins", "a rising bar chart with a check mark"],
    ["100-Day Legend", "a stone moai head"],
    ["100K Legend", "a crown with three gems"],
    ["10K Club", "a medal on a ribbon with a laurel"],
    ["200 Workouts", "a flexed arm with a sweat drop"],
    ["50 Check-ins", "a notepad with a pencil"],
    ["500 Check-ins", "a wall calendar with a check mark"],
    ["60-Day Dynasty", "a throne"],
    ["90-Day Streak", "a dragon head breathing a small flame"],
    ["Absolute Zero", "a thermometer at zero with frost crystals"],
    ["Apprentice", "a military medal ribbon with one star"],
    ["Arctic Soul", "a snowflake"],
    ["Army Builder", "a military helmet"],
    ["Battle God", "a lightning bolt over crossed swords"],
    ["Battle Hardened", "a battered shield with a notch"],
    ["Beast Mode", "a wolf head"],
    ["Bookworm", "a stack of three books"],
    ["Champion", "a medal with a star"],
    ["Champion Fighter", "two boxing gloves crossed"],
    ["Clean Eater", "a bowl of greens with a fork"],
    ["Commentator", "two overlapping speech bubbles"],
    ["Consistent", "three equal bars with a check mark"],
    ["Devoted", "a padlock with a heart"],
    ["Diet King", "a crown over a leaf"],
    ["Digital Ascetic", "a phone with a diagonal bar and a person meditating"],
    ["Double Trouble", "two lightning bolts side by side"],
    ["Early Riser", "a rooster"],
    ["Enlightened", "a lotus flower with a halo"],
    ["Eternal", "an infinity loop"],
    ["First 1K", "a coin with a star"],
    ["First Blood", "a sword with a single drop"],
    ["First Breath", "a lotus bud with a breath swirl"],
    ["First Chapter", "a closed book with a ribbon marker"],
    ["First Chill", "a shivering face with snowflakes"],
    ["First Clean Meal", "a broccoli floret"],
    ["First Spark", "a struck match with a spark"],
    ["First Step", "a single footprint"],
    ["First Sweat", "a sweat droplet on a headband"],
    ["Flawless", "a diamond with a check mark"],
    ["Fortnight Force", "two stars orbiting in a ring"],
    ["Frost King", "a crown made of ice"],
    ["Gladiator", "a gladiator helmet with a plume"],
    ["Grandmaster", "a chess king piece"],
    ["Gym Rat", "a kettlebell"],
    ["Gym Regular", "a stack of barbell plates"],
    ["Hydration King", "a water bottle with a crown"],
    ["Ice Breaker", "an ice block cracking under a pick"],
    ["Influencer", "a megaphone with a crown"],
    ["Inner Peace", "a peace symbol"],
    ["Iron Mind", "a brain on a shield"],
    ["Knowledge Seeker", "a magnifying glass over a book"],
    ["Level 15", "a shield with one star"],
    ["Level 30", "a shield with two stars"],
    ["Level 5", "a small five-pointed star"],
    ["Library Legend", "a bookshelf between two columns"],
    ["Mind Over Matter", "a brain with a dumbbell"],
    ["Morning Monk", "a sun rising over mountains"],
    ["Night Guardian", "a crescent moon on a shield"],
    ["Night Owl Discipline", "an owl"],
    ["Nutrition Nerd", "a DNA helix with a leaf"],
    ["Ocean Inside", "a curling wave"],
    ["Overachiever", "a target with two arrows"],
    ["Perfect Week", "a calendar page with a large star on it"],
    ["Perfectionist", "a crown with a check mark"],
    ["Polar Bear", "a polar bear head"],
    ["Proof Machine", "a video camera"],
    ["Protein Beast", "a steak with a flexed arm"],
    ["Protein Machine", "a protein shaker bottle"],
    ["Protein Titan", "a trophy with a steak"],
    ["Receipts Only", "a paper receipt"],
    ["Recruiter", "a megaphone"],
    ["Rising Star", "a star with an upward arrow"],
    ["Scholar", "a graduation cap"],
    ["Show Don't Tell", "an instant photo print"],
    ["Squad Leader", "three figures, the middle one raised"],
    ["Sunset Sage", "a setting sun over water"],
    ["Titan of Iron", "a sword driven into an anvil"],
    ["Top 1%", "a diamond with rays"],
    ["Top 10%", "a three-step podium"],
    ["Top 5%", "a rosette medal"],
    ["Undefeated", "a crown over crossed swords"],
    ["Unstoppable", "a rocket"],
    ["Viral", "a flame with a heart"],
    ["Warlord", "a trident crossed with a shield"],
    ["Warrior", "a helmet over crossed swords"],
    ["Water God", "a trident rising from water"],
    ["Week Warrior", "a lightning bolt on a shield"],
    ["XP Collector", "a money bag with a star"],
    ["XP Immortal", "a skull with a crown"],
    ["XP Machine", "a gear with a flame"],
    ["XP Overlord", "a crystal ball"],
    ["Year of Steel", "a steel ring with a star"],
    ["Zen Master", "a meditating figure with a halo"],
  ],
  habit: [
    ["sleep", "a crescent moon with one small star"],
    ["workout", "a dumbbell"],
    ["hydration", "a water droplet"],
    ["meditation", "a person sitting cross-legged in meditation"],
    ["steps_8k", "a pair of footprints"],
    ["extra_workout", "a dumbbell with a small plus sign"],
    ["zone2", "a heart with a pulse line"],
    ["mobility", "a figure in a deep side stretch"],
    ["sunlight", "a rising sun over a horizon line"],
    ["healthy_food", "a bowl of salad with a leaf"],
    ["protein", "a steak"],
    ["no_alcohol", "a beer mug with a diagonal bar across it"],
    ["no_sugar", "a lollipop with a diagonal bar across it"],
    ["caffeine_cutoff", "a coffee cup with a small clock"],
    ["creatine", "a capsule pill"],
    ["meditation_pm", "a crescent moon over a person sitting in meditation"],
    ["breathwork", "a face in profile exhaling a curling breath"],
    ["no_phone_am", "a phone with a diagonal bar and a small sun"],
    ["no_phone_pm", "a phone with a diagonal bar and a small moon"],
    ["reading", "an open book"],
    ["journaling", "a notebook with a pen"],
    ["gratitude", "two hands pressed together"],
    ["cold_shower", "an ice cube with a snowflake"],
    ["sauna", "a sauna ladle over rising heat waves"],
    ["early_bed", "a bed with a small clock"],
    ["connection", "two hands in a handshake"],
  ],
  sport: [
    ["gym", "a barbell"],
    ["hiit", "a lightning bolt"],
    ["run", "a running figure"],
    ["cycling", "a bicycle"],
    ["swim", "a swimmer's arm and head over a wave"],
    ["rowing", "a rowing oar crossing a wave"],
    ["walk", "a walking figure"],
    ["tennis", "a tennis racket and ball"],
    ["padel", "a padel racket with holes and a ball"],
    ["football", "a football (soccer ball)"],
    ["basketball", "a basketball"],
    ["icehockey", "an ice hockey stick and puck"],
    ["floorball", "a floorball stick and a ball with holes"],
    ["golf", "a golf flag in a hole"],
    ["team", "a goal net"],
    ["combat", "a boxing glove"],
    ["yoga", "a figure in a yoga tree pose"],
    ["dance", "a dancing figure"],
    ["skate", "an ice skate"],
    ["climbing", "a climbing carabiner with rope"],
    ["hike", "a hiking boot"],
    ["ski", "two crossed downhill skis with poles"],
    ["xcski", "a cross-country skier gliding"],
    ["other", "a medal on a ribbon"],
  ],
  quest: [
    ["cold_shower", "an ice cube"],
    ["double_meditation", "a person in meditation with a sun and a moon above"],
    ["hydration_max", "a large water droplet with a small crown"],
    ["no_phone", "a phone with a diagonal bar across it"],
    ["perfect_sleep", "a sleeping face with closed eyes and a small z"],
    ["full_nutrition", "a bowl of salad with a steak"],
    ["own_sport", "an archery target with an arrow"],
    ["extra_grind", "a flexed arm"],
    ["tribe_player", "a campfire"],
    ["early_bird", "a rising sun with a small bird"],
    ["total_discipline", "a crown"],
    ["bookworm", "an open book with a bookmark"],
  ],
  pillar: [
    ["sleep", "a crescent moon"],
    ["movement", "a flexed arm"],
    ["nutrition", "a steak"],
    ["stress", "a person sitting cross-legged in meditation"],
    ["recovery", "a flame"],
    ["connection", "two hands in a handshake"],
  ],
  onboarding: [
    ["goal-all", "a lightning bolt"],
    ["goal-strength", "a barbell"],
    ["goal-hypertrophy", "a flexed arm"],
    ["goal-fat_loss", "a flame"],
    ["goal-endurance", "a running figure"],
    ["goal-longevity", "a sprouting seedling"],
    ["goal-focus", "a brain"],
    ["struggle-consistency", "a line chart falling"],
    ["struggle-no-plan", "a folded map"],
    ["struggle-motivation", "a battery nearly empty"],
    ["struggle-busy", "an hourglass"],
    ["struggle-quit", "a roller coaster track"],
    ["struggle-alone", "a small island with one palm tree"],
    ["freq-0", "a sprouting seedling"],
    ["freq-1-2", "a running shoe"],
    ["freq-3-4", "a flame"],
    ["freq-5+", "two crossed swords"],
  ],
  mood: [
    ["energy-1", "a sleeping face with closed eyes and a z"],
    ["energy-2", "a tired face with drooping eyes"],
    ["energy-3", "a calm face with a slight smile"],
    ["energy-4", "a smiling face with bright eyes"],
    ["energy-5", "a face with a lightning bolt, wide awake"],
    ["mood-1", "a sad face with a tear"],
    ["mood-2", "a worried face with a downturned mouth"],
    ["mood-3", "a neutral face with a flat mouth"],
    ["mood-4", "a smiling face"],
    ["mood-5", "a beaming face with a wide open smile"],
  ],
};

/** file id for a family entry (badges go by their name's slug). */
export const fileId = (family, id) => (family === "badge" ? slug(id) : id);
