-- Life OS Briefs — structured daily life-optimization plan per user per day.
-- Each row holds 5 domain "cards" (body, recovery, fuel, mind, adjustment)
-- generated by the life-os-brief edge function. One row per user per date.

create table if not exists public.coach_life_os_briefs (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users (id) on delete cascade,
  brief_date    date not null,
  focus         text not null,
  why           text,
  body          jsonb not null default '{}'::jsonb,
  recovery      jsonb not null default '{}'::jsonb,
  fuel          jsonb not null default '{}'::jsonb,
  mind          jsonb not null default '{}'::jsonb,
  adjustment    jsonb not null default '{}'::jsonb,
  generated_at  timestamptz not null default now(),
  unique (user_id, brief_date)
);

-- Index for the common read pattern (user + today)
create index if not exists coach_life_os_briefs_user_date_idx
  on public.coach_life_os_briefs (user_id, brief_date desc);

alter table public.coach_life_os_briefs enable row level security;

-- Users can read their own briefs
create policy "users_select_own_life_os_briefs"
  on public.coach_life_os_briefs for select
  using (auth.uid() = user_id);

-- Users can insert/update their own briefs (edge function runs as the user via anon key)
create policy "users_upsert_own_life_os_briefs"
  on public.coach_life_os_briefs for insert
  with check (auth.uid() = user_id);

create policy "users_update_own_life_os_briefs"
  on public.coach_life_os_briefs for update
  using (auth.uid() = user_id);
