-- ============================================================
-- Vault: holistic wellbeing + self-development expansion across all 5 pillars.
-- 2 articles per category. Honest evidence tiers; caveats in risks[].
-- Idempotent: ON CONFLICT (slug) DO NOTHING.
-- ============================================================

INSERT INTO public.vault_articles
  (category_id, slug, title, subtitle, summary, evidence_tier, read_time_min,
   benefits, risks, body_md, key_takeaways, try_today, references_json, display_order)
VALUES

-- ─────────────── RECIPES / Nutrition ───────────────
('recipes', 'hydration-electrolytes-baseline',
 'Hydration & electrolytes: the daily baseline',
 'The lever most people get wrong by default',
 'How much water you actually need, why plain water is not always enough, and a simple electrolyte rule for training, heat and high-sweat days.',
 'strong', 4,
 ARRAY['Sharper focus and energy','Better training performance','Fewer afternoon crashes and headaches'],
 ARRAY['People with kidney/heart conditions should follow medical advice on fluid and sodium'],
 E'Even mild dehydration (1–2% body mass) measurably drops focus, mood and physical output. But chugging plain water on heavy-sweat days can dilute sodium and backfire.\n\n**Baseline:** roughly 30–35 ml per kg bodyweight per day, more with heat or training. Urine pale-straw, not clear, not dark.\n\n**Electrolytes — when they matter:**\n- Long or sweaty training, sauna, hot days, or low-carb eating\n- Add ~300–500mg sodium per 500ml during/after big sweat sessions\n- A pinch of salt + water + a squeeze of citrus does the job; you do not need expensive sachets\n\n**Daily habit:** a glass of water on waking (you dehydrate overnight) and one with each meal. Coffee and tea count toward fluids despite the myth.',
 ARRAY['Aim ~30–35 ml/kg/day; check urine colour, not a fixed number','Add sodium only around heavy sweat — plain water alone can backfire there'],
 ARRAY['Drink a full glass of water right after waking tomorrow','On your next sweaty session, add a pinch of salt to your bottle'],
 '[{"author":"Sawka et al.","title":"ACSM Position Stand: Exercise and Fluid Replacement","year":2007}]'::jsonb,
 120),

('recipes', 'gut-health-fiber-fermented',
 'Gut health: fiber, fermented foods & the microbiome',
 'Feed the bugs that run your mood and immunity',
 'Why fiber diversity and fermented foods are among the highest-leverage nutrition moves — for digestion, immunity, and even mood via the gut-brain axis.',
 'promising', 4,
 ARRAY['Better digestion and regularity','Supports immunity','Linked to improved mood via the gut-brain axis'],
 ARRAY['Increase fiber gradually to avoid bloating','IBS/GI conditions: get tailored advice'],
 E'Your gut microbiome influences digestion, immunity, inflammation and mood. Two evidence-backed levers feed it:\n\n**1. Plant diversity (fiber).** Aim for **30+ different plants a week** — vegetables, fruit, legumes, nuts, seeds, whole grains, herbs and spices all count. Diversity matters more than quantity; different fibers feed different beneficial microbes.\n\n**2. Fermented foods.** A Stanford trial found that increasing fermented foods raised microbiome diversity and lowered inflammatory markers. Add a small daily serving of:\n- Yogurt or kefir (live cultures)\n- Sauerkraut, kimchi (unpasteurised)\n- Miso, tempeh\n\nStart slow if you are not used to fiber — ramp over a couple of weeks with plenty of water. Whole foods beat fiber supplements for diversity.',
 ARRAY['Chase 30+ different plants a week — diversity feeds a healthy microbiome','A small daily serving of fermented food measurably helps'],
 ARRAY['Count how many distinct plants you ate today; aim higher tomorrow','Add one fermented food (kefir, kimchi, yogurt) to a meal'],
 '[{"author":"Wastyk et al.","title":"Fermented-food diet increases microbiome diversity and decreases inflammatory markers","year":2021}]'::jsonb,
 121),

-- ─────────────── TRAINING / Movement ───────────────
('training', 'daily-steps-movement-floor',
 'Daily movement: the longevity floor',
 'Steps and movement snacks beat the gym-then-sit trap',
 'Why total daily movement — steps and breaking up sitting — may matter more for health than a single workout, and how to hit the floor without a treadmill.',
 'strong', 4,
 ARRAY['Lowers all-cause mortality risk','Improves metabolic health','Boosts mood and energy daily'],
 ARRAY['Build volume gradually if currently sedentary'],
 E'You can train hard for an hour and still be metabolically "sedentary" if you sit the other 15. Total daily movement is its own lever.\n\n**Steps:** benefits rise sharply up to ~7,000–8,000/day, with gains continuing more gently beyond. You do not need 10k — but most desk-workers sit far below the floor.\n\n**Break up sitting:** prolonged sitting harms metabolic health independent of exercise. Stand or walk ~2–3 minutes every 30–45 minutes.\n\n**Movement snacks:** 1–2 minute bursts scattered through the day — a flight of stairs, 20 bodyweight squats, a brisk walk to take a call. These add up and blunt post-meal glucose spikes.\n\nThe gym is the stimulus; daily movement is the foundation under it.',
 ARRAY['~7–8k steps/day captures most of the health benefit','Breaking up sitting matters even if you train'],
 ARRAY['Take a 2-minute walk every 45 minutes today','Do a "movement snack" (stairs or 20 squats) after lunch'],
 '[{"author":"Paluch et al.","title":"Daily steps and all-cause mortality: a meta-analysis","year":2022}]'::jsonb,
 120),

('training', 'mobility-posture-8-min',
 'Mobility & posture: 8 minutes to stay pain-free',
 'A daily routine for desk-bound bodies',
 'A short, repeatable mobility routine targeting the areas that stiffen from sitting — hips, thoracic spine, shoulders — to keep you moving well and lifting safely.',
 'promising', 4,
 ARRAY['Reduces stiffness and nagging aches','Improves lifting positions','Counteracts desk posture'],
 ARRAY['Sharp pain is a stop signal — mobility work should not hurt','Persistent pain needs a physio, not stretching'],
 E'Sitting shortens hip flexors, rounds the upper back and locks the shoulders. Eight minutes a day keeps the hinges oiled.\n\n**The routine (hold/repeat ~45–60s each):**\n1. **Hip flexor stretch** — half-kneel, tuck pelvis, lean forward. Both sides.\n2. **90/90 hip rotations** — sit, rotate knees side to side.\n3. **Thoracic rotations** — on all fours, hand behind head, rotate open. Both sides.\n4. **Cat-cow** — flow the spine through flexion and extension.\n5. **Doorway pec stretch** — open the chest, undo the slouch.\n6. **Deep squat hold** — sit in the bottom of a squat, heels down.\n\nDo it as a morning primer or a midday desk-reset. Consistency beats intensity — every day at 8 minutes beats once a week for an hour.',
 ARRAY['Target hips, t-spine and shoulders — the desk casualties','Daily 8 min beats occasional long sessions'],
 ARRAY['Run the 8-minute routine once today','Set a midday reminder to do the deep squat hold + chest stretch'],
 '[{"author":"Behm et al.","title":"Acute effects of stretching on range of motion and performance","year":2016}]'::jsonb,
 121),

-- ─────────────── RECOVERY & SLEEP ───────────────
('recovery', 'sauna-heat-exposure',
 'Heat exposure: sauna for recovery & longevity',
 'One of the most studied recovery tools there is',
 'What the (largely Finnish) sauna research shows for cardiovascular health, recovery and mood — plus a simple, safe protocol.',
 'promising', 4,
 ARRAY['Cardiovascular and longevity associations','Aids relaxation and recovery','Mood and stress benefits'],
 ARRAY['Hydrate well; do not combine with alcohol','Pregnancy, heart conditions, low blood pressure: check with a doctor'],
 E'Large Finnish cohort studies link frequent sauna use to lower cardiovascular and all-cause mortality — partly mimicking the cardiovascular load of moderate exercise (heart rate up, vessels dilate).\n\n**A simple protocol:**\n- ~80–90°C, 10–20 minutes per session\n- 2–4 sessions per week shows the strongest associations\n- Cool down and rehydrate between rounds\n\n**Timing with training:**\n- Great on rest days or well after lifting\n- Like cold, very intense heat right after strength work may slightly interfere with adaptation — leave a gap if muscle gain is the priority\n\nNo sauna? A hot bath (~40°C, 20 min) captures some of the same passive-heat benefits and aids sleep if done 1–2h before bed.',
 ARRAY['2–4 sauna sessions/week tracks with strong health associations','A hot bath before bed is a solid no-sauna alternative'],
 ARRAY['Book one sauna or hot-bath session this week','If using it for sleep, finish 1–2h before bed'],
 '[{"author":"Laukkanen et al.","title":"Sauna bathing and cardiovascular & all-cause mortality","year":2015}]'::jsonb,
 120),

('recovery', 'hrv-how-to-use-it',
 'HRV: what it is and how to actually use it',
 'Stop chasing the number; use the trend',
 'A plain-English guide to heart-rate variability — what it reflects, why the daily number is noisy, and how to use the trend to guide training and recovery.',
 'promising', 4,
 ARRAY['Objective recovery signal','Helps time hard vs easy days','Flags overreaching early'],
 ARRAY['HRV is noisy day-to-day — never act on a single reading','Not a medical diagnostic'],
 E'HRV measures the tiny variation between heartbeats. Higher generally means your parasympathetic ("recovery") system is well-engaged; a suppressed HRV can signal fatigue, stress, illness or poor sleep.\n\n**The trap:** the daily number is noisy. One low morning means little.\n\n**How to actually use it:**\n- Measure the same way each morning (most wearables do this automatically)\n- Watch the **7-day rolling trend**, not single days\n- Trend dropping for several days → favour easy training, sleep, lower stress\n- Trend stable/rising → green light for harder sessions\n\n**Biggest HRV levers** are unglamorous: sleep, alcohol (drops it hard), training load, and stress. Use HRV as one input among how you feel and perform — not the boss of you.',
 ARRAY['Use the 7-day HRV trend, not single readings','Sleep and alcohol move HRV more than any gadget tweak'],
 ARRAY['Check your HRV trend (not today''s number) before your next hard session','Note how last night''s sleep/alcohol tracked with it'],
 '[{"author":"Plews et al.","title":"Training adaptation and HRV in elite endurance athletes","year":2013}]'::jsonb,
 121),

-- ─────────────── MIND / Self-development ───────────────
('mind', 'deep-work-train-focus',
 'Deep work: train focus like a muscle',
 'Reclaim attention in a distracted world',
 'Why fragmented attention quietly wrecks output and wellbeing, and a practical system to build the capacity for sustained, single-tasked focus.',
 'promising', 5,
 ARRAY['More output in less time','Lower stress from task-switching','A trainable, compounding skill'],
 ARRAY['Focus capacity builds gradually — start with short blocks'],
 E'Every time you switch tasks, attention leaves a "residue" on the old one — you are never fully on the new task. Chronic switching feels busy but produces shallow work and frazzle.\n\n**Build the muscle:**\n1. **Time-block** one 60–90 min "deep work" block daily for your most important task.\n2. **Remove triggers** — phone in another room (not just face-down), notifications off, one browser tab.\n3. **Single-task** — one thing until the block ends. When the urge to switch hits, note it and return.\n4. **Start small** — 25 minutes (a Pomodoro) if 90 feels impossible, and extend over weeks.\n\n**Protect it:** batch shallow work (email, messages) into set windows instead of all day. The goal is fewer, deeper hours — not more frantic ones.',
 ARRAY['Task-switching leaves attention residue — single-task to go deep','Phone in another room beats willpower'],
 ARRAY['Block 60 minutes tomorrow for one important task, phone elsewhere','Batch your email/messages into 2 set windows today'],
 '[{"author":"Newport, C.","title":"Deep Work","year":2016},{"author":"Leroy, S.","title":"Why is it so hard to do my work? Attention residue","year":2009}]'::jsonb,
 120),

('mind', 'five-minute-journal',
 'The 5-minute journal: gratitude, intention, review',
 'A tiny daily practice with outsized returns',
 'A simple morning-and-evening journaling structure — gratitude, intention, and review — shown to improve mood, focus and follow-through.',
 'promising', 3,
 ARRAY['Lifts baseline mood','Sharpens daily priorities','Builds self-awareness over time'],
 ARRAY['Skip the toxic-positivity trap — be honest, not relentlessly upbeat'],
 E'Two minutes in the morning, three at night. The structure does the work so you do not have to stare at a blank page.\n\n**Morning (2 min):**\n- 3 things you are grateful for (specific beats generic — "the coffee was perfect" over "my life")\n- 1 line: what would make today great?\n- 1 line: a short affirmation or focus for the day\n\n**Evening (3 min):**\n- 3 good things that happened today\n- 1 line: what could have made today better? (learning, not self-flagellation)\n\nGratitude practices have repeatedly shown small but real improvements in mood and wellbeing. The intention-setting turns the day from reactive to deliberate; the evening review compounds self-awareness.\n\nKeep it short forever. A 5-minute habit you keep beats a journal you abandon.',
 ARRAY['Structure beats a blank page — gratitude + intention + review','Be specific and honest; keep it to 5 minutes'],
 ARRAY['Write your 3 gratitudes + "what makes today great" tomorrow morning','Do the 3-good-things review before bed tonight'],
 '[{"author":"Emmons & McCullough","title":"Counting blessings versus burdens: gratitude and wellbeing","year":2003}]'::jsonb,
 121),

('mind', 'discipline-systems-over-motivation',
 'Systems beat motivation',
 'Design your environment so the right thing is the easy thing',
 'Motivation is unreliable; environment and systems are not. How to engineer your defaults so discipline takes less willpower.',
 'strong', 4,
 ARRAY['Less reliance on fragile motivation','Higher follow-through','Compounds into identity over time'],
 ARRAY['Systems support goals — you still have to start'],
 E'Motivation is a feeling; it comes and goes. People with great "discipline" usually just built better systems and environments so the right action is the path of least resistance.\n\n**Four levers:**\n1. **Make it obvious** — lay out gym clothes; put the book on the pillow; keep fruit visible. Cues drive behaviour.\n2. **Make it easy** — shrink the first step. "Do 1 push-up" / "read 1 page". Starting is the hard part; reduce its friction.\n3. **Make it attractive** — pair a habit you should do with one you want ("podcast only while walking").\n4. **Remove friction from bad defaults** — phone out of the bedroom, junk food out of the house. You will not eat what is not there.\n\n**Anchor to identity:** "I am someone who trains" beats "I want to get fit". Each rep is a vote for the person you are becoming.',
 ARRAY['Engineer environment so the right thing is the easy thing','Cast votes for an identity, not just chase outcomes'],
 ARRAY['Set up ONE obvious cue tonight (clothes out, book on pillow)','Remove one bad-default trigger from your environment'],
 '[{"author":"Clear, J.","title":"Atomic Habits","year":2018},{"author":"Wood & Neal","title":"Habits in everyday life","year":2007}]'::jsonb,
 122),

-- ─────────────── NERVOUS SYSTEM ───────────────
('nervous-system', 'morning-protocol-set-the-day',
 'The morning protocol: set your nervous system',
 'The first 30 minutes shape the next 16 hours',
 'A short, stackable morning routine — light, movement, no-phone, breath — that anchors your circadian clock and starts the day regulated instead of reactive.',
 'promising', 4,
 ARRAY['Steadier energy and mood all day','Better sleep that night','Starts the day proactive, not reactive'],
 ARRAY['Adapt to your context — consistency matters more than perfection'],
 E'How you spend the first 30 minutes biases your whole day''s nervous system. A simple stack:\n\n1. **Light first, phone later.** Get outside (or to a bright window) for 5–10 min within an hour of waking. This anchors your circadian clock and lifts morning cortisol in the healthy, natural way. Delay the phone — do not start the day in a reactive scroll.\n2. **Move.** 5 minutes of easy movement — a walk, mobility, a few squats — wakes the body and lifts mood.\n3. **Breathe or sit.** 2–3 minutes of slow breathing or stillness sets a calm baseline before the demands hit.\n4. **Hydrate.** A glass of water; you woke up dehydrated.\n\nYou do not need all four to be long. Ten focused minutes, done daily, beats an elaborate routine you abandon. The theme: regulate *before* you react.',
 ARRAY['Light + movement early, phone later — regulate before you react','10 consistent minutes beats an elaborate routine you drop'],
 ARRAY['Tomorrow: light + water before you touch your phone','Add 5 minutes of easy movement to your morning'],
 '[{"author":"Blume et al.","title":"Effects of light on human circadian rhythms, sleep and mood","year":2019}]'::jsonb,
 120),

('nervous-system', 'vagal-tone-builders',
 'Vagal tone: train your calm',
 'Strengthen the brake pedal of your nervous system',
 'The vagus nerve is your body''s brake on stress. Simple daily practices that, over time, raise vagal tone so you recover from stress faster.',
 'promising', 4,
 ARRAY['Faster recovery from stress','Better emotional regulation','Improved HRV over time'],
 ARRAY['These are supports, not treatments for anxiety disorders'],
 E'The vagus nerve runs the parasympathetic "rest and digest" system — your brake on the stress response. Higher vagal tone means you down-shift from stress faster. It is partly trainable.\n\n**Daily builders (pick a few):**\n- **Slow breathing** — ~6 breaths/min (inhale 4–5s, exhale 5–6s) for a few minutes. The single most direct lever.\n- **Long exhales / humming / chanting** — vibration of the vocal cords stimulates the vagus.\n- **Cold splash** — brief cold water on the face triggers the calming dive reflex.\n- **Moderate exercise + good sleep** — the unglamorous foundations.\n- **Connection** — warm social contact raises vagal tone (it is a social-engagement nerve).\n\nThink of it like training a muscle: a little, most days, raises your baseline calm over weeks.',
 ARRAY['~6 breaths/min is the most direct vagal-tone lever','Humming, cold-on-face and warm connection all help'],
 ARRAY['Do 3 minutes of 6-breaths-per-minute breathing today','Try a cold splash on the face when stressed'],
 '[{"author":"Laborde et al.","title":"Slow-paced breathing, vagal activity and wellbeing","year":2022}]'::jsonb,
 121)

ON CONFLICT (slug) DO NOTHING;
