-- Vault · Wisdom: the practice loop on every lesson, and thirteen new pieces
-- from the thinkers the course did not yet carry.
--
-- Original educational text on documented ideas. No quotations are attributed
-- to any thinker; every piece names its source works in references_json and a
-- "Note" row states the relationship. The evidence chip rates the PRACTICE
-- (what the reader does in try_today), never the philosophy behind it.
-- Mirrored for the coach in supabase/functions/_shared/wisdom-catalog.ts and
-- for the client map in src/data/vault-masters.ts / vault-paths.ts. Update all
-- together.

-- ── 1. The eleven course lessons get a master, a question in, a question out ──
UPDATE public.vault_articles SET master_slug = NULL, practice_minutes = 10,
  reflect_prompt = 'Which teacher on this list have you swallowed whole, practice and metaphysics together? What did you keep, and what did you quietly drop?',
  integrate_prompt = 'You wrote three sentences for one source. Which of the three was hardest to finish, and what does that say about how you read?'
WHERE slug = 'how-to-read-a-teacher';

UPDATE public.vault_articles SET master_slug = 'clear', practice_minutes = 10,
  reflect_prompt = 'Finish the sentence honestly, not aspirationally: right now my actions say I am the kind of person who …',
  integrate_prompt = 'You put one identity sentence where you would see it at check-in time. Did it change what you did, or only how you felt about what you did?'
WHERE slug = 'atomic-habits-identity';

UPDATE public.vault_articles SET master_slug = 'tolle', practice_minutes = 5,
  reflect_prompt = 'Which thought loop ran most often this week, and how many times did it actually change anything?',
  integrate_prompt = 'After three sixty-second returns: how long did the gap last before the thinker started again, and what pulled you back?'
WHERE slug = 'power-of-now-presence';

UPDATE public.vault_articles SET master_slug = 'tolle', practice_minutes = 5,
  reflect_prompt = 'Name one role, opinion or number you would feel smaller without. What does defending it cost you?',
  integrate_prompt = 'You caught one identification in the act. What did the defence feel like in the body, and what happened when you did not act on it?'
WHERE slug = 'new-earth-ego';

UPDATE public.vault_articles SET master_slug = 'byrne', practice_minutes = 5,
  reflect_prompt = 'Which feeling do you fight hardest when it shows up at check-in time?',
  integrate_prompt = 'You welcomed one difficult feeling instead of fighting it. Did it grow, shrink or change shape, and how long did it stay?'
WHERE slug = 'greatest-secret-awareness';

UPDATE public.vault_articles SET master_slug = 'sharma', practice_minutes = 15,
  reflect_prompt = 'Score your last month on the eight forms, one to five each. Which score would surprise someone who only sees your streak?',
  integrate_prompt = 'You moved one hour toward the poorest form. Was the resistance in the calendar, or in you?'
WHERE slug = 'eight-forms-of-wealth';

UPDATE public.vault_articles SET master_slug = 'jung', practice_minutes = 10,
  reflect_prompt = 'Who irritated you out of all proportion this week, and which quality in them did it?',
  integrate_prompt = 'You traced one irritation back to a quality you disown in yourself. Where has that quality shown up in you since, and what did you do with it?'
WHERE slug = 'jung-shadow-individuation';

UPDATE public.vault_articles SET master_slug = 'dispenza', practice_minutes = 10,
  reflect_prompt = 'Which upcoming moment do you already rehearse badly in your head, obstacle and all?',
  integrate_prompt = 'You rehearsed one scene with the feeling included. When the real moment came, what was familiar and what was not?'
WHERE slug = 'dispenza-rehearsal';

UPDATE public.vault_articles SET master_slug = 'huberman', practice_minutes = 10,
  reflect_prompt = 'Of light, breath, dopamine and cold, which one is missing from your mornings, and what fills its place?',
  integrate_prompt = 'You ran one protocol for three days. What changed in the check-in numbers, and what changed that no number tracks?'
WHERE slug = 'huberman-protocol-stack';

UPDATE public.vault_articles SET master_slug = 'watts', practice_minutes = 10,
  reflect_prompt = 'What are you gripping right now, a result, a streak, a person, that the gripping itself is spoiling?',
  integrate_prompt = 'You did one thing purely for its own sake, unlogged. How did it feel not to count it, and what did you want to count anyway?'
WHERE slug = 'watts-wisdom-of-insecurity';

UPDATE public.vault_articles SET master_slug = NULL, practice_minutes = 20,
  reflect_prompt = 'Which of the nine practices would you keep if you could keep only one, and why that one?',
  integrate_prompt = 'You ran the stack for a week. Which practice earned its minutes, and which one did you let go of without missing it?'
WHERE slug = 'wisdom-practice-stack';

-- ── 2. Thirteen new pieces ──────────────────────────────────────────────────
INSERT INTO public.vault_articles
  (category_id, slug, title, subtitle, summary, evidence_tier, read_time_min,
   benefits, risks, body_md, why_it_matters, key_takeaways, try_today,
   references_json, quiz, display_order, lesson_number, course_role,
   master_slug, reflect_prompt, integrate_prompt, practice_minutes)
VALUES

-- ─── Frankl ───
('wisdom', 'frankl-meaning-responsibility',
 'Frankl: Meaning Is Made, Not Found',
 'Viktor Frankl''s reversal: stop asking what you want from life and answer what life is asking of you',
 'Frankl, a psychiatrist who survived four camps, built a therapy on one observation: people who had something to answer for held on. His method turns the question around. Meaning is not a feeling you wait for; it is a task you take on.',
 'promising', 5,
 ARRAY['A concrete way to locate meaning in an ordinary week: through work, through people, through how you carry what cannot be changed','A reframe for suffering that does not pretend it is good, only that your response to it is still yours','The link between purpose and follow-through that the habit literature keeps finding'],
 ARRAY['Meaning research shows strong associations with wellbeing and health behaviour; it cannot prove that adopting a purpose causes the benefits','Frankl''s claims come from clinical observation and his own survival, not controlled trials; the practice earns its chip, the biography does not','A meaning that is only ever future-facing can become another way of not living now'],
 E'Viktor Frankl was a Viennese psychiatrist before the war and a prisoner in Auschwitz and Dachau during it. Man''s Search for Meaning, written in nine days in 1946, is half memoir and half the outline of the therapy he called logotherapy. Its claim is narrow and testable in your own week: the people who kept going had something to answer for. A manuscript to finish. A person waiting. A way of carrying a situation nobody could change.\n\n**The question, reversed**\nMost of us ask what we want from life and then feel let down by the answer. Frankl turns it around. Life is asking questions of you, in the concrete form of this week''s situations, and you answer with what you do. Meaning is not found lying around like a coin; it is made by responding. That is why he called responsibility the other half of freedom. You are free to choose your response; you are responsible for the one you choose.\n\n**Three roads to it**\nFrankl named three ways meaning shows up. Through what you create or do: your craft, your training, the work only you will finish. Through what you encounter: people, beauty, love, the things that ask you to pay attention. And through the attitude you take toward suffering you cannot remove: illness, loss, an injury that ended a season. The third road is the one that made his method famous, and it is also the one most often misused. He never said suffering is good. He said that when it is unavoidable, the stance you take toward it is still yours, and that stance can carry meaning.\n\n**What the research adds**\nSince Steger''s 2006 meaning-in-life work, presence of meaning has been measured in tens of thousands of people. It tracks with lower depression, better sleep, more physical activity and, in large cohorts, lower mortality. Those are associations. They do not show that writing a purpose statement makes you healthier. What they do show is that the thing Frankl pointed at is real, common and measurable, and that people who have it behave differently on ordinary days. That is why the chip says promising: the practice below has a plausible mechanism and early support, and no trial has run it as written.\n\n**Where it meets your week**\nThe streak and the check-in are answers to a question you set for yourself. They hold up on days when the question is alive and fall apart when it goes quiet. Frankl''s move is to keep the question audible: not "do I feel like it" but "what is this day asking of me, and who is on the other end of the answer".',
 'A streak survives on the days you remember what it is for. Frankl gives you a way to keep that answer in reach, and a way to stand toward the parts of a week you cannot change.',
 ARRAY['Meaning is a response, not a discovery: life asks, you answer with action.','Three roads: what you make, whom you meet, how you carry what cannot be changed.','The evidence supports the pattern, not the biography; run the practice and judge it by your week.'],
 ARRAY['Write down three questions this month is asking of you, in concrete terms: a person, a task, a situation to carry.','Choose one and write the answer as an action you will take within seven days, with a day attached.','Do it, and note afterwards whether the meaning arrived before, during or after the action.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Viktor Frankl; not affiliated with the author''s estate or publishers"}, {"author": "Frankl, V. E.", "title": "Man''s Search for Meaning", "year": 1946}, {"author": "Steger, M. F. et al.", "title": "The Meaning in Life Questionnaire: Assessing the presence of and search for meaning in life (J. Couns. Psychol.)", "year": 2006}, {"author": "Cohen, R. et al.", "title": "Purpose in life and its relationship to all-cause mortality and cardiovascular events: a meta-analysis (Psychosom. Med.)", "year": 2016}]'::jsonb,
 '[{"q": "What does Frankl mean by reversing the question?", "choices": ["Stop wanting things", "Ask what life is asking of you and answer with action", "Find your purpose by thinking harder"], "correct": 1, "explain": "Meaning is made by responding to the concrete situations in front of you, not found by introspection alone."}, {"q": "What does the meaning-in-life research actually show?", "choices": ["Purpose statements cause better health", "Presence of meaning is associated with better wellbeing and behaviour", "Nothing measurable"], "correct": 1, "explain": "Strong associations in large samples, not proof of cause. The practice earns a promising chip, not a strong one."}]'::jsonb,
 320, NULL, 'protocol',
 'frankl',
 'Which difficulty in your life have you been asking "why me" about? What would it look like to ask what it is asking of you instead?',
 'You answered one of life''s questions with an action. Did the meaning arrive before the action, during it, or only afterwards?',
 10),

-- ─── Epictetus ───
('wisdom', 'epictetus-dichotomy-of-control',
 'Epictetus: The Line Between Up to You and Not',
 'A former slave''s first lesson: sort everything into what is yours to move and what never was',
 'The Enchiridion opens with a sorting rule. Some things are up to us: our judgements, our aims, what we go after and what we avoid. Others are not: the body, reputation, other people, outcomes. Most distress comes from treating the second group as the first. The practice is the sort, done daily, in writing.',
 'promising', 4,
 ARRAY['A five-minute morning practice that turns vague worry into one action and one release','The frame behind cognitive therapy: it is the judgement about the event, not the event, that you can work on','A way to compete hard for outcomes you do not control without being owned by them'],
 ARRAY['The sort can be misread as passivity; the Stoics trained for outcomes as hard as anyone, they just refused to stake their peace on them','Cognitive reappraisal has solid trial evidence; the Stoic version as written has plausible mechanism and mostly indirect support, hence promising','Some things are partly up to you; the sort is a first cut, not a law'],
 E'Epictetus was born a slave in what is now Turkey, was freed, taught philosophy in Rome until the emperor expelled the philosophers, and then taught in Greece until he died around 135 AD. He wrote nothing down. His student Arrian recorded the lectures as the Discourses and condensed them into a pocket manual, the Enchiridion. Its first paragraph is the whole method.\n\n**The sort**\nSome things are up to us and some are not. Up to us: our opinions, our impulses, what we desire and what we avoid, everything that is our own doing. Not up to us: the body, property, reputation, position, everything that is not our own doing. Epictetus then makes the claim that gives Stoicism its edge. If you treat what is not up to you as if it were, you will be blocked, frustrated and at the mercy of other people. If you keep the line straight, nobody can compel you and nothing can harm the part of you that matters.\n\n**What it is not**\nThe sort is often read as a licence to stop caring. The Stoics did not read it that way. They ran for office, led armies, wrote to their students about training the body. The distinction they drew was between the target and the aim. You aim at the outcome with everything you have. You stake your peace only on the aim, because the outcome was never fully yours. Later Stoics called this the reserve clause: I will do this, if nothing prevents it. It is the mental posture of someone who trains hard for a race they may not win.\n\n**Where it meets the science**\nThe line from the Enchiridion runs straight into modern cognitive therapy. Albert Ellis and Aaron Beck both credited Epictetus for the observation that it is our judgements about events, not events themselves, that disturb us, and cognitive reappraisal is now one of the best-supported techniques in psychology. The daily sort as a written practice has not been tested on its own in a trial; that is why the chip says promising rather than strong. The mechanism is the reappraisal literature''s; the ritual is the Stoics''.\n\n**Where it meets your week**\nA rank on a board, a session that goes badly, someone''s reaction to your post: none of it is in the first column. The training you do, how you read the number, whether you show up tomorrow: all of it is. The practice below takes five minutes and leaves you with one action and one thing set down.',
 'Boards, battles and streaks put numbers in front of you every day that you do not fully control. The sort is how you compete for them without letting them run your nervous system.',
 ARRAY['Up to you: judgements, aims, effort. Not up to you: outcomes, bodies, other people.','Aim at outcomes with everything; stake your peace only on what is yours.','The frame is the ancestor of cognitive reappraisal, which has strong evidence; the written daily sort is promising.'],
 ARRAY['Write down the three things weighing on you this morning.','Draw a line: for each, name the part that is up to you and the part that is not.','For the up-to-you column, one action today. For the other column, one sentence of release, said once, out loud.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Epictetus as recorded by Arrian; the Enchiridion and Discourses are in the public domain"}, {"author": "Epictetus (Arrian, ed.)", "title": "Enchiridion", "year": 125}, {"author": "Robertson, D.", "title": "How to Think Like a Roman Emperor: The Stoic Philosophy of Marcus Aurelius", "year": 2019}, {"author": "Webb, T. L. et al.", "title": "Dealing with feeling: A meta-analysis of the effectiveness of strategies derived from the process model of emotion regulation (Psychol. Bull.)", "year": 2012}]'::jsonb,
 '[{"q": "Which of these is in the up-to-you column?", "choices": ["Your rank on the board", "How you judge your rank on the board", "What other people think of your rank"], "correct": 1, "explain": "Judgements, aims and effort are yours. The number and other people''s reactions are not."}, {"q": "What did the Stoics do about outcomes they could not control?", "choices": ["Stopped trying for them", "Aimed at them fully but staked their peace on the aim, not the result", "Pretended they did not want them"], "correct": 1, "explain": "The reserve clause: full effort, held loosely."}]'::jsonb,
 321, NULL, 'protocol',
 'epictetus',
 'What did you try to control this week that was never up to you, and what did the trying cost?',
 'You sorted three worries. How much of your day''s tension sat in the column that was never yours?',
 5),

-- ─── Marcus Aurelius ───
('wisdom', 'marcus-aurelius-morning-practice',
 'Marcus Aurelius: Notes to Himself',
 'The most powerful man alive kept a private notebook to prepare for difficult people and to zoom out',
 'The Meditations were never meant to be read. They are an emperor''s reminders to himself, written in camp during a plague and a war, and they show a practice: expect the day''s difficulty before it arrives, name what is yours in it, and look at it from far enough away that it shrinks. The practice is a three-line morning note.',
 'promising', 4,
 ARRAY['A morning ritual that puts a gap between a difficult person and your first reaction','The view from above: a reliable way to shrink a problem to its real size','A private page that has some of the evidence base of expressive writing behind it'],
 ARRAY['Expressive writing has trial support; the specific Stoic three-line note has not been tested on its own, so the chip says promising','Preparing for difficulty can tip into rehearsing dread; keep the note short and end it with the zoom-out','Marcus wrote as a Stoic with a cosmology most readers do not share; the practice works without it'],
 E'Marcus Aurelius ruled Rome from 161 to 180 AD, through the Antonine plague and years of war on the Danube. In camp, at night, he wrote in Greek to himself. He called the notebook "to himself"; we call it the Meditations. Nothing in it is addressed to a reader. That is what makes it useful: it is a working document from someone under pressure, and the practices repeat because he needed them repeated.\n\n**Expect the difficult ones**\nThe most-quoted passage in the book, at the start of Book 2, is a morning drill. Tell yourself before the day starts that you will meet people who are meddling, ungrateful, arrogant, dishonest. Then remind yourself why: they do not know better, and they are, like you, part of the same whole, so you cannot be harmed by them and cannot rightly be angry with them. Whatever you make of the metaphysics, the mechanics are sharp. Naming the difficulty before it arrives means it lands on a prepared mind. The gap between the event and your reaction, the thing Epictetus'' sort creates, is put in place in advance.\n\n**The view from above**\nThe second recurring move is scale. Marcus repeatedly imagines looking down on cities and armies from a height, or forward across centuries, until the thing that seemed enormous is a small event among countless others. Pierre Hadot called this the view from above and traced it through the whole Stoic tradition. It is not detachment. It is a change of frame that lets you act without the distortion of a problem that has filled the whole windscreen.\n\n**What the research adds**\nWriting privately about difficult experiences has been studied since Pennebaker''s 1986 experiments: modest but repeated benefits for mood, health visits and immune markers across dozens of trials. The morning note below borrows that mechanism and adds two Stoic moves, the preparation and the zoom-out. As a package it has not been trialled, which is why the chip is promising rather than strong.\n\n**Where it meets your week**\nSquads, boards and a comment thread put other people in front of you before breakfast. A three-line note takes under five minutes, and it is written before you have looked at any of them.',
 'Other people are the part of your day you control least and react to most. Marcus wrote his way into a prepared mind every morning; the same three lines fit before your first check-in.',
 ARRAY['Name the day''s likely difficulty before it arrives, and it lands on a prepared mind.','The view from above shrinks a problem to its real size without pretending it is not there.','Private writing about difficulty has trial support; the Stoic note is that mechanism with two extra moves.'],
 ARRAY['Before you open anything else, write one line: the person or situation most likely to test you today.','Write one line naming what in that situation is yours: your tone, your effort, your reading of it.','Write one line from above: this day, this week, seen from a year away. Then close the notebook and start.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Marcus Aurelius; the Meditations are in the public domain"}, {"author": "Marcus Aurelius", "title": "Meditations (Ta eis heauton)", "year": 180}, {"author": "Hadot, P.", "title": "The Inner Citadel: The Meditations of Marcus Aurelius", "year": 1998}, {"author": "Pennebaker, J. W. & Beall, S. K.", "title": "Confronting a traumatic event: Toward an understanding of inhibition and disease (J. Abnorm. Psychol.)", "year": 1986}]'::jsonb,
 '[{"q": "Why does Marcus name difficult people before the day begins?", "choices": ["To avoid them", "So the difficulty lands on a prepared mind with a gap before the reaction", "To feel superior to them"], "correct": 1, "explain": "The preparation puts the gap between event and reaction in place in advance."}, {"q": "What is the view from above for?", "choices": ["Detaching from life", "Seeing a problem at its real size so you can act without distortion", "Feeling insignificant"], "correct": 1, "explain": "A change of frame, not a retreat from action."}]'::jsonb,
 322, NULL, 'protocol',
 'marcus-aurelius',
 'Which person or situation is most likely to test you today, and what is your usual first reaction to it?',
 'You wrote the morning note before the day. When the difficulty came, was there a gap between it and your reaction that was not there before?',
 5),

-- ─── Seneca ───
('wisdom', 'seneca-on-time',
 'Seneca: You Are Not Short of Time, You Are Wasting It',
 'A rich, busy, compromised man on the one resource nobody gets back, and the audit that shows where yours goes',
 'Seneca''s short essay on the shortness of life makes one argument: life is long enough if you use it, and most people hand their hours to other people''s demands, to distraction and to a future that never arrives. The practice is an honest audit of the last seven days and one hour reclaimed.',
 'promising', 4,
 ARRAY['A clear look at where a week actually went, which is almost never where you think','One reclaimed hour a week, chosen on purpose, which compounds faster than any productivity method','The evening review: a Stoic habit that turns the day into feedback instead of a blur'],
 ARRAY['Time-use awareness helps people change how they spend time; the effect sizes are modest and the audit below has not been trialled as written','Seneca was wealthy and politically compromised; read him for the argument, not as a model of a simple life','An audit can become a second job; do it once a week, not daily'],
 E'Lucius Annaeus Seneca was a playwright, a senator, tutor and then adviser to Nero, one of the richest men in Rome, and a Stoic who was ordered to kill himself in 65 AD and did. He is the most human of the Stoics because he failed at his own advice often and wrote about it anyway. His essay On the Shortness of Life is addressed to a friend, Paulinus, who ran Rome''s grain supply, and it is short enough to read in an hour.\n\n**The argument**\nWe complain that life is short. Seneca says it is not; it is long enough, and we waste most of it. Wasted how? On other people''s claims on us, on business that is not ours, on drink and sleep past need, on worry about the future and regret about the past, and above all on postponement: the plan to really start living once some condition is met. People guard their money and their land fiercely, he notes, and hand out their hours to anyone who asks.\n\n**The evening review**\nElsewhere, in the essay On Anger, Seneca describes a nightly habit he learned from his teacher Sextius: when the lamp is out and the house is quiet, go back over the day and ask what you did badly, what you did well, what you left undone. He says he sleeps better for it. It is the ancestor of every evening reflection, including the one in this app.\n\n**What the research adds**\nThe modern version of Seneca''s audit is time-use research. When people record how they actually spend a week, the record and the story they told themselves diverge, and the divergence is where the change comes from: seeing hours go to low-value defaults tends to move them. The effects in trials are modest, and the specific one-week audit plus one reclaimed hour has not been tested on its own. The mechanism is plausible and the cost is fifteen minutes, so the chip says promising.\n\n**Where it meets your week**\nThe check-in already asks how you slept and whether you trained. It does not ask where the other fourteen hours went. Once a week, this practice does, and it ends with one hour moved on purpose rather than a vague resolve to do better.',
 'Consistency is a time problem before it is a motivation problem. Seneca''s audit shows where the hours actually go, and moving one of them on purpose is the smallest change that compounds.',
 ARRAY['Life is long enough if you use it; most hours go to demands, distraction and postponement.','Review the day at night: what went badly, what went well, what was left undone.','Time-use awareness changes behaviour modestly and reliably; the weekly audit is the practical form.'],
 ARRAY['Take the last seven days and sort your waking hours roughly into three blocks: given to others'' demands, lost to distraction, lived deliberately.','Find the one hour you would most like back, and name what took it.','Put that hour in next week''s calendar with a specific use, and protect it like money.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Seneca; the essays and letters are in the public domain"}, {"author": "Seneca", "title": "De Brevitate Vitae (On the Shortness of Life)", "year": 49}, {"author": "Seneca", "title": "De Ira (On Anger), Book III, on the evening review", "year": 45}, {"author": "Whillans, A. V. et al.", "title": "Buying time promotes happiness (PNAS)", "year": 2017}]'::jsonb,
 '[{"q": "What is Seneca''s answer to \"life is too short\"?", "choices": ["It is, so hurry", "It is long enough; most of it is wasted on demands, distraction and postponement", "Time is an illusion"], "correct": 1, "explain": "The essay''s whole argument is that the shortage is in the use, not the supply."}, {"q": "What does the weekly audit end with?", "choices": ["A feeling of guilt", "One specific hour reclaimed and scheduled", "A new productivity app"], "correct": 1, "explain": "Awareness changes behaviour when it becomes one concrete move."}]'::jsonb,
 323, NULL, 'protocol',
 'seneca',
 'If your last seven days were the shape of your whole life, what would a stranger say you value?',
 'You reclaimed one hour. What did you put in it, and did it feel like living or like another task?',
 15),

-- ─── Aristotle ───
('wisdom', 'aristotle-habituation',
 'Aristotle: Character Is a Habit',
 'Twenty-three centuries before the habit books, the argument that virtue is built by doing, not by knowing',
 'In the Nicomachean Ethics, Aristotle says we become just by doing just acts and brave by doing brave ones, the way builders become builders by building. Character is a settled disposition formed by repetition. The practice is choosing one trait, finding the smallest act it is made of, and repeating it for a week.',
 'strong', 4,
 ARRAY['A clear model of how a trait is built: not by insight, but by repeated acts until they feel like you','The mean: a way to aim a trait between its two failure modes instead of overshooting','The habit-formation research, which supports the mechanism with real numbers'],
 ARRAY['The habit literature supports repetition to automaticity; Aristotle''s wider claims about the good life are philosophy, not findings','The famous line "we are what we repeatedly do" is Will Durant''s 1926 summary, not Aristotle''s sentence; the idea is his, the quote is not','Choosing a trait you do not actually value produces a performance, not a habit'],
 E'Aristotle taught in Athens in the fourth century BC, and the Nicomachean Ethics, named for his son, is the set of lecture notes that survived. Book II makes an argument that the modern habit literature has spent forty years confirming. Virtues are not given to us by nature and they are not learned by hearing about them. They are acquired by doing, the way skills are. You become a builder by building; you become brave by doing brave things while afraid.\n\n**Hexis: the settled state**\nThe word Aristotle uses for a trait is hexis, a having, a settled disposition. A brave person is not someone who feels no fear; it is someone in whom the brave act has become the default response to fear. That default is built by repetition, and it goes both ways: doing the cowardly thing repeatedly builds a coward. The unsettling part of the argument is that there is no neutral. Every day you are habituating something.\n\n**The mean**\nAristotle''s second tool is aim. Every virtue sits between two failure modes: courage between cowardice and recklessness, generosity between meanness and waste, confidence between self-doubt and arrogance. This is not a call to be lukewarm. The mean is relative to the person and the situation, and it is often nearer one extreme than the other. It tells you which way you personally tend to miss, so the practice can lean against it.\n\n**What the research adds**\nLally and colleagues followed people forming a new daily habit and found automaticity rising with repetition along a curve that plateaued after a median of 66 days, with a wide spread. Missing a single day did not break the curve. Later work on habit strength points the same way: repetition in a stable context, not willpower or understanding, is what turns an act into a default. That is Aristotle''s mechanism with a number attached, and it is why the practice below earns a strong chip: it is the habit-formation procedure, aimed by the mean.\n\n**Where it meets your week**\nEvery habit on your check-in is a hexis in the making. This piece asks you to pick one that is a trait rather than a task, patience, courage, honesty, and find the daily act it is made of.',
 'The check-in builds habits. Aristotle points out that some habits are traits, and that you are always building one. Choosing which, and aiming it, is the difference between a routine and a character.',
 ARRAY['Traits are built by repeated acts, not by knowing about them; there is no neutral day.','Aim between the two failure modes of the trait, leaning against the one you tend toward.','Habit research supports the mechanism: repetition in a stable context, missed days forgiven.'],
 ARRAY['Choose one trait you want, and write the two ways it fails: too little and too much.','Find the smallest daily act that trait is made of, something you can do in under two minutes.','Attach it to a fixed moment in your day and repeat it for seven days, counting the days, not the feeling.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Aristotle; the Nicomachean Ethics is in the public domain"}, {"author": "Aristotle", "title": "Nicomachean Ethics, Book II", "year": -350}, {"author": "Lally, P. et al.", "title": "How are habits formed: Modelling habit formation in the real world (Eur. J. Soc. Psychol.)", "year": 2010}, {"author": "Durant, W.", "title": "The Story of Philosophy (source of the misattributed \"we are what we repeatedly do\")", "year": 1926}]'::jsonb,
 '[{"q": "How, according to Aristotle, does a person become brave?", "choices": ["By understanding courage", "By doing brave acts repeatedly until they become the default", "By feeling no fear"], "correct": 1, "explain": "A virtue is a hexis, a settled state formed by repetition, exactly like a skill."}, {"q": "What did the habit-formation study add to the argument?", "choices": ["Habits form in 21 days", "Automaticity rises with repetition, plateauing after a median of 66 days, and one missed day does not break it", "Willpower is the key"], "correct": 1, "explain": "The mechanism is repetition in a stable context, with a wide spread between people."}]'::jsonb,
 324, NULL, 'protocol',
 'aristotle',
 'Name one trait you wish you had. When did you last do the act that trait is made of?',
 'Seven days of the small act. Did the trait start to feel like yours, or still like a performance?',
 10),

-- ─── Campbell ───
('wisdom', 'campbell-heros-journey',
 'Campbell: The Call, the Refusal and the Road Back',
 'Joseph Campbell''s map of a thousand stories, used as a lens on the change you are in the middle of',
 'Campbell argued that myths from every culture share one shape: a call, a refusal, a threshold, an ordeal, and a return with something to give. Whether every story truly fits is contested. As a lens on your own change, the map is useful for one thing: it tells you which stage you are in, and that the stage is not the verdict.',
 'promising', 5,
 ARRAY['A way to see a hard stretch as a stage with a next step, not a permanent state','A name for the refusal, the most common place a change quietly dies','The return: a reason to finish that is about what you bring back for someone else'],
 ARRAY['The universality of the monomyth is disputed by folklorists; use it as a lens, not as a law of human nature','Narrative reframing has support in the life-story research; the hero frame specifically has not been trialled, so the chip says promising','A journey frame can inflate ordinary tasks into epics; the map is for real change, not for a Tuesday'],
 E'Joseph Campbell taught comparative mythology at Sarah Lawrence College and in 1949 published The Hero with a Thousand Faces. Its claim is that the world''s myths retell one story, which he called the monomyth: a hero leaves the ordinary world, faces trials, and returns changed with something to give. George Lucas said he wrote Star Wars from it, and screenwriting has used the map ever since.\n\n**The stages that matter**\nCampbell''s full map has seventeen steps; five do the work. The call: something asks you to change. The refusal: you decline, usually with a good reason. The threshold: you cross into unfamiliar territory and cannot easily go back. The ordeal: the hardest part, where the old self does not work any more. The return: you come back with a gift, and the gift is the point.\n\n**Read it honestly**\nFolklorists have argued for decades that the monomyth fits the stories it fits and is forced onto the rest, and that Campbell''s reading is more Jungian than anthropological. Both criticisms are fair. That is why this piece does not ask you to believe that all myths are one. It asks you to use the shape the way a coach uses a training phase: as a name for where you are.\n\n**What the research adds**\nDan McAdams'' work on narrative identity shows that people who tell the story of their hard stretches with a redemptive arc, difficulty that led somewhere, report more wellbeing and generativity than people who tell the same events as contamination stories. That is correlational and the direction is not settled. But it supports the practical move here: naming your stage in a story with a next chapter changes what you do next. The frame itself has not been trialled, so the chip says promising.\n\n**Where it meets your week**\nA program, a new sport, a return after injury, the first weeks of a membership: each has a call, a refusal that sounds like sensible reasons, a threshold and an ordeal. Most people quit at the refusal without ever naming it. The practice below names it.',
 'Most changes die at the refusal, unnamed. Campbell''s map gives the refusal a name and the ordeal a next stage, which is often all the difference between a program abandoned in week three and one finished.',
 ARRAY['Five stages: call, refusal, threshold, ordeal, return. The return is the point.','Use the map as a lens on your own change, not as a law about all stories.','People who tell hard stretches as chapters with a next one do better in the life-story research.'],
 ARRAY['Write the change you are in the middle of, and mark which of the five stages you are in today.','If it is the refusal, write the exact reason you are using, in its own words, and read it back.','Write the return as a gift: who gets something from you having finished, and what.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Joseph Campbell; not affiliated with the Joseph Campbell Foundation"}, {"author": "Campbell, J.", "title": "The Hero with a Thousand Faces", "year": 1949}, {"author": "McAdams, D. P.", "title": "The psychology of life stories (Rev. Gen. Psychol.)", "year": 2001}, {"author": "Dundes, A.", "title": "Folkloristics in the twenty-first century (J. Am. Folklore), on the limits of the monomyth", "year": 2005}]'::jsonb,
 '[{"q": "Where do most real changes die?", "choices": ["At the ordeal", "At the refusal, usually with a sensible-sounding reason", "At the return"], "correct": 1, "explain": "The refusal is the quiet exit; naming it is the practice."}, {"q": "How should the monomyth be used here?", "choices": ["As proof that all stories are one", "As a lens that names your stage in a change", "As a screenwriting template"], "correct": 1, "explain": "Its universality is contested; its use as a frame for your own change is what this piece keeps."}]'::jsonb,
 325, NULL, 'protocol',
 'campbell',
 'What call have you been refusing, and what is the exact excuse you use?',
 'You named your stage. Did seeing it as a stage, not a verdict, change what you did next?',
 10),

-- ─── Nietzsche ───
('wisdom', 'nietzsche-self-overcoming',
 'Nietzsche: Become Who You Are',
 'Three metamorphoses, one rewrite: from the musts you carry to the will you choose',
 'Nietzsche''s Zarathustra opens with a parable: the spirit becomes a camel that carries every "you must", then a lion that says "I will not", then a child that says "I will" and creates. The philosophy is a stance, not a finding. The practice, rewriting one must as a will, is a way to test whether you chose the load you carry.',
 'speculative', 5,
 ARRAY['A three-step rewrite that separates the duties you chose from the ones you inherited','A name for self-overcoming: the discipline that is hard because it is yours, not because it was assigned','Amor fati as a working stance toward a body, a history and a week you did not pick'],
 ARRAY['Nietzsche is philosophy and rhetoric, not psychology; nothing here is a finding, and the rewrite has no trial evidence, which is why the chip says speculative','His work has been misused for a century as contempt for the weak; self-overcoming is aimed at yourself, never at others','The lion stage, endless refusal, is where some readers stop; the point is the child'],
 E'Friedrich Nietzsche was a professor of classical philology at twenty-four, an invalid by his mid-thirties, and silent after a collapse in 1889. Thus Spoke Zarathustra, written in the 1880s, opens with a short parable he called the three metamorphoses. It is the cleanest summary of what he meant by becoming who you are, the phrase he took from Pindar and put on the cover of his last book.\n\n**Camel, lion, child**\nThe spirit first becomes a camel: it kneels to be loaded, and it takes pride in carrying the heaviest things. Every "you must" of a culture, a family, a scoreboard goes on its back. Then, in the desert, the camel becomes a lion. The lion fights the dragon whose every scale says "thou shalt", and wins the right to say "I will not". But the lion cannot create; it can only refuse. So the lion becomes a child: a new beginning, a game, a wheel rolling from itself, a sacred yes. The child says "I will" and makes something.\n\n**Self-overcoming**\nWhat Nietzsche admired was not strength in the gym sense but the discipline of someone who has chosen their own hardness. He was scathing about people who carried loads assigned to them and called it virtue, and equally scathing about people who stopped at refusal and called it freedom. Becoming who you are is neither: it is the child''s stage, where the will and the act are yours. Amor fati, love of one''s fate, is the stance that goes with it: not resignation, but taking the body, the history and the week you actually have as the material rather than as the excuse.\n\n**Read it honestly**\nNone of this is science, and the practice below has no evidence behind it beyond the plausibility of its mechanism, which resembles the autonomy findings in self-determination theory: goals experienced as one''s own are pursued harder and longer than goals experienced as imposed. That is why the chip says speculative. Keep the exercise; treat the philosophy as a lens, not a result. And read him with the warning his own sister ignored: everything here is aimed at yourself.\n\n**Where it meets your week**\nA streak can be a camel''s load or a child''s game. The same session, done because you must and done because you will, is a different session, and the difference shows up on the days it is hard.',
 'The same streak can be carried like a load or played like a game. Nietzsche''s three stages are a way to find out which one you are doing, and the rewrite is how you move it.',
 ARRAY['Camel carries every must; lion wins the right to refuse; child says I will and creates.','Self-overcoming is chosen hardness, aimed at yourself, never at others.','No trial evidence for the rewrite; the mechanism echoes the autonomy findings, and the chip says so.'],
 ARRAY['List the musts you carry this month: every "I have to" you can hear in your own voice.','For each, write the lion''s line, "I will not", and notice which ones you cannot honestly write.','For one remaining must, write the child''s line, "I will", in your own words, and do it that way today.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Friedrich Nietzsche; his works are in the public domain"}, {"author": "Nietzsche, F.", "title": "Thus Spoke Zarathustra, Part I, On the Three Metamorphoses", "year": 1883}, {"author": "Kaufmann, W.", "title": "Nietzsche: Philosopher, Psychologist, Antichrist", "year": 1950}, {"author": "Ryan, R. M. & Deci, E. L.", "title": "Self-determination theory and the facilitation of intrinsic motivation, social development, and well-being (Am. Psychol.)", "year": 2000}]'::jsonb,
 '[{"q": "Why is the lion not the final stage?", "choices": ["Because lions are weak", "Because refusal cannot create; the child says I will and makes something", "Because the camel was right"], "correct": 1, "explain": "The lion wins the right to refuse; the point is the child''s sacred yes."}, {"q": "How much evidence supports the rewrite practice?", "choices": ["Strong trial evidence", "None beyond a plausible mechanism, so the chip says speculative", "It is proven by neuroscience"], "correct": 1, "explain": "Philosophy, not findings. Keep the exercise, drop the certainty."}]'::jsonb,
 326, NULL, 'protocol',
 'nietzsche',
 'Which "must" in your life did you never actually choose?',
 'You rewrote one must as a will. Did the action change, or only the sentence?',
 10),

-- ─── Greene ───
('wisdom', 'greene-mastery-apprenticeship',
 'Greene: The Apprenticeship Nobody Skips',
 'Robert Greene on the long, boring, unglamorous phase that every master went through and most people quit',
 'Mastery, published in 2012, studies how people from Darwin to Temple Grandin got good. The common structure is an apprenticeship: years of deep observation, skill acquisition and experimentation before anything original. The practice is a daily deliberate block on one skill, with a feedback loop, for five days.',
 'promising', 5,
 ARRAY['A model of skill that replaces "talent" with a phase you can actually enter','Deliberate practice defined properly: at the edge, with feedback, on the weak part','Social intelligence as part of the craft, not a distraction from it'],
 ARRAY['The 10,000-hour lore that grew around this research overstates it; deliberate practice explains a real but partial share of performance differences, hence promising','Greene''s case studies are narrative reconstructions, not controlled comparisons','An apprenticeship needs a source of feedback; practising without one repeats mistakes fluently'],
 E'Robert Greene writes long books built from biographies, and Mastery is the one where the pattern he found is worth keeping. He followed Darwin, Faraday, Mozart, Temple Grandin, and a set of living practitioners through their careers, and the shape repeats: a life''s task discovered early or late, then an apprenticeship that lasts years, then a creative phase in which the rules learned are broken on purpose. The book''s value is not the biographies. It is the insistence that the apprenticeship cannot be skipped and that almost everyone tries to.\n\n**The three parts of an apprenticeship**\nGreene splits it. Deep observation: before you act, learn how the field really works, its unwritten rules and its people. Skill acquisition: practise the fundamentals past boredom, in the order that lets each skill support the next. Experimentation: begin testing your own ideas while the feedback is still cheap. The order matters. People who experiment first produce novelty without foundations; people who never leave acquisition become fluent imitators.\n\n**Deliberate practice, honestly**\nThe science underneath is Anders Ericsson''s 1993 work on expert performance: what separates the best violinists is not hours played but hours of deliberate practice, meaning effortful work at the edge of ability, on the weak part, with immediate feedback, repeated. The 10,000-hour figure that grew around it was a journalist''s simplification, and a 2014 meta-analysis found deliberate practice explains a meaningful but partial share of performance differences, largest in games and music, smaller in professions. So: the method is real, the number is folklore, and the chip says promising.\n\n**Social intelligence**\nGreene''s most practical chapter is on the people around the work. Mentors compress the apprenticeship; rivals and gatekeepers can end it. He treats reading a room as a skill of the craft, acquired the same way, by observation before action. It is not manipulation. It is the recognition that mastery happens inside a community of practice.\n\n**Where it meets your week**\nYour training program is an apprenticeship with a coach in it. This piece asks you to treat one other craft the same way: the skill that would move it most, thirty minutes at the edge, and a source of feedback that tells you what effort alone hides.',
 'A program is an apprenticeship with the boring parts made visible. Greene shows the same structure under every craft, and the practice puts one of yours on the same footing: at the edge, with feedback, daily.',
 ARRAY['Every master served an apprenticeship: observation, skill acquisition, experimentation, in that order.','Deliberate practice is at the edge, on the weak part, with feedback; the 10,000-hour number is folklore.','Mentors and the people around the work are part of the craft, not a distraction from it.'],
 ARRAY['Name the craft you are actually an apprentice in right now, and the one skill that would move it most.','Design a thirty-minute block on that skill at the edge of your ability, with a way to get feedback the same day.','Run it five days in a row and write one line after each: what the feedback showed that effort alone hid.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Robert Greene; not affiliated with the author or publisher"}, {"author": "Greene, R.", "title": "Mastery", "year": 2012}, {"author": "Ericsson, K. A., Krampe, R. T. & Tesch-Römer, C.", "title": "The role of deliberate practice in the acquisition of expert performance (Psychol. Rev.)", "year": 1993}, {"author": "Macnamara, B. N., Hambrick, D. Z. & Oswald, F. L.", "title": "Deliberate practice and performance in music, games, sports, education, and professions: a meta-analysis (Psychol. Sci.)", "year": 2014}]'::jsonb,
 '[{"q": "What defines deliberate practice?", "choices": ["Many hours of play", "Effortful work at the edge, on the weak part, with feedback", "Watching experts"], "correct": 1, "explain": "Ericsson''s definition; the hours matter only when they are this kind."}, {"q": "What does the 2014 meta-analysis show about deliberate practice?", "choices": ["It explains everything", "It explains a real but partial share of performance differences", "It explains nothing"], "correct": 1, "explain": "The method is real; the 10,000-hour number is folklore. Promising, not strong."}]'::jsonb,
 327, NULL, 'protocol',
 'greene',
 'In which craft are you still an apprentice while behaving as if you had finished one?',
 'Five days of deliberate practice with feedback. What did the feedback show that effort alone hid?',
 15),

-- ─── Goggins ───
('wisdom', 'goggins-callused-mind',
 'Goggins: Keep the Promises You Make to Yourself',
 'David Goggins'' method separated from the myth: the accountability mirror, the cookie jar, and the limits of the 40% rule',
 'Goggins'' book is a memoir of turning a broken start into ultramarathons and special-forces selections, and it contains three tools that survive without the mythology: a written promise on the mirror, a jar of proof from past hard things, and a habit of doing the thing on the day you least want to. The 40% rule is a heuristic, not a finding, and the piece says so.',
 'promising', 5,
 ARRAY['A daily promise, written and specific, which is the smallest unit of self-trust','The cookie jar: past proof you can reach for at the moment of quitting','A relationship with discomfort that is chosen and bounded, not endless'],
 ARRAY['The 40% rule has no physiological measurement behind it; the psychobiological model of endurance supports the direction, not the number','Goggins trained through injuries that ended in surgeries; his tolerance is not a target and rest is part of the method, whatever the memoir implies','Self-contempt as fuel works short term and corrodes; the promise is kept out of respect, not punishment'],
 E'David Goggins grew up poor and abused, weighed close to 300 pounds in his twenties, and became a Navy SEAL, an ultramarathon runner and a pull-up world-record holder. Can''t Hurt Me, from 2018, is his account of it. It is also a manual, and the manual has a problem: the parts that made him famous, the 40% rule and the callused mind, are heuristics dressed as facts. The tools underneath them are worth keeping, and they are simpler than the myth.\n\n**The accountability mirror**\nAs a young man he wrote his goals on sticky notes on the bathroom mirror and read them every morning: specific, small, dated. Lose the weight. Study for the test. The mechanism is mundane and strong. A promise you can see, that names an action rather than an outcome, is the smallest unit of self-trust, and self-trust is what a streak is built from. Every kept promise makes the next one more likely to be believed.\n\n**The cookie jar**\nWhen he wanted to quit in a race, he reached for a mental jar of proof: past hard things he had already done. Not affirmations. Evidence. The moment of quitting is a moment of forgetting, and the jar is a way of remembering on purpose. It works because the proof is true.\n\n**The 40% rule, honestly**\nGoggins claims that when your mind tells you that you are done, you are at about forty percent of capacity. There is no measurement behind the number. What there is, is Marcora''s psychobiological model of endurance: the point at which people stop is set by perceived effort and motivation, not by the muscle''s actual limit, and both can be moved. So the direction is right, there is more in the tank than the mind reports, and the number is a story. Keep the direction, drop the number. The chip says promising for that reason.\n\n**The part he under-writes**\nGoggins ran through stress fractures and needed multiple surgeries. His tolerance for damage is not a target; it is a warning label. The practice below is bounded: one promise, one hard thing, one day at a time, and rest treated as part of the method rather than as weakness.\n\n**Where it meets your week**\nThe check-in is a promise kept in public to yourself. This piece makes it explicit: written, small, dated, and kept on the day you least want to.',
 'A streak is a stack of kept promises. Goggins'' tools make each one explicit and give you something true to reach for at the moment you want to skip it.',
 ARRAY['A promise to yourself is the smallest unit of self-trust: written, specific, dated.','The cookie jar is evidence, not affirmation; reach for it at the moment of quitting.','More is in the tank than the mind reports; the 40% number is a story, and rest is part of the method.'],
 ARRAY['Write one promise for tomorrow on paper where you will see it in the morning: an action, not an outcome, with a time.','Write three hard things you have already done, in one line each, and keep the list where the promise is.','Tomorrow, keep the promise on the day''s terms, feel like it or not, and note afterwards what the next decision felt like.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of David Goggins; not affiliated with the author or publisher"}, {"author": "Goggins, D.", "title": "Can''t Hurt Me: Master Your Mind and Defy the Odds", "year": 2018}, {"author": "Marcora, S. M. & Staiano, W.", "title": "The limit to exercise tolerance in humans: mind over muscle? (Eur. J. Appl. Physiol.)", "year": 2010}, {"author": "Baumeister, R. F. & Tierney, J.", "title": "Willpower: Rediscovering the Greatest Human Strength", "year": 2011}]'::jsonb,
 '[{"q": "What is the cookie jar?", "choices": ["A reward for finishing", "A list of true past proof to reach for at the moment of quitting", "A motivational quote"], "correct": 1, "explain": "Evidence, not affirmation. It works because it is true."}, {"q": "What does the science say about the 40% rule?", "choices": ["It is measured and exact", "The direction is supported by the psychobiological model; the number is a story", "It is completely false"], "correct": 1, "explain": "Perceived effort sets the stopping point and can be moved; no study produced the number."}]'::jsonb,
 328, NULL, 'protocol',
 'goggins',
 'What is the last promise you made to yourself and broke, and what did you tell yourself afterwards?',
 'You kept one small promise on a day you did not feel like it. What did keeping it change in the next decision?',
 10),

-- ─── Thich Nhat Hanh ───
('wisdom', 'thich-nhat-hanh-one-thing',
 'Thich Nhat Hanh: Wash the Dishes to Wash the Dishes',
 'The Vietnamese monk who taught mindfulness as a way of doing ordinary things, not a way of escaping them',
 'The Miracle of Mindfulness was written as a letter to a friend running a relief programme during the war. Its instruction is simple: when you wash the dishes, wash the dishes. Do the thing you are doing, with the breath as the anchor. The practice is one ordinary task done as the only thing in the world.',
 'strong', 4,
 ARRAY['A form of mindfulness that needs no cushion, no app and no extra time: it is done inside tasks you already do','The breath as a portable anchor you can return to in a queue, a set or an argument','Evidence that this kind of attention training lowers stress and improves mood, from dozens of trials'],
 ARRAY['Mindfulness programmes have solid trial evidence for stress and mood; the effects are moderate, not miraculous, and they need practice to hold','A small minority of people experience unwanted effects from intensive practice; the everyday form here is gentle, and stopping is always allowed','Interbeing and the wider Buddhist frame are a worldview; the practice earns its chip without it'],
 E'Thich Nhat Hanh was a Zen monk from Vietnam who opposed the war from inside it, was exiled for it, and spent the rest of his life teaching in the West what he called engaged Buddhism. The Miracle of Mindfulness began in 1974 as a long letter to a colleague running a school of social workers in the war zone, and it is still the clearest short manual on the subject.\n\n**Doing the thing you are doing**\nThe central image is washing dishes. There are two ways to do it: to get them done so you can have your tea, or to wash them. In the first, you are not present for the dishes and, he argues, you will not be present for the tea either, because the habit of being elsewhere follows you. Mindfulness, in his usage, is simply being where you are, doing what you are doing, and the everyday tasks are where it is trained, not the cushion.\n\n**The breath as anchor**\nEvery time attention wanders, and it will, the breath is where you come back to. Not a special breath: the one already happening. He recommends counting or a short phrase paired with the in-breath and out-breath, and a bell, any bell, as a reminder to stop and take three breaths. The point is not to breathe better. It is to have a place to return to that is always with you.\n\n**What the research adds**\nMindfulness training has been studied more than any other contemplative practice. A 2014 review in JAMA Internal Medicine found moderate evidence that mindfulness programmes improve anxiety, depression and pain, and low-to-moderate evidence for stress and quality of life. Later meta-analyses on healthy adults point the same way for stress. The programmes studied are usually structured eight-week courses; the everyday form here is gentler and the effects should be expected to be smaller. The mechanism, though, is the same trained attention, and the practice has enough behind it for a strong chip.\n\n**The half-smile and the warning**\nHe recommended a half-smile during practice, which sounds precious and works: it is difficult to hold a small smile and stay tense. He also knew that people can be flooded by what they find when they stop moving. If that happens, stop; the practice is meant to be kind.\n\n**Where it meets your week**\nA set of squats, a walk to the station, the dishes after dinner. Each is already in your day. One of them, done as the only thing, is the whole practice.',
 'Meditation on the check-in is a box. This piece is the version that lives inside tasks you already do, so the box gets ticked by the way you wash a plate or walk to the gym.',
 ARRAY['Do the thing you are doing; the habit of being elsewhere follows you everywhere.','The breath is the anchor because it is always with you; a bell is a reminder to return to it.','Mindfulness programmes have moderate trial evidence for stress and mood; the everyday form is gentle and portable.'],
 ARRAY['Choose one task you do today anyway and rush through: the dishes, a walk, brushing your teeth.','Do it as the only thing in the world: hands, sounds, temperature, the breath underneath, and return to the breath each time you drift.','Set a bell, any timer, for one moment in the day, and take three slow breaths when it rings.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Thich Nhat Hanh; not affiliated with Plum Village or his publishers"}, {"author": "Thich Nhat Hanh", "title": "The Miracle of Mindfulness", "year": 1975}, {"author": "Goyal, M. et al.", "title": "Meditation programs for psychological stress and well-being: a systematic review and meta-analysis (JAMA Intern. Med.)", "year": 2014}, {"author": "Britton, W. B. et al.", "title": "Defining and measuring meditation-related adverse effects in mindfulness-based programs (Clin. Psychol. Sci.)", "year": 2021}]'::jsonb,
 '[{"q": "Where, in this teaching, is mindfulness trained?", "choices": ["Only on the cushion", "Inside ordinary tasks, by doing the thing you are doing", "In retreats"], "correct": 1, "explain": "The dishes are the practice; the cushion is optional."}, {"q": "What does the trial evidence show for mindfulness programmes?", "choices": ["Cures for most conditions", "Moderate improvements in anxiety, depression, pain and stress", "No measurable effect"], "correct": 1, "explain": "Moderate, repeated, real. The everyday form should be expected to do a little less."}]'::jsonb,
 329, NULL, 'protocol',
 'thich-nhat-hanh',
 'Which daily task do you rush through as if it were an obstacle to your actual life?',
 'You did one task fully. What did you notice in it that you had never noticed before?',
 5),

-- ─── Kabat-Zinn ───
('wisdom', 'kabat-zinn-full-catastrophe',
 'Kabat-Zinn: Mindfulness as Medicine',
 'The molecular biologist who put meditation in a hospital, measured it, and gave the world an eight-week course',
 'In 1979 Jon Kabat-Zinn opened a stress-reduction clinic in a Massachusetts hospital basement for patients medicine had run out of options for. The programme he built, MBSR, is the most-studied mindfulness course in existence. Its core is the body scan: attention moved slowly through the body without trying to change anything.',
 'strong', 5,
 ARRAY['The body scan: a ten-minute practice that restores contact with a body most of us only notice when it hurts','Stress reactivity versus stress response: a distinction you can feel once you have the practice','The best-evidenced form of mindfulness there is, stripped of any religious frame'],
 ARRAY['MBSR shows moderate effects on stress, anxiety and depression in meta-analyses; it is not a cure and not a replacement for treatment','Lying-down practice invites sleep; that is fine, and it is also not the exercise','A minority report unwanted effects with intensive practice; this piece uses the short form and permission to stop'],
 E'Jon Kabat-Zinn had a PhD in molecular biology from MIT and a long personal practice of Zen and yoga when, in 1979, he persuaded the University of Massachusetts Medical Center to let him run a course for patients with chronic pain and stress-related illness. He called it the Stress Reduction and Relaxation Program, later Mindfulness-Based Stress Reduction, and he did two unusual things: he removed every trace of religion, and he measured the results. Full Catastrophe Living, from 1990, is the course in book form. The title is from Zorba the Greek, who is asked whether he has ever been married and answers that he has a wife, a house, children, the full catastrophe.\n\n**The body scan**\nMBSR''s first practice is the body scan. Lying down, you move attention slowly from the toes to the top of the head, region by region, noticing whatever is there, warmth, pressure, nothing, an ache, without trying to relax it or change it. The instruction that makes it different from relaxation exercises is the last one: you are not trying to make anything happen. You are practising being in contact with the body as it is. Most people discover regions they had stopped feeling.\n\n**Reactivity and response**\nKabat-Zinn''s model of stress distinguishes the automatic reaction, in which a stressor triggers the full cascade before you have noticed it, from a response, in which awareness enters between the trigger and the cascade and gives you a choice. The body scan trains the noticing. The rest of the course applies it to breathing, walking, eating and, eventually, to the difficult conversation and the diagnosis.\n\n**What the research adds**\nMBSR has been tested in hundreds of trials. A 2015 meta-analysis in healthy adults found moderate effects on stress and smaller ones on anxiety, depression and quality of life. Reviews in clinical populations find similar moderate benefits for anxiety and depression. Effects are real, repeatable and not large; they hold better with continued practice. The programme is eight weeks with 45 minutes a day of homework; the ten-minute scan below is the entry to it, not the whole course, and it still earns a strong chip because the technique and the evidence are the same.\n\n**Where it meets your week**\nRPE, soreness, how you slept: the check-in asks you to read the body every day. The scan is how you train the instrument you are reading with.',
 'The check-in asks you to read your body every day. The body scan trains the reading, and it is the single best-evidenced mindfulness practice available.',
 ARRAY['The body scan: attention moved through the body without trying to change anything.','Awareness between the trigger and the cascade turns a stress reaction into a response.','MBSR has moderate, repeatable effects on stress and mood across hundreds of trials.'],
 ARRAY['Lie down where you will not be interrupted for ten minutes and set a timer.','Move attention from the toes upward, region by region, naming what is there without adjusting it; when you drift, return to the last region.','Finish by feeling the whole body at once for three breaths, then note which region had gone quiet before you visited it.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Jon Kabat-Zinn; not affiliated with the author or the Center for Mindfulness"}, {"author": "Kabat-Zinn, J.", "title": "Full Catastrophe Living: Using the Wisdom of Your Body and Mind to Face Stress, Pain, and Illness", "year": 1990}, {"author": "Khoury, B. et al.", "title": "Mindfulness-based stress reduction for healthy individuals: A meta-analysis (J. Psychosom. Res.)", "year": 2015}, {"author": "Goldberg, S. B. et al.", "title": "Mindfulness-based interventions for psychiatric disorders: A systematic review and meta-analysis (Clin. Psychol. Rev.)", "year": 2018}]'::jsonb,
 '[{"q": "What separates the body scan from a relaxation exercise?", "choices": ["It is longer", "You are not trying to make anything happen, only to be in contact with what is there", "It uses music"], "correct": 1, "explain": "Contact, not control. Regions you had stopped feeling come back."}, {"q": "What size of effect does MBSR show in meta-analyses?", "choices": ["Large and curative", "Moderate on stress, smaller on anxiety and depression", "None"], "correct": 1, "explain": "Real, repeatable, moderate. Held better with continued practice."}]'::jsonb,
 330, NULL, 'protocol',
 'kabat-zinn',
 'Where does stress show up in your body first, before you have called it stress?',
 'Ten minutes of scanning. Which part of the body that you had stopped feeling came back?',
 10),

-- ─── Attia ───
('wisdom', 'attia-centenarian-decathlon',
 'Attia: Train for the Last Decade',
 'Peter Attia''s reframe of exercise: choose what you want to be able to do at ninety, then back-calculate the training',
 'Outlive argues that healthspan, the years you can still do what you care about, is the target, and that most people train for the next race instead of the last decade. The Centenarian Decathlon is the tool: ten physical tasks you want at ninety, mapped to the capacities that make them possible, trained now.',
 'strong', 5,
 ARRAY['A reason to train that survives the day motivation does not: a specific future you can picture','The four capacities that predict a good last decade: aerobic base, peak aerobic capacity, strength, stability','Some of the strongest mortality data in medicine, translated into what to do on Tuesday'],
 ARRAY['Fitness and strength predict mortality strongly in cohorts; trials cannot run for decades, so the causal claim is inferred, well supported and still inferred','Attia''s clinical protocols go far beyond exercise into testing and medication; this piece keeps only the training frame','Training for ninety at thirty can be used to postpone living; the decathlon is a reason to train, not a reason to wait'],
 E'Peter Attia is a physician who left surgery and a stretch at McKinsey to practise what he calls Medicine 3.0: prevention aimed decades ahead. Outlive, from 2023, is the argument and the manual. Its central move for training is a question: what do you want to be able to do in your last decade? Lift a grandchild. Carry groceries up stairs. Get off the floor without hands. Walk a trail. Most people have never asked, so they train for the next event and arrive at eighty unable to do the things they would have chosen.\n\n**The Centenarian Decathlon**\nThe tool is a list. Write ten physical tasks you want to be able to do at ninety, specifically. Then back-calculate. Capacity declines with age at a known rate; to do a task at ninety you need a large margin now, so each task maps to a capacity to build well beyond the task itself. Carrying two bags of groceries up three flights at ninety needs the grip, the legs and the aerobic base of someone who can farmer-carry far more than that at forty.\n\n**Four capacities**\nAttia trains four things and ranks them by evidence. Aerobic efficiency, zone 2, the base that everything else sits on. Peak aerobic capacity, VO2max, the single strongest fitness predictor of mortality in the cohort data. Strength, especially grip, carrying and the legs, which predicts mortality nearly as well. And stability: the ability to load the body safely, which is what lets you keep training the other three into old age instead of getting hurt out of them.\n\n**What the research adds**\nA 2018 study of over 120,000 people found that cardiorespiratory fitness was inversely associated with mortality across the whole range, with no upper limit to the benefit and the least fit at risk comparable to smoking. Meta-analyses of muscular strength find the same direction: stronger people die later, across ages and causes. These are cohorts, not trials; nobody can randomise forty years of training. The consistency, size and dose-response make the inference as strong as observational medicine gets, and the practice earns a strong chip.\n\n**Where it meets your week**\nYour program trains for the next block. This piece asks what it is missing for the last decade, and adds one session for the capacity it ignores.',
 'The program trains for the next block. Attia asks what you want your body to do in its last decade, and the answer usually reveals one capacity your training is quietly ignoring.',
 ARRAY['Train for the last decade: ten specific tasks at ninety, back-calculated to capacities now.','Four capacities: aerobic base, VO2max, strength, stability. VO2max and strength predict mortality strongly.','Cohort evidence, not trials, and as strong as observational medicine gets.'],
 ARRAY['Write ten physical things you want to be able to do at ninety, specific enough to picture.','Beside each, write the capacity it needs most: aerobic base, peak aerobic, strength or stability.','Find the capacity your current week trains least and add one session for it, starting this week.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Peter Attia; not affiliated with the author or Early Medical"}, {"author": "Attia, P. with Gifford, B.", "title": "Outlive: The Science and Art of Longevity", "year": 2023}, {"author": "Mandsager, K. et al.", "title": "Association of cardiorespiratory fitness with long-term mortality among adults undergoing exercise treadmill testing (JAMA Netw. Open)", "year": 2018}, {"author": "García-Hermoso, A. et al.", "title": "Muscular strength as a predictor of all-cause mortality in an apparently healthy population: a systematic review and meta-analysis (Arch. Phys. Med. Rehabil.)", "year": 2018}]'::jsonb,
 '[{"q": "What is the Centenarian Decathlon?", "choices": ["A race for old people", "Ten physical tasks you want at ninety, back-calculated to the capacities to train now", "A supplement stack"], "correct": 1, "explain": "A reason to train that is specific enough to picture and to plan from."}, {"q": "What kind of evidence links fitness and strength to mortality?", "choices": ["Randomised trials", "Large cohorts with consistent dose-response, as strong as observational medicine gets", "Anecdotes"], "correct": 1, "explain": "Nobody can randomise forty years of training; the inference is well supported and still an inference."}]'::jsonb,
 331, NULL, 'protocol',
 'attia',
 'What do you want to be able to do at ninety that you are not training for at all?',
 'You added one session for the capacity you ignored. Did it feel like training or like insurance, and which one keeps you doing it?',
 15),

-- ─── Jung, second piece ───
('wisdom', 'jung-persona-mask',
 'Jung: The Persona and the Price of the Mask',
 'The face you show the world is necessary. Mistaking it for yourself is the mistake Jung spent a career describing',
 'Jung called the persona the mask a person wears to meet the world: a role, a rank, a reputation. It is useful, and it becomes a problem when the mask is mistaken for the face. Individuation, his word for becoming whole, begins with telling the two apart. The practice is a plain inventory of where the mask is doing the living.',
 'promising', 5,
 ARRAY['A clear line between the useful role and the identification that costs you','The midlife pattern Jung described, which shows up in anyone who has climbed a ladder','Individuation as an ordinary practice: small acts done as yourself rather than as the role'],
 ARRAY['Jungian theory is not experimental psychology; the persona is a model, and the practice earns its promising chip from the self-concept and self-discrepancy literature, not from Jung','Dropping a role too fast is its own drama; the practice is an inventory, not a resignation letter','The persona is necessary; the aim is a mask you can take off, not no mask'],
 E'Carl Jung split from Freud in 1913 and spent the next half-century mapping the parts of the psyche that are not the ego. The shadow is the famous one. The persona is the quieter one, and for people who are good at what they do it is often the more important. The word is the Latin for an actor''s mask, and Jung meant it neutrally: the persona is the face you build to meet the world, shaped by what your work, your family and your culture reward.\n\n**Necessary, and not you**\nJung was clear that the persona is not a lie. You need one. A surgeon needs a surgeon''s face; a coach needs a coach''s. The trouble starts when the person and the persona fuse, when someone is their rank, their record, their reputation, and has nothing left when those are threatened. He called it identification with the persona, and he thought it was the characteristic illness of successful people at midlife: the ladder climbed, the mask perfected, and a hollowness behind it that no further success touches.\n\n**Individuation**\nHis word for the way out was individuation: becoming the whole of what you are, which includes the shadow and excludes nothing. It is not self-improvement. It is closer to self-inclusion, and it begins with the plain act of noticing where the mask is doing the living. Which decisions are made because the role requires them? Which feelings are not allowed because the role would not have them? Which people only ever meet the mask?\n\n**What the research adds**\nJung''s theory is not experimental, and this piece does not pretend otherwise. What has been studied is the gap between the self as presented and the self as felt: self-discrepancy work since Higgins in 1987 links large gaps between the ought self and the actual self to anxiety and low mood, and the authenticity literature links acting in line with one''s own values to wellbeing. Those findings support the direction of the practice, not Jung''s architecture. The chip says promising for that reason.\n\n**Where it meets your week**\nA tier, a division, a badge case: the app hands you a persona if you want one. The Watts and Tolle lessons ask you to hold it lightly. This one asks the prior question: where, this week, did the mask decide?',
 'Ranks and tiers are a persona the app can hand you. Jung''s question is the one under Tolle''s and Watts'': not whether to hold the role lightly, but where it has already started deciding for you.',
 ARRAY['The persona is the necessary face you meet the world with; the illness is mistaking it for yourself.','Identification with the role is the midlife pattern of successful people: the ladder climbed, the hollowness behind it.','Individuation starts with an inventory of where the mask is doing the living; the self-discrepancy research supports the direction.'],
 ARRAY['List three decisions you made this week and, beside each, write who made it: you, or the role.','Write one feeling the role does not allow you, and where it went instead.','Do one small thing today as yourself rather than as the role, and tell nobody.'],
 '[{"author": "Note", "title": "Original lesson on the ideas of Carl Jung; not affiliated with the Jung estate or any Jungian institute"}, {"author": "Jung, C. G.", "title": "Two Essays on Analytical Psychology (Collected Works 7), on the persona", "year": 1928}, {"author": "Higgins, E. T.", "title": "Self-discrepancy: A theory relating self and affect (Psychol. Rev.)", "year": 1987}, {"author": "Kernis, M. H. & Goldman, B. M.", "title": "A multicomponent conceptualization of authenticity: Theory and research (Adv. Exp. Soc. Psychol.)", "year": 2006}]'::jsonb,
 '[{"q": "What is the persona, in Jung''s sense?", "choices": ["A lie you tell", "The necessary face you build to meet the world, which becomes a problem when mistaken for yourself", "The shadow"], "correct": 1, "explain": "Neutral and needed; the illness is identification with it."}, {"q": "What research supports the direction of the practice?", "choices": ["Jung''s case studies", "Self-discrepancy and authenticity findings on the gap between the presented and felt self", "Brain scans of the persona"], "correct": 1, "explain": "Jung''s architecture is a model; the gap between ought and actual self has been measured."}]'::jsonb,
 332, NULL, 'protocol',
 'jung',
 'Which decision this week did the role make for you, and would you have made it as yourself?',
 'You did one thing as yourself, not as the role, and told nobody. What was different about doing it unwitnessed?',
 10),

-- ─── The map ───
('wisdom', 'how-to-walk-a-path',
 'How to Walk a Path',
 'The Vault''s loop and its map: six paths, twenty teachers, one rule for turning an idea into a week',
 'Every piece in this library now runs the same loop: understand the idea, answer one question privately, run one bounded practice, answer one question afterwards. Paths string pieces into a change. This piece is the manual: how the loop works, what the map is for, and why the answers stay yours.',
 'strong', 3,
 ARRAY['The loop, explained once: understand, reflect, practise, integrate','The six paths and which dimension of a life each one works on','The privacy rule: reflections are yours and are never shown to anyone'],
 ARRAY['A path is a suggested order, not a course you owe anyone; skipping is allowed','Running several paths at once is the fastest way to run none; one at a time','The loop rewards practice, not reading; a piece read and not practised is a piece not yet used'],
 E'The old Vault was a library: shelves of pieces, each graded by evidence, each ending in a quiz and a button that said complete. Reading was the whole loop. That is fine for a protocol, sleep timing, protein dosing, where knowing the number is most of the work. It is not enough for an idea. An idea from Frankl or Epictetus is not used by being understood; it is used by being run on a Tuesday and looked at afterwards.\n\n**The loop**\nEvery piece with a question at the end of it now runs four stages. Understand: read the idea, take the quiz if you want the check. Reflect: one question, answered in your own words, before you do anything. Practise: one bounded exercise with a time on it, most under fifteen minutes, some meant to run over days. Integrate: one question afterwards, about what actually happened. The practice is what earns progress and XP; the reading on its own earns nothing, on purpose. Fifteen XP for the first practice of each day, and no more, so the loop can add to the ladder without becoming a way to farm it.\n\n**The map**\nTwenty teachers and thinkers sit behind the pieces, each with a lens: what they let you see. Tap a name to see their ideas. Six paths string pieces into a change, one for each dimension of a life this app cares about: the body and its long game, the mind and its presence, discipline, character, purpose, mastery. A path is a suggested order. The next piece is always the first one you have not practised.\n\n**Today**\nHome and the Vault both open with one practice for today, chosen from what your week looks like: fewer check-ins than usual points at systems, a heavy training week with short sleep points at the long game, a strong meditation week points deeper into presence, a long streak points at meaning. It is a pointer, not a diagnosis. The whole map is always one tap away.\n\n**Your answers are yours**\nReflections are stored so you can read them back. They are never shown on the feed, the boards, a profile or to another member, and the coach never quotes them. Achievements for practices run are public like every other badge; the words are not.\n\n**One rule**\nOne piece, one practice, one path at a time. A path finished is a week changed, not a list completed.',
 'A library is used by reading. A map is used by walking. This piece is the difference, and the rule that keeps the Vault a place you use rather than a place you visit.',
 ARRAY['Understand, reflect, practise, integrate: practice earns progress, reading alone does not.','Six paths, one per dimension; the next piece is the first one you have not practised.','Reflections are private and stay that way; only practices run become achievements.'],
 ARRAY['Open the path that Today points you at and read its first piece.','Answer the reflection before the practice, in your own words, without editing.','Run the practice today, and answer the integration question only after you have.'],
 '[{"author": "Note", "title": "The Vault''s own manual for the practice loop and the map; no external source"}, {"author": "Lally, P. et al.", "title": "How are habits formed: Modelling habit formation in the real world (Eur. J. Soc. Psychol.)", "year": 2010}, {"author": "Gollwitzer, P. M. & Sheeran, P.", "title": "Implementation intentions and goal achievement: A meta-analysis of effects and processes (Adv. Exp. Soc. Psychol.)", "year": 2006}]'::jsonb,
 '[{"q": "What earns progress in the Vault?", "choices": ["Reading a piece", "Running its practice", "Opening the app"], "correct": 1, "explain": "Understanding is the first stage; the practice is the one that counts."}, {"q": "Who can see your reflections?", "choices": ["Your squad", "Only you", "The coach quotes them in chat"], "correct": 1, "explain": "Private rows, never surfaced; only practices run become badges."}]'::jsonb,
 319, NULL, 'foundations',
 NULL,
 'Which of the six dimensions, body, mind, discipline, character, purpose, mastery, has had the least of your attention this year?',
 'You walked the first piece of a path. What did the loop ask of you that the old reading did not?',
 5)
ON CONFLICT (slug) DO NOTHING;
