-- ============================================================
-- Inner Work — 10-lesson course: identity, energy, manifestation.
-- Honest-premium framing: full spiritual topics, truthfully tiered
-- (what is evidenced vs speculative) so they belong in a
-- "verified results" brand.
-- Idempotent: ON CONFLICT (slug) DO NOTHING. Re-runnable.
-- ============================================================

INSERT INTO public.vault_articles
  (category_id, slug, title, subtitle, summary, evidence_tier, read_time_min,
   benefits, body_md, why_it_matters, key_takeaways, try_today,
   references_json, quiz, display_order, lesson_number, course_role)
VALUES

-- ─── Lesson 1 · Foundations ───
('inner-work', 'inner-operating-system',
 'The Inner Operating System',
 'Why the strongest habits still leak without identity, attention and state',
 'Discipline trains your hardware. This course trains your software: the self-image you act from, the attention you aim, and the state you operate in. Here is the map.',
 'promising', 5,
 ARRAY['Explains why willpower alone plateaus','Gives you the 3-layer model the whole course builds on','Sets honest expectations: evidence vs speculation'],
 E'You can force a habit for 30 days on willpower. You cannot force it for 10 years. What carries behaviour over years is not effort — it is the **inner operating system** underneath it.\n\nThis course works on three layers:\n\n**1. Identity — the self-image you act from**\nPeople behave in ways that feel consistent with who they believe they are. A person who *sees themselves* as an athlete does not negotiate with the alarm clock the way a person "trying to work out" does. Lessons 8 and 2 work here.\n\n**2. Attention — what your mind is primed to notice**\nYou do not experience the world; you experience what you attend to. Two people walk the same street — one primed for opportunities sees them, one primed for threats sees those. Attention is trainable. Lessons 2, 3, 4 and 6 work here.\n\n**3. State — the energy you operate in**\nThe same task is easy in a resourceful state and impossible in a depleted one. Your physiology (breath, posture, movement, light) is the fastest lever on state — much faster than trying to think your way into feeling different. Lessons 5, 7 and 9 work here.\n\n**Our honesty contract**\nThis category takes so-called "soft" topics seriously — manifestation, energy, self-image — and tells you the truth about each: what controlled research supports, what is promising, and what is speculative. Every lesson carries an evidence chip. Nothing here requires you to believe anything mystical; everything here works through attention, identity and physiology — mechanisms you already own.\n\nTrain the body. Run the protocols. But upgrade the operating system they run on — that is what makes the results permanent.',
 'Every habit, workout and check-in in this app runs on top of your self-image, your attention and your state. If those leak, effort leaks. This lesson gives you the map the next nine lessons fill in.',
 ARRAY['Behaviour that lasts is identity-consistent, not willpower-forced.','You act on what you attend to — and attention is trainable.','State beats motivation: change physiology first, feelings follow.'],
 ARRAY['Write one sentence: "The person I am becoming is …" — you will refine it in Lesson 8.','Notice today which of the 3 layers (identity, attention, state) leaks most for you.'],
 '[{"author":"Kross, E.","title":"Chatter: The Voice in Our Head, Why It Matters, and How to Harness It","year":2021},{"author":"Markus, H. & Nurius, P.","title":"Possible Selves","year":1986}]'::jsonb,
 '[{"q":"What carries behaviour over years, according to this model?","choices":["Maximum daily willpower","An identity the behaviour is consistent with","Stricter tracking"],"correct":1,"explain":"Willpower is a short-term override. Long-term consistency comes from acting like the person you believe you are."},{"q":"Which is the FASTEST lever on your operating state?","choices":["Thinking positive thoughts","Physiology — breath, posture, movement","Waiting for motivation"],"correct":1,"explain":"Body changes state faster than mind. A 2-minute physiological intervention outruns an hour of trying to think yourself into a mood."}]'::jsonb,
 100, 1, 'foundations'),

-- ─── Lesson 2 · Foundations ───
('inner-work', 'manifestation-demystified',
 'Manifestation, Demystified',
 'The three real mechanisms — and the one claim the evidence does not support',
 'Manifestation works for many people — but not the way the books say. Here are the three mechanisms that are real, the one that is not, and how to practice it so it actually moves your life.',
 'speculative', 6,
 ARRAY['Keeps the useful core of manifestation','Removes the passive, wish-and-wait failure mode','Turns vision into primed attention and same-day action'],
 E'Millions of people swear manifestation changed their lives. Dismissing all of them as deluded is lazy — and swallowing the "law of attraction" whole is worse. The honest position: **something real is happening, and it is not magic.**\n\n**Mechanism 1 — Primed attention**\nWhen you define a desire vividly and revisit it daily, you prime your attention system to notice relevant openings you would otherwise filter out. This is why, after deciding to buy a certain car, you suddenly see it everywhere. The car did not multiply — your filter changed. People who write down what they want spot the aligned conversation, job post or person, because the target is loaded in attention.\n\n**Mechanism 2 — Identity-consistent behaviour**\nRepeatedly visualising yourself as a certain person shifts your self-concept — and you start making the hundred micro-choices that person makes. The "vibration" people report is usually this: they carry themselves differently, speak differently, and others respond to it. Psychologists studied this as *possible selves*: a vivid future self changes present behaviour.\n\n**Mechanism 3 — Action bias**\nPeople who believe good outcomes are coming take more shots: they apply, ask, show up, start. More attempts, more hits. Research on self-described "lucky" people found they simply create and notice more chance opportunities — openness and action, not fortune.\n\n**What the evidence does NOT support**\nThere is no controlled evidence that thoughts alone alter external events — that the universe rearranges outcomes to match a frequency. That is the speculative part, and this lesson wears its *speculative* chip on purpose.\n\n**The trap to avoid**\nHere the research gets sharp: studies by Gabriele Oettingen show that *positive fantasy alone* — enjoying the dream as if already achieved — measurably REDUCES the energy and action people put toward the goal. Passive manifestation is not neutral; it can be counterproductive.\n\n**The honest protocol**\n1. Write the desire in present-tense detail — this loads the attention filter.\n2. Revisit it 2 minutes every morning — priming decays; renew it.\n3. Same day, take one action a person with that outcome would take — this is where the "law" actually operates.\n\nManifestation, practiced honestly, is a daily attention-and-identity ritual with an action trigger. That version works — and you do not have to believe anything unprovable to use it.',
 'Manifestation is one of the most-searched self-development ideas on Earth — and most people practice the version that research suggests backfires (dream, feel good, wait). Extract the three real mechanisms and it becomes a legitimate daily tool.',
 ARRAY['Real: primed attention, identity-consistent behaviour, action bias.','Not evidenced: thoughts alone changing external events.','Positive fantasy WITHOUT action measurably reduces drive (Oettingen) — always pair vision with a same-day act.'],
 ARRAY['Write your one clearest desire in present-tense detail (2 minutes).','Do one thing today that the version of you who already has it would do.','Notice one "coincidence" today and ask: did my filter just catch it because it is primed?'],
 '[{"author":"Oettingen, G.","title":"Rethinking Positive Thinking: Inside the New Science of Motivation","year":2014},{"author":"Kappes, H. & Oettingen, G.","title":"Positive fantasies about idealized futures sap energy","year":2011},{"author":"Wiseman, R.","title":"The Luck Factor","year":2003},{"author":"Markus, H. & Nurius, P.","title":"Possible Selves","year":1986}]'::jsonb,
 '[{"q":"Which of these is a REAL, evidence-plausible mechanism behind manifestation?","choices":["Thoughts emitting a frequency the universe answers","Primed attention noticing aligned opportunities","Wanting something hard enough"],"correct":1,"explain":"Defining a target vividly changes what your attention system flags — the filter changes, not the world."},{"q":"What did Oettingen''s research find about positive fantasy alone?","choices":["It doubles achievement","It has no effect","It measurably reduces energy and action toward the goal"],"correct":2,"explain":"Enjoying the dream as if achieved relaxes the system — the drive to close the gap drops. Vision must be paired with action."},{"q":"Why does this lesson carry a SPECULATIVE chip?","choices":["Because attention priming is unproven","Because the thoughts-change-external-events claim lacks controlled evidence","Because visualisation is pseudoscience"],"correct":1,"explain":"The mechanisms are real psychology; the metaphysical causality claim is the unevidenced part — and we say so honestly."}]'::jsonb,
 101, 2, 'foundations'),

-- ─── Lesson 3 · Protocol ───
('inner-work', 'woop-mental-contrasting',
 'WOOP: Wishes That Survive Contact With Reality',
 'The evidence-based cousin of manifestation — Wish, Outcome, Obstacle, Plan',
 'Twenty years of research distilled into a 5-minute mental protocol that roughly doubles follow-through: dream it, feel it, then deliberately collide it with the obstacle and pre-load your response.',
 'strong', 5,
 ARRAY['Backed by meta-analyses across health, study and fitness goals','Takes 5 minutes, needs nothing but a quiet moment','Converts vague wishes into automatic if-then responses'],
 E'Lesson 2 ended with a warning: fantasy without friction backfires. This lesson is the fix — and it is one of the best-evidenced motivation tools in psychology.\n\n**WOOP** = Wish, Outcome, Obstacle, Plan. Developed by Gabriele Oettingen (as *mental contrasting with implementation intentions*), tested in dozens of controlled studies: more exercise, better eating, better grades, faster recovery habits. Implementation intentions alone carry a meta-analysis of 94 studies with a medium-to-large effect on goal attainment.\n\n**The protocol (5 minutes):**\n\n**W — Wish.** Name one meaningful wish for the next weeks. Challenging but feasible. *"Train 4× per week."*\n\n**O — Outcome.** Imagine the best result vividly for 60 seconds. How it feels, what changes. Indulge fully — this is the manifestation muscle, used deliberately.\n\n**O — Obstacle.** Now the turn most people never make: find the obstacle *inside you*. Not "my schedule" — but "when 18:00 comes I feel drained and open my phone." Feel that scene honestly. This collision — dream against inner obstacle — is *mental contrasting*, and it is what converts a pleasant fantasy into mobilised energy.\n\n**P — Plan.** Pre-load the response as an if-then: *"IF it is 18:00 and I feel drained and reach for my phone, THEN I put on my training shoes and walk out the door."* If-then plans work because they hand the behaviour to the situation cue — the decision is already made when the moment hits.\n\n**Why the order matters**\nObstacle before dream kills belief; dream before obstacle without the collision is Lesson 2''s trap. Wish → Outcome → Obstacle → Plan uses the dream to energise and the obstacle to aim.\n\nRun one WOOP per goal, re-run when the obstacle changes. This is the bridge between your inner work and your daily check-in: the plan you pre-load tonight is the habit you lock tomorrow.',
 'This is the strongest-evidenced protocol in the entire category — the tool that makes every vision from Lessons 2 and 4 executable. Five minutes of WOOP routinely outperforms hours of raw motivation.',
 ARRAY['WOOP = Wish, Outcome, Obstacle, Plan — in that exact order.','The obstacle must be internal (the feeling/thought that derails you), not external.','If-then plans automate the response: the situation triggers the behaviour, not willpower.'],
 ARRAY['Run one full WOOP (5 min) on your most important current goal.','Write your if-then plan where you will see it tomorrow.','Tonight, WOOP tomorrow''s hardest habit before sleep.'],
 '[{"author":"Oettingen, G.","title":"Rethinking Positive Thinking: Inside the New Science of Motivation","year":2014},{"author":"Gollwitzer, P. & Sheeran, P.","title":"Implementation intentions and goal achievement: a meta-analysis of effects and processes","year":2006},{"author":"Duckworth, A. et al.","title":"Self-regulation strategies improve self-discipline in adolescents (MCII)","year":2013}]'::jsonb,
 '[{"q":"What makes WOOP different from pure visualisation?","choices":["It skips imagining the outcome","It collides the dream with your inner obstacle, then pre-loads a plan","It uses affirmations"],"correct":1,"explain":"Mental contrasting — dream against obstacle — converts fantasy into directed energy; the if-then plan makes the response automatic."},{"q":"A well-formed WOOP obstacle is…","choices":["My boss and my schedule","The drained feeling at 18:00 that sends me to my phone","Bad weather"],"correct":1,"explain":"The operative obstacle is internal — the specific feeling, thought or impulse that actually derails you. That is what you can plan against."},{"q":"Why do if-then plans work?","choices":["They increase motivation","They delegate the decision to the situation cue in advance","They are written down"],"correct":1,"explain":"Gollwitzer''s research: pre-deciding IF-situation THEN-action removes the in-the-moment negotiation where goals usually die."}]'::jsonb,
 102, 3, 'protocol'),

-- ─── Lesson 4 · Protocol ───
('inner-work', 'visualization-that-works',
 'Visualization That Actually Works',
 'Process over outcome, all senses, obstacles included — the PETTLEP method',
 'Elite sport has used structured imagery for decades. The catch: visualising the PROCESS improves performance, while only visualising the outcome can backfire. Here is the working protocol.',
 'promising', 5,
 ARRAY['Borrowed from sports psychology, works for any hard task','Strengthens skill and confidence without extra physical load','5 minutes, best used right before training or a hard block'],
 E'Visualization has a solid body of sport-psychology research behind it — motor imagery activates overlapping neural machinery with physical execution, and structured imagery programs reliably improve performance in athletes. But HOW you visualise decides whether it helps.\n\n**The critical study**\nStudents were split into groups before an exam: one visualised *getting the A* (outcome), one visualised *the process* — sitting down, studying, working through material. The process group studied more and scored better. The outcome-only group performed *worse* than controls. Same trap as Lesson 2: consuming the reward in imagination relaxes the drive to earn it.\n\n**Rule 1: Visualise the doing, not the podium.**\n\n**The PETTLEP checklist** (from applied sport psychology) makes imagery vivid enough to matter:\n- **P**hysical — imagine in the body: feel the grip, the breath, the cold air. First person, through your own eyes.\n- **E**nvironment — your actual gym, your actual desk, your actual kitchen.\n- **T**ask — the specific movements and decisions, step by step.\n- **T**iming — real time, not fast-forward.\n- **L**earning — update the image as your skill grows.\n- **E**motion — include the nerves, the effort, the satisfaction of execution.\n- **P**erspective — first person as default.\n\n**Rule 2: Include the obstacle.** The most useful rep is imagining the moment it gets hard — rep 8 burning, the urge to check your phone, the craving at 21:00 — and *seeing yourself execute anyway*. This is mental contrasting fused with imagery, and it is what separates preparation from daydreaming.\n\n**The protocol (3–5 minutes, before the hard thing):**\n1. Close your eyes, 3 slow breaths.\n2. Run the task first-person with PETTLEP vividness.\n3. Insert the hardest moment; watch yourself handle it.\n4. End at completion — the last rep done, the block finished. Then go do it.\n\nVisualization is rehearsal, not wish-granting. Rehearse the performance, and the performance improves.',
 'Visualization done wrong (outcome-only) measurably hurts follow-through; done right (process + obstacles) it is one of the cheapest performance enhancers available. The difference is one rule.',
 ARRAY['Process visualisation improves performance; outcome-only can reduce it.','PETTLEP vividness (body, environment, real time, emotion) is what makes imagery effective.','Always rehearse the hardest moment and your response to it.'],
 ARRAY['Before today''s training or hardest task: 3 minutes of first-person process imagery.','Include one obstacle moment and watch yourself execute through it.'],
 '[{"author":"Pham, L. & Taylor, S.","title":"From thought to action: Effects of process- versus outcome-based mental simulations on performance","year":1999},{"author":"Holmes, P. & Collins, D.","title":"The PETTLEP approach to motor imagery","year":2001},{"author":"Cumming, J. & Williams, S.","title":"The role of imagery in performance (Oxford Handbook of Sport Psychology)","year":2012}]'::jsonb,
 '[{"q":"Which visualisation style improved exam results in the classic study?","choices":["Visualising receiving the top grade","Visualising the process of studying","Visualising celebrating afterwards"],"correct":1,"explain":"Process simulation increased actual studying; outcome-only visualisation let students consume the reward in imagination and perform worse."},{"q":"What does the second T in PETTLEP stand for, and why does it matter?","choices":["Talent — imagine being naturally gifted","Timing — image in real time, not fast-forward","Tension — stay stressed"],"correct":1,"explain":"Real-time imagery keeps the mental rehearsal faithful to actual execution, which is what makes it transfer."},{"q":"The most valuable single image to rehearse is…","choices":["The finish line","The hardest moment, with you executing anyway","Your competition failing"],"correct":1,"explain":"Pre-living the obstacle plus your response is rehearsal for the exact moment goals are usually lost."}]'::jsonb,
 103, 4, 'protocol'),

-- ─── Lesson 5 · Protocol ───
('inner-work', 'elevate-your-energy',
 'Elevating Your Energy: State Management',
 'Your "vibe" is physiology plus mood plus meaning — and all three are trainable',
 'When people say "raise your energy" or "raise your vibration", something real sits underneath: operating state. Here is what it is made of and the fastest honest levers to lift it.',
 'promising', 6,
 ARRAY['Fast state-shift tools measured in minutes, not weeks','An energy audit that finds your hidden drains','A repeatable peak-state ritual for hard blocks'],
 E'"High-vibe" is not a frequency your body emits. But everyone knows the difference between a day you are switched on and a day you are running at 40%. That difference — **operating state** — is real, measurable in arousal, mood and focus, and far more controllable than most people think.\n\n**Honest translation:** energy = physiological arousal × mood × sense of meaning. Raise any factor and the others tend to follow.\n\n**Lever 1 — Breath (fastest, ~1–2 minutes)**\nThe *physiological sigh* — double inhale through the nose, long exhale through the mouth — is the quickest validated down-shifter for stress; five minutes of it daily improved mood and lowered anxiety in a controlled Stanford trial. To shift UP: 20–30 fast full breaths, then one long exhale. Calm on demand, activation on demand.\n\n**Lever 2 — Posture and movement (2–5 minutes)**\nSlumped posture measurably feeds low-energy, negative thinking; upright posture supports energy and confidence. Better still: move. Two minutes of fast stairs, squats or a walk outside beats a coffee for subjective energy. Emotion follows motion.\n\n**Lever 3 — Light and environment**\nMorning outdoor light anchors your circadian rhythm — the single biggest background variable in daily energy. Your spaces are state triggers too: the cluttered desk, the phone on the table — each is a small, constant drain.\n\n**Lever 4 — Music and ritual**\nMusic reliably shifts arousal and mood within minutes — that is why every locker room uses it. Build a 3-song activation playlist that means one thing: we are switching on.\n\n**The energy audit (do once, review weekly)**\nDraw two columns. **Chargers:** people, places, activities after which your energy is UP. **Drains:** after which it is down — doomscrolling, certain conversations, skipped meals, 23:30 bedtimes. Schedule one more charger and delete one drain this week. Nothing mystical: ruthless accounting.\n\n**The peak-state ritual (before anything hard)**\n1. 90 seconds of breath (up- or down-shift as needed)\n2. Posture: stand tall, shoulders back, 30 seconds\n3. One activation track\n4. One sentence of meaning: *why this block matters* — then begin.\n\nYou cannot always choose your circumstances. You can almost always choose your state going into them.',
 'State is the multiplier on everything else in this app — the same workout, the same work block, the same conversation lands completely differently at 40% vs 90%. These levers move state in minutes.',
 ARRAY['"Energy" honestly = arousal × mood × meaning — all three trainable.','Breath is the fastest lever: physiological sigh down, cyclic fast breathing up.','Audit chargers vs drains weekly; schedule the former, delete the latter.'],
 ARRAY['Do 5 physiological sighs right now and rate your state before/after.','Write your energy audit: 3 chargers, 3 drains — cut one drain this week.','Build a 3-song activation playlist for training blocks.'],
 '[{"author":"Balban, M. et al. (Huberman & Spiegel labs)","title":"Brief structured respiration practices enhance mood and reduce physiological arousal","year":2023},{"author":"Peper, E. & Lin, I-M.","title":"Increase or decrease depression: How body postures influence your energy level","year":2012},{"author":"Thayer, R.","title":"The Biopsychology of Mood and Arousal","year":1989}]'::jsonb,
 '[{"q":"The honest translation of \"raising your energy\" is…","choices":["Emitting a higher frequency","Shifting arousal, mood and meaning — your operating state","Drinking more caffeine"],"correct":1,"explain":"The felt experience is real; the mechanism is physiology and psychology, not a broadcast frequency — and that makes it directly trainable."},{"q":"What is the physiological sigh?","choices":["A long inhale held for 30 seconds","Double nasal inhale, long mouth exhale","Breathing into a bag"],"correct":1,"explain":"Two stacked inhales reinflate collapsed alveoli, the long exhale slows the heart via the vagal brake — the fastest validated calm-down."},{"q":"The energy audit asks you to…","choices":["Rank your friends","List chargers and drains, then schedule/delete accordingly","Track calories"],"correct":1,"explain":"State management is largely accounting: consciously add what charges you, remove what drains you."}]'::jsonb,
 104, 5, 'protocol'),

-- ─── Lesson 6 · Protocol ───
('inner-work', 'gratitude-savoring',
 'Gratitude & Savoring',
 'The 5-minute practices that reliably raise baseline mood — no journal aesthetic required',
 'Gratitude is one of the most replicated interventions in positive psychology, and savoring is its underrated sibling. Together they retrain your attention filter toward what is working.',
 'promising', 4,
 ARRAY['Reliably improves mood and life satisfaction in controlled trials','Counteracts the brain''s negativity bias at the attention level','Takes under 5 minutes, compounds with your evening check-in'],
 E'Your attention system has a built-in negativity bias — threats and problems are flagged first, wins are filtered out. Useful for survival, terrible for baseline mood. Gratitude practice is not positive thinking; it is **manually correcting the filter**.\n\n**The evidence, briefly**\nIn Emmons and McCullough''s controlled studies, people who wrote weekly gratitude lists reported better mood, fewer physical complaints and even more exercise than those listing hassles. Seligman''s "three good things" — write three things that went well tonight and *why* — produced happiness gains still measurable six months later. Effects are moderate, replicated, and cheap.\n\n**Protocol 1 — Three good things (evening, 3 minutes)**\nTonight, write three things that went well. The rule that makes it work: **be specific and name the why**. Not "training" but "I showed up for the 4×4 session even though 18:00-me wanted to skip — because the plan was pre-loaded." Specificity forces your attention to re-scan the day for wins — that re-scan IS the training.\n\n**Protocol 2 — Savoring (in the moment, 30 seconds)**\nGratitude looks back; savoring happens live. A few times a day, when something is good — first sip of coffee, post-training buzz, evening light — stop for 30 seconds and *let it register fully*. Name it: "this is a good moment." Research on savoring links it to higher life satisfaction; mechanically, you are teaching your attention that good moments are worth flagging.\n\n**Protocol 3 — Gratitude aimed at people (weekly)**\nThe largest single effects in the literature come from *expressed* gratitude: tell one person, concretely, what they did and what it meant. One message per week.\n\n**Why this sits in Inner Work**\nLesson 2 taught that a primed filter finds what it seeks. Gratitude is that same priming aimed at what is already working — the most evidence-backed "abundance practice" there is.',
 'Baseline mood is trainable, and the training is embarrassingly simple: repeatedly point your attention at what worked. The evening habit doubles as fuel for your check-in streak.',
 ARRAY['Gratitude corrects the negativity bias at the filter level — it is attention training.','Specific + why beats generic lists; expressed gratitude beats private lists.','Savoring is live gratitude: 30 seconds of letting a good moment register.'],
 ARRAY['Tonight: three good things, each with the why.','Savor one moment today for a full 30 seconds.','Send one concrete thank-you message this week.'],
 '[{"author":"Emmons, R. & McCullough, M.","title":"Counting blessings versus burdens: gratitude and subjective well-being in daily life","year":2003},{"author":"Seligman, M. et al.","title":"Positive psychology progress: empirical validation of interventions","year":2005},{"author":"Bryant, F. & Veroff, J.","title":"Savoring: A New Model of Positive Experience","year":2007}]'::jsonb,
 '[{"q":"What is gratitude practice actually training?","choices":["Politeness","Your attention filter — re-scanning for what worked","Memory capacity"],"correct":1,"explain":"The nightly re-scan for wins counteracts the negativity bias; over weeks the filter itself shifts."},{"q":"What makes a \"three good things\" entry effective?","choices":["Writing it in a nice notebook","Being specific and naming why it went well","Listing at least ten items"],"correct":1,"explain":"Specificity plus causal reflection is what the validated protocol requires — it forces genuine attentional re-scanning."},{"q":"Which gratitude form shows the largest effects in research?","choices":["Private mental gratitude","Expressed gratitude aimed at a real person","Gratitude quotes on social media"],"correct":1,"explain":"Expressed, concrete gratitude (letters, direct messages) produces the biggest and longest-lasting boosts — for both parties."}]'::jsonb,
 105, 6, 'protocol'),

-- ─── Lesson 7 · Protocol ───
('inner-work', 'distanced-self-talk',
 'Inner Dialogue: Coaching Yourself From a Distance',
 'Turn the inner critic into an inner coach with one linguistic trick',
 'The voice in your head runs commentary all day. Research by Ethan Kross shows a startlingly simple upgrade: talk to yourself by name, from the outside — and regulation improves measurably.',
 'promising', 5,
 ARRAY['One-word technique with lab-measured effects on stress and performance','Converts rumination loops into coach-like problem solving','Pairs naturally with pre-training and pre-conversation nerves'],
 E'You already talk to yourself constantly — the only question is whether that voice is a critic, a catastrophiser, or a coach.\n\n**The chatter problem**\nUnder stress, inner speech collapses into first-person loops: *"Why did I do that? What if I fail? I always do this."* Kross calls this *chatter* — and it measurably degrades problem solving, sleep and performance.\n\n**The fix: psychological distance via language**\nIn Kross''s experiments, people preparing for a stressful task who coached themselves in the **second or third person** — *"Okay [your name], you have done harder things than this. Here is how you take the first step"* — showed calmer physiological profiles, less rumination afterwards, and better-rated performance than those using "I". The mechanism: your name/"you" activates the same perspective you use when advising a friend — and everyone is wiser about their friends'' problems than their own.\n\n**Protocol 1 — Named coaching (in the stress moment)**\nWhen you notice spiralling: address yourself by name, and ask *"what would you tell a friend in exactly this spot?"* Then say it — to yourself, by name.\n\n**Protocol 2 — Temporal distancing**\nAsk: *"How will I feel about this in a week? In a year?"* Zooming the timeline out reliably shrinks the emotional charge of the present problem.\n\n**Protocol 3 — The critic audit (once)**\nWrite down the three sentences your inner critic repeats most. Read them aloud. Would you say them to someone you are coaching? Rewrite each as the coach version — same standard, zero contempt. *"You are behind, as always"* becomes *"You are behind on this one — what is the first 10-minute move?"* Keep the rewritten three visible.\n\n**The standard stays high**\nThis is not self-soothing or lowering the bar. Great coaches are demanding AND on your side. That combination — high standards, high support — is exactly what distanced self-talk makes available to you, from you.',
 'The tone of your inner dialogue is the tone of your entire day — and it leaks into training, willpower and sleep. Distanced self-talk is the cheapest measured upgrade to that tone.',
 ARRAY['First-person chatter degrades regulation; distance restores it.','Coach yourself by name / as "you" — the friend-advice perspective.','High standards + high support: rewrite the critic, keep the bar.'],
 ARRAY['Next stress spike: coach yourself by name for 30 seconds before acting.','Write your critic''s top 3 lines and rewrite them as coach lines.','Before training: one named instruction — "[Name], first set, nothing else."'],
 '[{"author":"Kross, E. et al.","title":"Self-talk as a regulatory mechanism: how you do it matters","year":2014},{"author":"Kross, E.","title":"Chatter: The Voice in Our Head, Why It Matters, and How to Harness It","year":2021},{"author":"Orvell, A. et al.","title":"Does distanced self-talk facilitate emotion regulation across a range of emotionally intense experiences?","year":2021}]'::jsonb,
 '[{"q":"What did Kross''s lab find about third-person self-talk under stress?","choices":["It feels silly and does nothing","It improves regulation, rumination and rated performance","It only works for extroverts"],"correct":1,"explain":"The linguistic shift creates psychological distance — the same wise perspective you use for friends — with measurable downstream effects."},{"q":"The coach voice differs from the critic voice by…","choices":["Lowering the standard","Keeping the standard but removing contempt","Ignoring mistakes"],"correct":1,"explain":"High standards with high support. The rewrite keeps accountability and adds a first actionable step."},{"q":"Temporal distancing means asking…","choices":["Why does this always happen to me?","How will this look in a week or a year?","Who is to blame?"],"correct":1,"explain":"Zooming out the timeline reliably shrinks the present problem''s emotional charge and restores perspective."}]'::jsonb,
 106, 7, 'protocol'),

-- ─── Lesson 8 · Protocol ───
('inner-work', 'authentic-self-image',
 'Authentic Self-Image: Who Are You Becoming?',
 'Identity is not found — it is built, one vote at a time',
 'The deepest lever in behaviour change is the sentence after "I am". This lesson turns your self-image from an inherited accident into a deliberate, honest construction — anchored to your values and cast daily.',
 'promising', 6,
 ARRAY['Connects your habits to the person they are building','A values exercise that filters goals you never actually chose','Directly upgrades the "I am" statement your coach uses daily'],
 E'Every lesson so far points here. Attention, state, self-talk — they all run on top of one thing: **who you believe you are**.\n\n**Self-image is evidence-based (in both senses)**\nPsychology''s *self-perception theory* (Bem): we infer who we are largely by watching what we do. Each action is a data point — a **vote** — for some identity. Skip training: a vote for "someone who skips". Show up tired: a vote for "someone who shows up". Your self-image is the running tally. This is why the check-in streak in this app is more than points: it is a stack of identity evidence.\n\n**Possible selves**\nMarkus and Nurius showed that a vivid *possible self* — a concrete image of who you could become — actively organises present behaviour. Vague "I want to be better" does nothing; a specific "the version of me who trains 4× and speaks calmly under pressure" gives today''s choices a direction to vote for.\n\n**Authentic does not mean fixed**\n"Finding your authentic self" often hides an assumption: that there is a finished self buried somewhere, waiting. The healthier, better-supported frame: authenticity means your actions align with your **chosen values** — not with a fixed essence, and not with an audience. You are allowed to build the self; what makes it authentic is that YOU chose the blueprint.\n\n**The values filter (10 minutes, do once)**\n1. List the 5 things you claim to value most (health, family, craft, freedom, courage…).\n2. Now audit last week: where did your hours, money and energy actually go?\n3. The gaps are the work. And check each goal you are chasing: is it yours, or inherited from parents, feeds, or comparison? Cut one goal that fails the test — pursuing borrowed goals is the deepest energy drain there is.\n\n**Write the "I am" (the artifact of this lesson)**\nOne or two sentences, present tense, values-anchored, honest enough that acting on it is possible today:\n*"I am an athlete who keeps promises to himself. Calm under pressure, first to move."*\nAvoid fantasy inflation — the statement must be one your daily votes can actually support. Identity claims that outrun evidence collapse into noise; claims that grow WITH evidence become unshakeable.\n\n**Close the loop in the app**\nYour coach already asks for this: open **Settings → Athlete Profile → "Your why — who are you becoming?"** and rewrite it with what you built here. It anchors your daily check-in and your coach''s guidance from tomorrow morning.',
 'Identity is the deepest lever: it decides what feels "like you" before willpower even gets a vote. Making your self-image deliberate — and anchoring it in the app — turns every habit into evidence.',
 ARRAY['You infer who you are from what you do — every action is a vote.','A vivid, specific possible self organises today''s behaviour; vague wishes do not.','Authentic = aligned with chosen values, not a fixed buried essence.'],
 ARRAY['Run the values filter: 5 claimed values vs where last week actually went.','Cut one inherited goal that is not truly yours.','Rewrite your "I am" statement in Settings → Athlete Profile — make it votable today.'],
 '[{"author":"Bem, D.","title":"Self-Perception Theory","year":1972},{"author":"Markus, H. & Nurius, P.","title":"Possible Selves","year":1986},{"author":"Sheldon, K. & Lyubomirsky, S.","title":"How to increase and sustain positive emotion: the best possible selves exercise","year":2006}]'::jsonb,
 '[{"q":"According to self-perception theory, self-image is primarily built from…","choices":["Childhood only","Observing your own actions — each one a vote","What others say about you"],"correct":1,"explain":"Bem: we infer who we are from what we repeatedly do. The tally of votes IS the self-image — which makes it changeable."},{"q":"What makes a self-image \"authentic\" in this lesson''s frame?","choices":["It matches a fixed inner essence you discovered","Your actions align with values you consciously chose","Other people approve of it"],"correct":1,"explain":"Authenticity as chosen-values alignment lets you BUILD the self deliberately without faking anything."},{"q":"Why should the \"I am\" statement avoid fantasy inflation?","choices":["Modesty is polite","Identity claims must be supportable by today''s votes or they collapse","Short sentences are easier to remember"],"correct":1,"explain":"An identity that grows with evidence becomes solid; one that outruns evidence reads as noise even to yourself."}]'::jsonb,
 107, 8, 'protocol'),

-- ─── Lesson 9 · Protocol ───
('inner-work', 'letting-go',
 'Letting Go: Acceptance & Defusion',
 'Control the controllable, release the grip on the rest — as a trained skill, not a platitude',
 'The spiritual traditions call it surrender; clinical psychology calls it acceptance and defusion, and has two decades of trials behind it. Fighting your thoughts amplifies them — here is what works instead.',
 'promising', 5,
 ARRAY['Backed by the ACT research literature','Stops the suppression rebound that fuels cravings and rumination','An evening ritual that closes the day instead of carrying it'],
 E'Some of the most useful spiritual advice ever given — *let go, surrender the outcome* — sounds like giving up. Done right, it is the opposite: it frees the energy you were spending on an unwinnable fight and returns it to the part you control.\n\n**Why fighting thoughts fails**\nWegner''s classic experiments: told NOT to think of a white bear, people think of it more — and the rebound persists after they stop trying. Suppression is a tracking task that keeps the target active. The same mechanism inflates cravings, pre-performance nerves and 02:00 rumination. If you have ever tried to force yourself calm, you have felt it.\n\n**Acceptance is not approval**\nIn Acceptance and Commitment Therapy (ACT) — supported by hundreds of trials across anxiety, pain and performance — acceptance means *making room for* the feeling without obeying or fighting it. Pain studies show it plainly: acceptance instructions outperform suppression on tolerance. The feeling is allowed to exist; it just does not get the steering wheel.\n\n**Protocol 1 — Defusion (10 seconds, any time)**\nChange *"I can''t do this"* to *"I am having the thought that I can''t do this."*\nSay it slowly. You just moved from being INSIDE the thought to LOOKING AT it. Thoughts are events in the mind, not orders. This one linguistic move is defusion, and it works on cravings, doubts and catastrophes alike.\n\n**Protocol 2 — The control sort (2 minutes, when gripped)**\nTwo columns. **Mine:** effort, preparation, response, the next action. **Not mine:** outcomes, other people''s opinions, timing, the past. Everything in column two gets one deliberate exhale and the sentence: *"Not mine to carry. Mine is the next action."* Then take it. (The Stoics ran their entire operating system on this sort; ACT rebuilt it with data.)\n\n**Protocol 3 — The evening release (3 minutes, after your check-in)**\n1. Name the one thing still gripping you.\n2. Sort it: what part is yours? Write tomorrow''s single action for it.\n3. Physiological sigh ×3 (Lesson 5), and the line: *"Day closed. Handled what was mine."*\nCarrying the day into bed is a sleep tax; the release ritual pays it before the pillow.\n\n**Where this meets manifestation**\nLesson 2''s honest protocol ends "act, then release the outcome." Now you have the release half: full effort on the action, open hands on the result. That combination — maximum agency, minimum grip — is what the traditions were pointing at all along.',
 'The grip itself — on thoughts, outcomes, and how things "should" be — is a measurable performance and sleep tax. Acceptance and defusion are the trained skills that release it without lowering your standards.',
 ARRAY['Suppressing thoughts rebounds (white bear effect) — fighting feeds the fire.','Defusion: "I am having the thought that…" turns orders into observable events.','Sort control ruthlessly: full effort on yours, one exhale on the rest.'],
 ARRAY['Catch one sticky thought today and run the defusion phrasing on it.','Do the 2-column control sort on whatever is gripping you right now.','Tonight after check-in: the 3-minute evening release.'],
 '[{"author":"Hayes, S. et al.","title":"Acceptance and Commitment Therapy: model, processes and outcomes","year":2006},{"author":"Wegner, D.","title":"Ironic processes of mental control","year":1994},{"author":"Masedo, A. & Esteve, M.","title":"Effects of suppression, acceptance and spontaneous coping on pain tolerance and intensity","year":2007}]'::jsonb,
 '[{"q":"What does thought suppression do, per Wegner''s research?","choices":["Removes the thought permanently","Increases the thought''s frequency, with a rebound afterwards","Nothing measurable"],"correct":1,"explain":"Monitoring for the forbidden thought keeps it active — suppression is the fuel, not the extinguisher."},{"q":"Defusion changes \"I can''t do this\" into…","choices":["I definitely can do this!","I am having the thought that I can''t do this","I will never think this again"],"correct":1,"explain":"The reframe creates distance: the thought becomes an observable mental event instead of a command. No forced positivity required."},{"q":"Letting go, done right, means…","choices":["Lowering effort and standards","Full effort on what is yours, released grip on outcomes","Avoiding hard situations"],"correct":1,"explain":"Maximum agency on the controllable, open hands on the rest — surrender as strategy, not resignation."}]'::jsonb,
 108, 9, 'protocol'),

-- ─── Lesson 10 · Recap ───
('inner-work', 'inner-work-recap',
 'Recap: Your Inner Protocol',
 'Assemble the nine lessons into one daily and weekly operating rhythm',
 'The tools only compound when they run on a schedule. This recap assembles attention, identity, state and release into a 15-minute daily rhythm and a 20-minute weekly review.',
 'promising', 4,
 ARRAY['One page that operationalises the whole category','A daily rhythm that costs ~15 minutes total','A weekly identity review that keeps the votes honest'],
 E'Nine lessons, four themes: **prime attention, build identity, manage state, release the rest.** Here they become a schedule.\n\n**THE DAILY RHYTHM (~15 minutes total)**\n\n**Morning — prime (5 min)**\n- Read your "I am" statement (Lesson 8) — the day''s first identity vote is remembering what you are voting for.\n- 2 minutes of vision on your primary desire (Lesson 2''s honest protocol) and name today''s same-day action.\n- If today holds a known battle: 60-second WOOP if-then (Lesson 3).\n\n**Before the hard block — state + rehearsal (5 min)**\n- Peak-state ritual: breath, posture, one track, one line of meaning (Lesson 5).\n- 3 minutes of process visualisation including the hardest moment (Lesson 4).\n- One named coach instruction: "[Name], first set. Nothing else." (Lesson 7)\n\n**During the day — micro-skills (0 min extra)**\n- Savor one good moment for 30 seconds (Lesson 6).\n- Defuse one sticky thought: "I am having the thought that…" (Lesson 9).\n\n**Evening — bank and release (5 min)**\n- Check in and lock the day — the identity vote made visible.\n- Three good things, with the why (Lesson 6).\n- Evening release: sort what is yours, one action for tomorrow, three sighs, day closed (Lesson 9).\n\n**THE WEEKLY REVIEW (20 min, same day each week)**\n1. **Votes:** what did this week''s actions vote for? Does the tally match the "I am"?\n2. **Values audit:** hours and energy vs claimed values (Lesson 8) — one gap to close.\n3. **Energy audit:** chargers up, drains down; delete one drain (Lesson 5).\n4. **WOOP** the coming week''s biggest wish, obstacle included (Lesson 3).\n5. **Express** one gratitude to a real person (Lesson 6).\n\n**The honest core, one last time**\nNothing in this category asked you to believe anything unprovable. Primed attention finds openings. Identity votes compound. State is physiology, and physiology is trainable. Effort belongs to you; outcomes only partly. Practice the rhythm for four weeks — the person running the protocol IS the protocol.',
 'Tools that are not scheduled do not compound. Fifteen deliberate minutes a day plus one weekly review converts nine lessons of theory into a running inner operating system.',
 ARRAY['Four themes: prime attention, build identity, manage state, release the rest.','The daily rhythm costs ~15 minutes: morning prime, pre-block state, evening bank + release.','The weekly review keeps identity votes, values and energy honestly audited.'],
 ARRAY['Schedule the morning prime and evening release as calendar blocks for the next 7 days.','Pick your weekly review slot (same day, 20 min) and set it recurring.','Run the full daily rhythm tomorrow and rate your day 1–10 against a normal day.'],
 '[{"author":"Wood, W. & Neal, D.","title":"A new look at habits and the habit-goal interface","year":2007},{"author":"Oettingen, G.","title":"Rethinking Positive Thinking","year":2014},{"author":"Kross, E.","title":"Chatter","year":2021}]'::jsonb,
 '[{"q":"The four themes of the Inner Work protocol are…","choices":["Diet, cardio, lifting, sleep","Prime attention, build identity, manage state, release the rest","Wish, wait, receive, repeat"],"correct":1,"explain":"Every lesson maps to one of these four — together they form the daily and weekly rhythm."},{"q":"Why does the evening end with BOTH gratitude and release?","choices":["Tradition","Gratitude retrains the filter on wins; release drops the residue so it doesn''t tax sleep","To make journaling longer"],"correct":1,"explain":"They are complementary: bank what worked (attention training), put down what grips (acceptance) — then sleep clean."},{"q":"What makes the tools in this category actually compound?","choices":["Believing in them strongly","Running them on a schedule until the rhythm is automatic","Reading the lessons repeatedly"],"correct":1,"explain":"Scheduled practice — 15 min daily, 20 min weekly — is what turns techniques into an operating system."}]'::jsonb,
 109, 10, 'recap')

ON CONFLICT (slug) DO NOTHING;
