-- Vault · Wisdom (part 2, prose): the foundations piece rewritten as the shelf's manual,
-- the recap rewritten for the whole shelf, the Jung shadow piece cut to shadow and projection,
-- Huberman and Attia differentiated from the shelves that own their doses, and the sentences
-- the 2026-09-16 audit flagged. Machine shape: UPDATE … SET col = $v$…$v$ WHERE slug = '…';

-- The manual absorbs the second foundations piece (zero members had opened it).
DELETE FROM public.vault_articles WHERE slug IN ('how-to-walk-a-path');

UPDATE public.vault_articles SET title = $v$How to Use This Shelf$v$, subtitle = $v$The reading method, the loop every piece runs, and the map of thinkers and paths$v$, summary = $v$Every piece on this shelf is an idea you run, not a summary you read. Each comes from a named thinker with a question before it, a short practice, and a question after it. This piece is the method for all of them: how to read a teacher, what the chip means here, and why your answers stay yours.$v$, evidence_tier = $v$strong$v$, benefits = ARRAY[$v$A reading method that keeps the useful part of any teacher and drops the rest$v$, $v$One loop for every piece: a question in, a practice, a question out$v$, $v$A map of twenty-one thinkers and six paths, so one idea leads to the next$v$], risks = ARRAY[$v$Reading about practices is not practising them; a piece read and not run is a piece not yet used$v$, $v$Some sources make claims about physics or healing that the evidence does not support; the chip says so where it happens$v$], body_md = $v$**Ideas are tools, not beliefs**
A tool has a job. A hammer is not true or false; it is useful or not for the nail in front of you. Read every thinker on this shelf the same way. James Clear gives you a way to design a cue. Epictetus gives you a way to sort a worry into what is yours and what is not. Jung gives you a way to read your own irritation. You do not need to believe anything to use any of them. You need to try them on a real Tuesday.

**Three sentences to finish for every thinker**
1. The one idea: what does this teacher say that nobody else on the shelf says?
2. The practice: what would I do, today, for five minutes, if I took it seriously?
3. The claim I am not buying: what does the source assert that goes beyond what it can show?
If you can finish all three, you have read the book better than most people who finished it.

**What the evidence chip means here**
On the other shelves the chip rates studies. Here the sources are often philosophers and practitioners, so the chip rates the practice, not the worldview. Strong means the practice has repeated human trials behind it: morning light, a habit cue, slow exhale breathing. Promising means the mechanism is plausible and early or indirect studies agree: presence practice, identity-based habits, the control sort, mental rehearsal. Speculative means the practice may be valuable and the explanation offered for it is not supported: quantum healing, the universe answering, anchoring sold as a science. Speculative is not an insult. It lets you keep the exercise and drop the story.

**The loop**
Every piece runs four stages. Understand: read the idea, take the check if you want it. Reflect: one question, answered in your own words, before you do anything. Practise: one bounded exercise with a time on it, most under fifteen minutes, some meant to run over days. Integrate: one question afterwards, about what happened. The practice earns the progress and the XP; reading alone earns nothing, on purpose. Fifteen XP for the first practice of each day, and no more, so the loop can add to the ladder without becoming a way to farm it.

**The map**
Twenty-one thinkers sit behind the pieces, each with a lens: what they let you see. Tap a name in the Vault for their ideas and for what kind of claim they make, philosophy, psychological theory, science or practice. Six paths string pieces into a change, one for each dimension of a life this app cares about: the body and its long game, the mind and its presence, discipline, character, purpose, mastery. A path is a suggested order. The next step is always the first piece you have not practised.

**Your answers are yours**
Reflections are stored so you can read them back. They are never shown on the feed, the boards, a profile or to another member, and the coach never quotes them. Achievements for practices run are public like every other badge; the words are not.

**How to use the shelf**
One piece a day is plenty. Run the practice before you open the next one. The last piece folds the whole shelf into one week you can run without believing any of it.$v$, why_it_matters = $v$Your check-ins, streaks and sessions are practices. This shelf adds the ones that shaped how millions think about habits, presence and meaning, with the discipline to say which parts are practice and which parts are story.$v$, key_takeaways = ARRAY[$v$Read a thinker for the practice you can run this week, not the worldview you must adopt.$v$, $v$The chip rates the practice, not the philosophy; speculative means keep the exercise, drop the explanation.$v$, $v$Understand, reflect, practise, integrate: the practice is what counts, and your answers stay private.$v$], try_today = ARRAY[$v$Pick the one thinker on this shelf you already know best and write their three sentences: the idea, the practice, the claim you are not buying.$v$, $v$Open the path Today points you at and run its first practice before you read anything else.$v$, $v$Decide the time of day your five minutes will live this week, and put it in the calendar.$v$], references_json = $v$[{"author": "Note", "title": "The Vault's own manual for reading, the loop and the map; no external source"}, {"author": "Lally, P. et al.", "title": "How are habits formed: Modelling habit formation in the real world (Eur. J. Soc. Psychol.)", "year": 2010}, {"author": "Gollwitzer, P. M. & Sheeran, P.", "title": "Implementation intentions and goal achievement: A meta-analysis of effects and processes (Adv. Exp. Soc. Psychol.)", "year": 2006}, {"author": "Sagan, C.", "title": "The Demon-Haunted World: Science as a Candle in the Dark", "year": 1995}]$v$::jsonb, quiz = $v$[{"q": "What does a speculative chip mean on this shelf?", "choices": ["The practice is worthless", "The practice may be valuable but the explanation offered for it is not supported", "The teacher is being dishonest"], "correct": 1, "explain": "Speculative rates the story, not the exercise. Keep the practice, drop the explanation."}, {"q": "What earns progress in the Vault?", "choices": ["Running its practice", "Opening the app", "Reading a piece"], "correct": 0, "explain": "Understanding is the first stage; the practice is the one that counts."}, {"q": "Who can see your reflections?", "choices": ["The coach quotes them in chat", "Your squad", "Only you"], "correct": 2, "explain": "Private rows, never surfaced; only practices run become badges."}]$v$::jsonb, reflect_prompt = $v$Which thinker on this shelf have you swallowed whole, practice and metaphysics together? What did you keep, and what did you quietly drop?$v$, integrate_prompt = $v$You wrote three sentences for one thinker. Which of the three was hardest to finish, and what does that say about how you read?$v$, practice_minutes = 10, read_time_min = 4, updated_at = now() WHERE slug = 'how-to-read-a-teacher';
UPDATE public.vault_articles SET title = $v$One Week With the Masters$v$, subtitle = $v$The shelf folded into seven days you can run without believing any of it$v$, summary = $v$The shelf ends as a week, not a reading list. Morning light, the control sort, one identity vote, the sixty-second return, a promise kept, a projection check, a Sunday audit: the masters folded into a routine that takes under twenty minutes a day.$v$, evidence_tier = $v$promising$v$, benefits = ARRAY[$v$One routine that carries the shelf's daily practices in under twenty minutes$v$, $v$A three-week ramp that adds tools only when the earlier ones hold$v$, $v$A Sunday that audits the week on more scales than XP$v$], risks = ARRAY[$v$Running all of it at once is the fastest way to run none of it; the ramp is the method$v$, $v$The week is a menu with a suggested order, not a contract; drop what does not pay$v$], body_md = $v$**Why a week, not a list**
Twenty-four pieces is a library. A week is a practice. Each piece on this shelf earns its place by changing a Tuesday, and the way to find out which ones change yours is to run them together for seven days, then keep the ones that paid.

**Morning, six minutes**
Light first: outside within the hour, no sunglasses; the dose lives in Morning Light Anchor. Then three physiological sighs before the day's first hard thing. Then the control sort from Epictetus: three worries, a line down the middle, one action for the column that is yours. Then Marcus Aurelius' one line naming the person most likely to test you today. Finish with Clear's identity sentence, read once: I am the kind of person who.

**Whenever, under a minute each**
Tolle's sixty-second return when the thinker takes over: hands, the furthest sound, one long exhale, what is here right now. Byrne's welcome when a feeling arrives that you would rather fight: drop the story, find it in the body, let it be there. Jung's projection check when someone irritates you out of proportion: which quality is it, and where is it in you.

**Training, thirty seconds**
Between sets, Dispenza's rehearsal from the inside: the next set, feeling included. On the day you least want to go, Goggins' promise: written last night, kept today.

**Evening, four minutes**
Seneca's review: what went badly, what went well, what was left undone. Thich Nhat Hanh's one task done fully, the dishes as the dishes. One line of gratitude with the why.

**Sunday, fifteen minutes**
Sharma's eight forms, scored one to five. Seneca's time audit: where the week's hours went, and one hour reclaimed. Frankl's question: what is this month asking, and who receives the answer. Attia's decathlon glance: which capacity did this week ignore.

**What the week leaves out**
Aristotle, Campbell, Nietzsche, Greene, Kabat-Zinn and Robbins run on longer clocks: a trait built over weeks, a stage of a change, a must rewritten, an apprenticeship, an eight-week course, a model studied. Their pieces carry their own practices. This week keeps the daily ones.

**How to introduce it**
Running everything at once is the fastest way to run none of it. Week one: the morning block and the return. Week two: add the whenever-tools and the evening. Week three: add training and Sunday. Then keep what earned its minutes and let the rest go without guilt.$v$, why_it_matters = $v$A shelf is finished when it changes a week, not when the last piece is marked complete. This is the change: the masters' practices, under twenty minutes a day, inside the app's own rhythm of check-ins, sessions and Sundays.$v$, key_takeaways = ARRAY[$v$Morning: light, three sighs, the control sort, one line for the difficult person, the identity sentence.$v$, $v$Whenever: the return, the welcome, the projection check. Evening: the review, one task done fully.$v$, $v$Sunday: the eight forms, the time audit, Frankl's question, the decathlon glance.$v$], try_today = ARRAY[$v$Put tomorrow's morning block in the calendar: light, three sighs, the control sort, one line, the identity sentence.$v$, $v$Set a Sunday reminder for the eight-forms score and the time audit.$v$, $v$Write down which two whenever-tools you will carry this week, and where you expect to need them.$v$], references_json = $v$[{"author": "Note", "title": "The shelf's own recap; no external source"}, {"author": "Lally, P. et al.", "title": "How are habits formed: Modelling habit formation in the real world (Eur. J. Soc. Psychol.)", "year": 2010}, {"author": "Gollwitzer, P. M. & Sheeran, P.", "title": "Implementation intentions and goal achievement: A meta-analysis of effects and processes (Adv. Exp. Soc. Psychol.)", "year": 2006}]$v$::jsonb, quiz = $v$[{"q": "How should the week be introduced?", "choices": ["All of it from day one", "In three weeks: the morning block and the return first, then the whenever-tools and the evening, then training and Sunday", "Only on rest days"], "correct": 1, "explain": "Running everything at once is the fastest way to run none of it."}, {"q": "Which pieces run on longer clocks and stay out of the daily week?", "choices": ["Huberman and Epictetus", "Tolle and Byrne", "Aristotle, Campbell, Nietzsche, Greene, Kabat-Zinn and Robbins"], "correct": 2, "explain": "A trait, a stage, a rewritten must, an apprenticeship, a course and a model take weeks, not minutes."}, {"q": "What does the week keep after three weeks?", "choices": ["What earned its minutes; the rest goes without guilt", "Only the morning block", "Everything, on principle"], "correct": 0, "explain": "The week is a menu with a suggested order, not a contract."}]$v$::jsonb, reflect_prompt = $v$Which of the daily practices would you keep if you could keep only one, and why that one?$v$, integrate_prompt = $v$You ran the week. Which practice earned its minutes, and which one did you let go of without missing it?$v$, practice_minutes = 20, read_time_min = 3, updated_at = now() WHERE slug = 'wisdom-practice-stack';
UPDATE public.vault_articles SET title = $v$Jung: The Shadow and What It Projects$v$, subtitle = $v$Carl Jung's map of the parts of you that you do not show, and why they run the show anyway$v$, summary = $v$Jung's shadow is everything you have decided you are not. It does not disappear; it leaks, mostly as strong reactions to other people. The practice is to use those reactions as a map.$v$, evidence_tier = $v$promising$v$, benefits = ARRAY[$v$A way to read your own irritation as information instead of noise$v$, $v$The one Jungian tool with a mechanism that has been measured: projection$v$, $v$A practice that takes back a piece of yourself you had handed to someone else$v$], risks = ARRAY[$v$Jung's theory is a model, not a finding; the chip rates the projection exercise, which has experimental support, not the architecture$v$, $v$The map is for owning a quality, not excusing an act; my shadow made me do it is the wrong reading$v$], body_md = $v$**The parts you do not show**
Carl Jung split from Freud in 1913 and spent the next half-century mapping what lies outside the ego. The shadow is the part everybody has heard of. It is everything you have decided you are not: the anger you do not have, the envy you are above, the laziness, the vanity, the neediness. None of it goes away. It goes underground, and from there it decides more than you would like.

**How it leaks**
The shadow does not announce itself. It arrives as a reaction that is too big for its cause: the colleague whose confidence makes your skin crawl, the friend whose laziness you cannot stop mentioning, the stranger on a board whose boasting you read three times. Jung's word for this is projection. The quality you refuse in yourself is easiest to see, and hardest to forgive, in someone else. That is why irritation out of proportion is not noise. In Jung's map it is the most precise information about yourself you will get this week.

**Reading the map**
The exercise is short and uncomfortable. List three people or types who irritate you beyond what they have done. For each, name the quality that does it in one word. Then the sentence Jung's method turns on: where does that quality live in me, and what would it cost to admit it? The aim is not to like these people, and not to confess to being them. It is to take back a piece of yourself you had handed to a stranger.

**What the research adds**
Jung's theory is not experimental, and this piece does not pretend otherwise. What has been studied is the mechanism he named. Defensive projection, seeing one's own unwanted traits in others, was demonstrated in controlled work by Newman, Duff and Baumeister (1997), and later studies link suppressing a trait to noticing it more in other people. That supports the direction of the practice, not Jung's architecture, so the chip says promising.

**Where it goes wrong**
Two failure modes. The first is turning the shadow into a story: my shadow made me do it. The map is for owning a quality, not excusing an act. The second is stopping at the confession. Jung's word for the longer work was individuation, becoming the whole of what you are, and the piece on the persona picks that up: the mask you wear to meet the world, and where it has started deciding for you.

**Where it meets your week**
Squads, boards and battles put other people in front of you every day. The ones who get under your skin are not noise. They are the map.$v$, why_it_matters = $v$Squads, boards and battles put other people in front of you every day. The ones who get under your skin are not noise; in Jung's map they are the most precise information about you that you will get this week.$v$, key_takeaways = ARRAY[$v$The shadow is everything you have decided you are not; it leaks as reactions too big for their cause.$v$, $v$Irritation out of proportion is a map: name the quality, then find where it lives in you.$v$, $v$Projection has been measured; Jung's wider architecture has not. Keep the exercise.$v$], try_today = ARRAY[$v$List three people or types who irritate you out of proportion, and the quality in each that does it.$v$, $v$For each quality, write one sentence: where does it live in me, and what would it cost to admit it?$v$, $v$Next time the irritation comes, name the quality silently before you react.$v$], references_json = $v$[{"author": "Note", "title": "Original lesson on the ideas of Carl Jung; not affiliated with the Jung estate or any Jungian institute"}, {"author": "Jung, C. G.", "title": "Aion: Researches into the Phenomenology of the Self (Collected Works 9ii)", "year": 1951}, {"author": "Newman, L. S., Duff, K. J. & Baumeister, R. F.", "title": "A new look at defensive projection: Thought suppression, accessibility, and biased person perception (J. Pers. Soc. Psychol.)", "year": 1997}]$v$::jsonb, quiz = $v$[{"q": "What does Jung mean by projection?", "choices": ["Public speaking", "Planning the future", "Seeing a quality you refuse in yourself most sharply in someone else"], "correct": 2, "explain": "The disowned quality is easiest to see, and hardest to forgive, in another person."}, {"q": "What has the research actually supported?", "choices": ["The mechanism of defensive projection", "That the shadow is a literal entity", "Jung's whole map of the psyche"], "correct": 0, "explain": "Controlled studies show the mechanism; the architecture stays a model."}]$v$::jsonb, practice_minutes = 10, read_time_min = 3, updated_at = now() WHERE slug = 'jung-shadow-individuation';
UPDATE public.vault_articles SET subtitle = $v$Andrew Huberman's four most reliable levers, read the way he reads evidence: mechanism first, then the trial, then the number$v$, summary = $v$Huberman's gift is turning physiology into levers you can pull today. Four of them, morning light, the physiological sigh, dopamine baselining and deliberate cold, carry the strongest evidence. This piece is about how he reads that evidence and where the podcast overreaches; the doses live on the Recovery and Mind shelves.$v$, evidence_tier = $v$strong$v$, benefits = ARRAY[$v$The four Huberman levers with the strongest evidence, and where each one's dose lives$v$, $v$A way to read a protocol podcast: mechanism, trial, then the number as an experiment$v$, $v$The dopamine baseline framing, which explains why a stacked morning feels flat by noon$v$], risks = ARRAY[$v$The specific numbers in the protocols are often inferences, not trial results; run them as defaults to test$v$, $v$Cold and caffeine both have rules that matter more than the dose: cold away from strength work, caffeine away from bed$v$], body_md = $v$**A neuroscientist with a podcast**
Andrew Huberman runs a lab at Stanford and, since 2021, a podcast that turned physiology into a to-do list for millions. The format is the same every episode: a mechanism, the studies, then a protocol. It is also why he is worth reading carefully rather than swallowing. The mechanism is usually right, the protocol is usually reasonable, and the specific number is sometimes an inference the trial never ran.

**Light: the clock**
Morning light through the eyes tells a cluster of cells behind the retina what time it is, and that signal sets the clock the rest of the day runs on, including when melatonin is released fourteen to sixteen hours later. The mechanism is solid and the human data is large. The dose lives in Morning Light Anchor on the Recovery shelf; this piece only asks you to notice that the cheapest lever on tonight's sleep is what you do tomorrow morning.

**Breath: the sigh**
A double inhale through the nose and a long exhale through the mouth reinflates collapsed air sacs and slows the heart within one or two breaths. The mechanism was known for decades; the trial that made it a practice was Balban et al. (2023), five minutes a day for a month against mindfulness meditation. The practice lives in The Physiological Sigh on the Mind shelf.

**Dopamine: the baseline**
Huberman's most useful framing is that dopamine has a baseline and peaks, and that stacking peaks, caffeine, music, a phone, a pre-workout, all at once, borrows from the baseline the rest of the day runs on. The advice that follows, delay the first coffee, keep some effort unrewarded, is a reasonable reading of the pharmacology. The ninety-minute figure for caffeine is an inference from adenosine clearance, not a trial result, so treat it as a default to test.

**Cold: deliberate discomfort**
Cold water raises noradrenaline and dopamine for hours and trains the response to stress in a place you chose. Cold is also where the podcast leans hardest on small studies. The piece that owns it, Cold Exposure on the Recovery shelf, gives the weekly dose and the rule that matters most: keep it hours away from strength work.

**Where the podcast overreaches**
Claims about fat loss, immunity and the exact numbers in the protocols are thinner than the mechanisms behind them. Read him the way this shelf reads everyone: keep the mechanism and the practice, run the number as an experiment, drop the certainty.

**Where it meets your week**
Sleep, water and training are three of the numbers your check-in tracks. Light and the sigh are the two cheapest levers on them, and they cost ten minutes and three breaths.$v$, key_takeaways = ARRAY[$v$Light sets the clock; the dose lives in Morning Light Anchor.$v$, $v$The sigh is the fastest evidenced way to lower arousal; the practice lives in The Physiological Sigh.$v$, $v$Keep the mechanism and the practice, run the number as an experiment, drop the certainty.$v$], try_today = ARRAY[$v$Tomorrow morning: outside within the hour, no sunglasses, phone in your pocket; the minutes are in Morning Light Anchor.$v$, $v$Before today's first hard thing: three physiological sighs.$v$, $v$Pick one number you have taken from a podcast as fact and run it for a week as an experiment, with a note at check-in.$v$], references_json = $v$[{"author": "Note", "title": "Original lesson on the ideas of Andrew Huberman; not affiliated with the author or Huberman Lab"}, {"author": "Huberman, A.", "title": "Huberman Lab (podcast)", "year": 2021}, {"author": "Balban, M. Y. et al.", "title": "Brief structured respiration practices enhance mood and reduce physiological arousal (Cell Rep. Med.)", "year": 2023}, {"author": "Blume, C., Garbazza, C. & Spitschan, M.", "title": "Effects of light on human circadian rhythms, sleep and mood (Somnologie)", "year": 2019}]$v$::jsonb, quiz = $v$[{"q": "Why is morning light first among the four?", "choices": ["It sets the circadian clock that the rest of the day, including sleep, runs on", "It replaces coffee", "It burns calories"], "correct": 0, "explain": "Light is the dominant time-setter for the human clock; melatonin release is timed from the morning signal."}, {"q": "What should cold exposure be kept away from?", "choices": ["Breakfast", "The hours after strength training", "Rest days"], "correct": 1, "explain": "Post-training cold blunts the signalling the session was for. Put it before, or on a rest day."}, {"q": "What did the 2023 Balban trial find?", "choices": ["Breathing has no effect on mood", "Meditation beat breathing", "Cyclic sighing beat mindfulness meditation for mood and arousal over a month"], "correct": 2, "explain": "Five minutes a day of cyclic sighing outperformed meditation on mood and breathing rate."}]$v$::jsonb, read_time_min = 3, updated_at = now() WHERE slug = 'huberman-protocol-stack';
UPDATE public.vault_articles SET summary = $v$Attia's question is simple: what do you want to be able to do at ninety? Most people train for the next event. The Centenarian Decathlon back-calculates from the last decade instead, and usually reveals one capacity the current week ignores.$v$, evidence_tier = $v$promising$v$, benefits = ARRAY[$v$A reason to train that survives the day motivation does not: a specific future you can picture$v$, $v$A ten-task list that turns into one capacity your week is ignoring$v$, $v$The four capacities, with their evidence on the Longevity shelf$v$], risks = ARRAY[$v$The decathlon is a planning exercise; the mortality data behind the capacities is cohort data, so the chip says promising$v$, $v$Training for ninety can be used to postpone living; the list is a reason to train, not to wait$v$], body_md = $v$**The question nobody asks**
Peter Attia is a physician who left surgery and a stretch in consulting to practise what he calls Medicine 3.0: prevention aimed decades ahead. Outlive, from 2023, is the argument and the manual. Its central move for training is a question: what do you want to be able to do in your last decade? Lift a grandchild. Carry groceries up stairs. Get off the floor without hands. Walk a trail. Most people have never asked, so they train for the next event and arrive at eighty unable to do the things they would have chosen.

**The Centenarian Decathlon**
The tool is a list. Write ten physical tasks you want to be able to do at ninety, specifically. Then back-calculate. Capacity declines with age at a known rate, so to do a task at ninety you need a large margin now; each task maps to a capacity to build well beyond the task itself. Carrying two bags of groceries up three flights at ninety needs the grip, the legs and the aerobic base of someone who can carry far more than that at forty.

**Four capacities, one week**
Attia trains four things: an aerobic base, peak aerobic capacity, strength, and stability, the ability to load the body safely so the other three can be trained into old age. The Longevity shelf owns the evidence and the doses: the ranking in The Hierarchy of Levers, VO₂max in the predictor lesson, strength in Strength: The Longevity Organ. This piece owns the exercise that tells you which of the four your week has been ignoring.

**Where it meets the science**
The decathlon is a planning exercise, not a study, and the cohort data behind Attia's four capacities is observational: nobody can randomise forty years of training. That makes the frame promising rather than strong. The direction is as well supported as observational medicine gets, and the ten-task list is the part you can act on tomorrow.

**Where it goes wrong**
Training for ninety at thirty can become a way to postpone living. The list is a reason to train, not a reason to wait. It is also a reason to rest, because the capacity that matters most at ninety is the one you did not injure out of the programme at forty-five.

**Where it meets your week**
Your program trains for the next block. This piece asks what it is missing for the last decade, and adds one session for the capacity it ignores.$v$, key_takeaways = ARRAY[$v$Ten specific tasks at ninety, back-calculated to capacities now.$v$, $v$Four capacities: aerobic base, peak aerobic, strength, stability; the doses live on the Longevity shelf.$v$, $v$The list usually reveals one capacity your week ignores. Add one session for it.$v$], quiz = $v$[{"q": "What is the Centenarian Decathlon?", "choices": ["A supplement stack", "A race for old people", "Ten physical tasks you want at ninety, back-calculated to the capacities to train now"], "correct": 2, "explain": "A reason to train that is specific enough to picture and to plan from."}, {"q": "What kind of evidence sits behind the four capacities?", "choices": ["Cohort data, as strong as observational medicine gets and still an inference", "Anecdotes", "Randomised trials"], "correct": 0, "explain": "Nobody can randomise forty years of training; the inference is well supported and still an inference."}]$v$::jsonb, read_time_min = 3, updated_at = now() WHERE slug = 'attia-centenarian-decathlon';
UPDATE public.vault_articles SET summary = $v$The Greatest Secret drops the law of attraction for something older: you are the awareness the thoughts and feelings appear in. Its one practice, welcoming a feeling instead of fighting it, is worth keeping.$v$, body_md = $v$Rhonda Byrne's first book, The Secret, told millions that thoughts attract outcomes. The Inner Work pillar of this Vault has an honest lesson on why that claim fails (manifestation-demystified). Her later book is a different animal. The Greatest Secret says the thing you have been looking for is not a thing at all: it is the awareness you have been looking with.

**The claim**
Thoughts come and go. Feelings come and go. The body changes. What stays constant through all of it is the fact that it is being noticed. Byrne, drawing on the non-dual teachers she quotes throughout, argues that this noticing is what you actually are, and that suffering comes from mistaking yourself for the contents instead of the container.

You do not have to accept the metaphysics to test the observation. Ask, right now: am I aware? The answer is obviously yes, and it arrived before any thought did. That two-second question is the book's most portable practice. It does not solve anything; it briefly moves you out of the argument in your head into the room you are in.

**Welcoming**
The practice this lesson keeps is the one for difficult feelings. Most of us do one of two things with a hard emotion: push it down or feed it a story. Byrne's alternative is to let it be there fully, as a sensation in the body, without the narrative, and to notice that a feeling that is allowed passes in minutes while a feeling that is fought can last for days. This maps closely onto what acceptance-based therapies train. In ACT and in exposure work, willingness to feel an emotion without trying to control it is the ingredient that reduces its power over behaviour.

**What is supported and what is not**
Supported: allowing an emotion rather than suppressing it. Suppression studies consistently show a rebound, the white bear effect, where the pushed-down thought returns stronger. Accepting a feeling lowers its intensity and its cost. Not supported: that awareness is the fundamental substance of reality, or that realising it removes suffering permanently. Those are claims from a contemplative tradition, and they are honestly labelled speculative here. Keep the practice.

**The five-minute version**
Sit. Find the hardest feeling present today. Drop the story about it and find where it lives in the body. Say, silently, *you can be here.* Breathe with it for five minutes. Notice whether it changed. Most people find it did, and that the change came from not fighting it.$v$, try_today = ARRAY[$v$Ask "am I aware?" three times today, especially mid-argument with your own head.$v$, $v$Take one difficult feeling, drop its story, find it in the body, and give it five minutes of "you can be here".$v$, $v$Tonight, name one thing you have been trying to attract and write what you would do tomorrow if it never arrived.$v$], read_time_min = 3, updated_at = now() WHERE slug = 'greatest-secret-awareness';
UPDATE public.vault_articles SET summary = $v$Tolle's claim is that most suffering is made of thinking about the past and the future. The way out is not better thoughts but attention to the present moment, where problems are small and action is possible.$v$, read_time_min = 3, updated_at = now() WHERE slug = 'power-of-now-presence';
UPDATE public.vault_articles SET summary = $v$Watts argued that the demand for security is the source of insecurity. Life, he said, is better treated as music than as a journey to a destination; the point is the playing.$v$, why_it_matters = $v$Streaks and ranks are destinations, and they will keep you going for a while. Watts is the frame that makes the four hundredth check-in feel like playing rather than like a corridor, and only a game gets played four hundred times.$v$, read_time_min = 3, updated_at = now() WHERE slug = 'watts-wisdom-of-insecurity';
UPDATE public.vault_articles SET summary = $v$Seneca's essay on the shortness of life makes one argument: life is long enough if you use it. Most people hand their hours to other people's demands, to distraction and to a future that never arrives. The practice is an honest audit of the last seven days and one hour reclaimed.$v$, body_md = $v$Lucius Annaeus Seneca was a playwright, a senator, tutor and then adviser to Nero, one of the richest men in Rome, and a Stoic who was ordered to kill himself in 65 AD and did. He is the most human of the Stoics because he failed at his own advice often and wrote about it anyway. His essay On the Shortness of Life is addressed to a friend, Paulinus, who ran Rome's grain supply, and it is short enough to read in an hour.

**The argument**
We complain that life is short. Seneca says it is not; it is long enough, and we waste most of it. Wasted how? On other people's claims on us, on business that is not ours, on drink and sleep past need, on worry about the future and regret about the past, and above all on postponement: the plan to really start living once some condition is met. People guard their money and their land fiercely, he notes, and hand out their hours to anyone who asks.

**The evening review**
Elsewhere, in the essay On Anger, Seneca describes a nightly habit he learned from Sotion, a follower of the philosopher Sextius: when the lamp is out and the house is quiet, go back over the day and ask what you did badly, what you did well, what you left undone. He says he sleeps better for it. It is the ancestor of every evening reflection, including the one in this app.

**What the research adds**
The modern version of Seneca's audit is time-use research. When people record how they actually spend a week, the record and the story they told themselves diverge, and the divergence is where the change comes from: seeing hours go to low-value defaults tends to move them. The effects in trials are modest, and the specific one-week audit plus one reclaimed hour has not been tested on its own. The mechanism is plausible and the cost is fifteen minutes, so the chip says promising.

**Where it meets your week**
The check-in already asks how you slept and whether you trained. It does not ask where the other fourteen hours went. Once a week, this practice does, and it ends with one hour moved on purpose rather than a vague resolve to do better.$v$, references_json = $v$[{"author": "Note", "title": "Original lesson on the ideas of Seneca; the essays and letters are in the public domain"}, {"author": "Seneca", "title": "De Brevitate Vitae (On the Shortness of Life)", "year": 49}, {"author": "Seneca", "title": "De Ira (On Anger), Book III, on the evening review", "year": 45}, {"author": "Hamermesh, D. S.", "title": "Spending Time: The Most Valuable Resource (Oxford University Press)", "year": 2019}]$v$::jsonb, read_time_min = 3, updated_at = now() WHERE slug = 'seneca-on-time';
UPDATE public.vault_articles SET summary = $v$Aristotle says we become just by doing just acts and brave by doing brave ones, the way builders become builders by building. Character is a settled disposition formed by repetition. The practice is choosing one trait, finding the smallest act it is made of, and repeating it for a week.$v$, read_time_min = 3, updated_at = now() WHERE slug = 'aristotle-habituation';
UPDATE public.vault_articles SET summary = $v$Campbell argued that the world's myths share one shape: a call, a refusal, a threshold, an ordeal, a return with something to give. Whether every story fits is contested. As a lens on your own change, the map is useful for one thing: it tells you which stage you are in, and that the stage is not the verdict.$v$, body_md = $v$Joseph Campbell taught comparative mythology at Sarah Lawrence College and in 1949 published The Hero with a Thousand Faces. Its claim is that the world's myths retell one story, which he called the monomyth: a hero leaves the ordinary world, faces trials, and returns changed with something to give. George Lucas has credited it as an influence on Star Wars, and screenwriting has used the map ever since.

**The stages that matter**
Campbell's full map has seventeen steps; five do the work. The call: something asks you to change. The refusal: you decline, usually with a good reason. The threshold: you cross into unfamiliar territory and cannot easily go back. The ordeal: the hardest part, where the old self does not work any more. The return: you come back with a gift, and the gift is the point.

**Read it honestly**
Folklorists have argued for decades that the monomyth fits the stories it fits and is forced onto the rest, and that Campbell's reading is more Jungian than anthropological. Both criticisms are fair. That is why this piece does not ask you to believe that all myths are one. It asks you to use the shape the way a coach uses a training phase: as a name for where you are.

**What the research adds**
Dan McAdams' work on narrative identity shows that people who tell the story of their hard stretches with a redemptive arc, difficulty that led somewhere, report more wellbeing and generativity than people who tell the same events as contamination stories. That is correlational and the direction is not settled. But it supports the practical move here: naming your stage in a story with a next chapter changes what you do next. The frame itself has not been trialled, so the chip says promising.

**Where it meets your week**
A program, a new sport, a return after injury, the first weeks of a membership: each has a call, a refusal that sounds like sensible reasons, a threshold and an ordeal. Most people quit at the refusal without ever naming it. The practice below names it.$v$, read_time_min = 3, updated_at = now() WHERE slug = 'campbell-heros-journey';
UPDATE public.vault_articles SET summary = $v$Zarathustra opens with three changes: the camel that carries every must, the lion that says I will not, the child that says I will. The philosophy is a stance, not a finding. The practice, rewriting one must as a will, is a way to test whether you chose the load you carry.$v$, read_time_min = 3, updated_at = now() WHERE slug = 'nietzsche-self-overcoming';
UPDATE public.vault_articles SET summary = $v$Goggins turned a broken start into ultramarathons and special-forces selections, and his book is the memoir of it. Three tools survive without the mythology: a written promise on the mirror, a jar of proof from past hard things, and a habit of doing the thing on the day you least want to. The 40% rule is a heuristic, not a finding, and the piece says so.$v$, references_json = $v$[{"author": "Note", "title": "Original lesson on the ideas of David Goggins; not affiliated with the author or publisher"}, {"author": "Goggins, D.", "title": "Can't Hurt Me: Master Your Mind and Defy the Odds", "year": 2018}, {"author": "Marcora, S. M. & Staiano, W.", "title": "The limit to exercise tolerance in humans: mind over muscle? (Eur. J. Appl. Physiol.)", "year": 2010}, {"author": "Inzlicht, M. & Friese, M.", "title": "The past, present, and future of ego depletion (Social Psychology)", "year": 2019}]$v$::jsonb, read_time_min = 3, updated_at = now() WHERE slug = 'goggins-callused-mind';
UPDATE public.vault_articles SET body_md = $v$Viktor Frankl was a Viennese psychiatrist before the war and a prisoner in four camps during it, Theresienstadt, Auschwitz, Kaufering and Türkheim. Man's Search for Meaning, written in nine days in 1946, is half memoir and half the outline of the therapy he called logotherapy. Its claim is narrow and testable in your own week: the people who kept going had something to answer for. A manuscript to finish. A person waiting. A way of carrying a situation nobody could change.

**The question, reversed**
Most of us ask what we want from life and then feel let down by the answer. Frankl turns it around. Life is asking questions of you, in the concrete form of this week's situations, and you answer with what you do. Meaning is not found lying around like a coin; it is made by responding. That is why he called responsibility the other half of freedom. You are free to choose your response; you are responsible for the one you choose.

**Three roads to it**
Frankl named three ways meaning shows up. Through what you create or do: your craft, your training, the work only you will finish. Through what you encounter: people, beauty, love, the things that ask you to pay attention. And through the attitude you take toward suffering you cannot remove: illness, loss, an injury that ended a season. The third road is the one that made his method famous, and it is also the one most often misused. He never said suffering is good. He said that when it is unavoidable, the stance you take toward it is still yours, and that stance can carry meaning.

**What the research adds**
Since Steger's 2006 meaning-in-life work, presence of meaning has been measured in tens of thousands of people. It tracks with lower depression, better sleep, more physical activity and, in large cohorts, lower mortality. Those are associations. They do not show that writing a purpose statement makes you healthier. What they do show is that the thing Frankl pointed at is real, common and measurable, and that people who have it behave differently on ordinary days. That is why the chip says promising: the practice below has a plausible mechanism and early support, and no trial has run it as written.

**Where it meets your week**
The streak and the check-in are answers to a question you set for yourself. They hold up on days when the question is alive and fall apart when it goes quiet. Frankl's move is to keep the question audible: not "do I feel like it" but "what is this day asking of me, and who is on the other end of the answer".$v$, read_time_min = 3, updated_at = now() WHERE slug = 'frankl-meaning-responsibility';
UPDATE public.vault_articles SET summary = $v$The Miracle of Mindfulness began as a long letter to a colleague running a training school in wartime Vietnam. Its instruction is simple: when you wash the dishes, wash the dishes. Do the thing you are doing, with the breath as the anchor.$v$, body_md = $v$Thich Nhat Hanh was a Zen monk from Vietnam who opposed the war from inside it, was exiled for it, and spent the rest of his life teaching in the West what he called engaged Buddhism. The Miracle of Mindfulness was written in 1974 as a long letter to a colleague running a school of social workers in the war zone, and it is still the clearest short manual on the subject.

**Doing the thing you are doing**
The central image is washing dishes. There are two ways to do it: to get them done so you can have your tea, or to wash them. In the first, you are not present for the dishes and, he argues, you will not be present for the tea either, because the habit of being elsewhere follows you. Mindfulness, in his usage, is simply being where you are, doing what you are doing, and the everyday tasks are where it is trained, not the cushion.

**The breath as anchor**
Every time attention wanders, and it will, the breath is where you come back to. Not a special breath: the one already happening. He recommends counting or a short phrase paired with the in-breath and out-breath, and a bell, any bell, as a reminder to stop and take three breaths. The point is not to breathe better. It is to have a place to return to that is always with you.

**What the research adds**
Mindfulness training has been studied more than any other contemplative practice, and the numbers live in Mindfulness (MBSR) on the Mind shelf: moderate, repeated effects on stress and mood from structured eight-week courses. The everyday form here is gentler and its effects should be expected to be smaller. The mechanism, trained attention, is the same, which is why the chip stays strong.

**The half-smile and the warning**
He recommended a half-smile during practice, which sounds precious and works: it is difficult to hold a small smile and stay tense. He also knew that people can be flooded by what they find when they stop moving. If that happens, stop; the practice is meant to be kind.

**Where it meets your week**
A set of squats, a walk to the station, the dishes after dinner. Each is already in your day. One of them, done as the only thing, is the whole practice.$v$, read_time_min = 3, updated_at = now() WHERE slug = 'thich-nhat-hanh-one-thing';
UPDATE public.vault_articles SET summary = $v$In 1979 Jon Kabat-Zinn opened a stress-reduction clinic in a hospital basement for patients medicine had run out of options for. The programme he built, MBSR, is the most-studied mindfulness course in existence. Its core is the body scan: attention moved slowly through the body without trying to change anything.$v$, read_time_min = 3, updated_at = now() WHERE slug = 'kabat-zinn-full-catastrophe';
UPDATE public.vault_articles SET body_md = $v$Joe Dispenza's books describe a loop most people will recognise: you wake up, think the same thoughts, which produce the same feelings, which drive the same choices, which produce the same day. His claim is that the loop can be broken on purpose, in meditation, by rehearsing a different state until it is more familiar than the old one.

**The loop**
Thoughts produce feelings. Feelings shape what you notice and what you want. Wants drive actions. Actions produce a day, and the day confirms the thoughts. Dispenza's framing, that you are literally rehearsing your current self every morning, is a useful exaggeration. Habit research agrees with the mechanism: repeated thought-and-response pairs become automatic and context-cued.

**Rehearsal with feeling**
The method is to sit, settle, and then rehearse a specific future: a hard set completed, a conversation handled well, a version of you a year from now. Not as a picture only. Dispenza insists on the feeling: the body should experience the state, gratitude or steadiness or pride, *now*, as if the event had already happened. His argument is that the brain does not distinguish well between a vividly rehearsed experience and a lived one, so rehearsal with emotion installs the new pattern.

**What the evidence supports**
Quite a lot, for the rehearsal. Motor imagery research shows that mentally practising a movement activates overlapping brain regions and produces measurable strength and skill gains, smaller than physical practice but real. The Inner Work lesson on imagery covers the sharper version: rehearse the *process* and the obstacles, not the trophy. Contemplative practice reliably shifts stress physiology, and deliberately generated positive emotion has measurable effects on heart-rate variability and mood. So the ten-minute practice below is promising.

**What it does not support**
Dispenza's explanation reaches into quantum physics and claims that meditation can cure serious illness. The physics is used as a metaphor and presented as a mechanism; that is not how the field works. The healing testimonials are uncontrolled. This lesson labels the method speculative because of those claims, and asks you to keep the rehearsal and leave the rest. If you are ill, the rehearsal can sit next to treatment. It cannot replace it.

**The ten-minute rehearsal**
Sit. Two minutes of slow breathing, longer out than in. Then pick one specific scene from the next week, not the next decade. Rehearse it from the inside: what you see, what your hands do, the exact moment it gets hard and what you do then. Let the feeling of having done it well arrive in the body and stay with it for two minutes. Open your eyes. Do the real thing within the week, so the rehearsal has somewhere to land.$v$, try_today = ARRAY[$v$Run the ten-minute rehearsal on one specific scene from the next seven days, obstacle included.$v$, $v$Between sets today, rehearse the next set from the inside for thirty seconds before you lift.$v$, $v$Write the obstacle you are most likely to meet in the scene, and rehearse the moment you meet it, not the trophy.$v$], read_time_min = 3, updated_at = now() WHERE slug = 'dispenza-rehearsal';
UPDATE public.vault_articles SET body_md = $v$James Clear's book is the most-used habit manual of its decade, and its central move is easy to miss under the tactics: stop aiming at outcomes and start aiming at identity.

**Outcomes, systems, identity**
Most goals are outcomes: lose five kilos, run a marathon, read more. Outcomes are where results show up, but they are not where change happens. Change happens in the system, the daily process, and the system is driven by identity, the story you tell about the kind of person you are. A person who *is* a runner runs on a wet Tuesday. A person who *wants to* run negotiates. Clear's framing is that every action is a vote for a type of person. You do not need a unanimous election. You need a majority.

**The loop: cue, craving, response, reward**
A habit runs as a loop. A cue (the phone on the pillow) triggers a craving (a hit of novelty), which drives a response (scroll), which delivers a reward (the hit). The loop repeats because the reward teaches the brain to expect it at the cue. Every tactic in the book pulls on one of the four stages.

**The four laws**
- Make it obvious: put the cue in your path. Shoes by the door, water bottle on the desk, the app on the home screen. Habit stacking is a cue rule: after an existing habit, do the new one.
- Make it attractive: pair it with something you want. Podcast only while walking.
- Make it easy: shrink it until it takes two minutes. Not "read a book", "read one page". The two-minute version is not the goal; it is the entrance.
- Make it satisfying: give yourself a visible tick. A streak is exactly this, a reward that arrives before the outcome does.

Breaking a habit inverts the laws: make it invisible, unattractive, hard, unsatisfying. Move the app off the home screen. Add friction.

**Environment beats willpower**
The most under-used lever in the book is the room. People with what looks like great self-control mostly live in environments where the tempting thing is not there. Design the room and you stop needing the willpower. This is why the app asks you to set a session reminder and a check-in time: they are cues placed in your path.

**What the evidence supports**
Habit research is real and reasonably consistent. Lally and colleagues tracked people forming a new daily behaviour and found automaticity plateauing after a median of 66 days, with a range from 18 to 254 and not three weeks. Missing a single day made no measurable difference to the curve. Wood and Neal's work shows that a large share of daily behaviour is cued by context rather than chosen, which is the environment argument. What is not evidenced is the tidy arithmetic of one percent per day; treat it as a picture of compounding, not a formula.

**Where it goes wrong**
Tracking becomes the habit. The streak becomes the goal. If you notice you are protecting a number rather than becoming a person, return to the identity question: what would the person I am becoming do today? Clear's rule for a broken streak is the useful one: never miss twice. One miss is an accident. Two is the start of a new habit.$v$, read_time_min = 4, updated_at = now() WHERE slug = 'atomic-habits-identity';
UPDATE public.vault_articles SET body_md = $v$After the break with Freud in 1913, Jung spent fifty years on the parts of the psyche that are not the ego. The shadow is the famous one. The persona is the quieter one, and for people who are good at what they do it is often the more important. The word is the Latin for an actor's mask, and Jung meant it neutrally: the persona is the face you build to meet the world, shaped by what your work, your family and your culture reward.

**Necessary, and not you**
Jung was clear that the persona is not a lie. You need one. A surgeon needs a surgeon's face; a coach needs a coach's. The trouble starts when the person and the persona fuse, when someone is their rank, their record, their reputation, and has nothing left when those are threatened. He called it identification with the persona, and he thought it was the characteristic illness of successful people at midlife: the ladder climbed, the mask perfected, and a hollowness behind it that no further success touches.

**Individuation**
His word for the way out was individuation: becoming the whole of what you are, which includes the shadow and excludes nothing. It is not self-improvement. It is closer to self-inclusion, and it begins with the plain act of noticing where the mask is doing the living. Which decisions are made because the role requires them? Which feelings are not allowed because the role would not have them? Which people only ever meet the mask?

**What the research adds**
Jung did not run experiments, and this piece does not pretend he did. What has been studied is the gap between the self as presented and the self as felt: self-discrepancy work since Higgins in 1987 links large gaps between the ought self and the actual self to anxiety and low mood, and the authenticity literature links acting in line with one's own values to wellbeing. Those findings support the direction of the practice, not Jung's architecture. The chip says promising for that reason.

**Where it meets your week**
A tier, a division, a badge case: the app hands you a persona if you want one. The Watts and Tolle lessons ask you to hold it lightly. This one asks the prior question: where, this week, did the mask decide?$v$, read_time_min = 3, updated_at = now() WHERE slug = 'jung-persona-mask';
