-- Vault · Wisdom: Sharma's eight forms rewritten to his own scorecard, and Tony Robbins
-- joins the shelf with the one piece of Unlimited Power the library lacked (modelling a
-- specific person, the seven useful lies as chosen stances, rapport by matching), with the
-- honest note on NLP. Machine shape (scripts/vault-content.mjs).

UPDATE public.vault_articles SET subtitle = $v$Robin Sharma's scorecard: eight forms of wealth, and the one that sets the ceiling$v$, summary = $v$Sharma's argument is that a life measured on one scale is poor even when the number is high. His eight forms of wealth are a scorecard, and his rule is that the lowest score sets how rich the life feels. The practice is the audit, once a week, and one hour moved.$v$, evidence_tier = $v$promising$v$, benefits = ARRAY[$v$A scorecard with eight scales instead of one, and a rule for which one to work on$v$, $v$Two forms with heavy evidence behind them, named honestly$v$, $v$A five-minute weekly audit that ends with one hour moved, not eight resolutions$v$], risks = ARRAY[$v$The lowest-score rule is Sharma's rule of thumb, not a finding; use it to choose, not to judge$v$, $v$Six of the eight forms are lived values, not measured outcomes; the chip rates the audit as a practice, and the audit has no trial behind it$v$], body_md = $v$**One scale is not enough**
Ask a room whether they are wealthy and most people reach for a number. Robin Sharma, a leadership writer whose books have sold in the tens of millions, argues in The Wealth Money Can't Buy that the number is one scale of eight, and that a life scored on it alone is poor even when it is high. The book is a scorecard. The practice is the audit.

**The eight forms**
1. Inner wealth: the state you carry into the day. Self-respect, calm, gratitude, the strength to sit with a hard feeling. Sharma puts it first because nothing outside can compensate for its absence.
2. Wellness: energy, sleep, strength, the body you live in. A sick person wants one thing; a well person wants a thousand.
3. Family and connection: the people who will be at the hospital bed, and whether you are present for them now.
4. Craft and calling: work done well for its own sake, and the sense that it is yours to do. Mastery from your own starting point, not someone else's.
5. Money as sufficiency: enough, with margin, and the freedom that margin buys. A tool, not the measure.
6. Community and network: the people who know your name, and the people who open doors. The quality of a life tracks the quality of its company.
7. Adventure: novelty, travel, the things you will remember. A life that is only routine is not a rich one.
8. Impact and legacy: what you give that is not for you, and what outlasts you.

**The rule**
Sharma's practical rule is that the lowest form sets the ceiling: a life at five on money and two on family feels like a two. That is a rule of thumb, not a finding, and it is useful because it points the next hour at the form that is starving.

**Where the evidence is strong**
Two forms carry heavy evidence. Connection: Holt-Lunstad and colleagues' 2010 meta-analysis of 148 studies found that people with strong social ties had roughly half the mortality risk of the isolated over the periods studied, and the Harvard Study of Adult Development, eighty years in, keeps finding that relationships predict late-life health better than cholesterol. Wellness: the Longevity shelf is the evidence. Two more forms have good support. Experiences over possessions: Gilovich and colleagues find that money spent on doing yields more durable satisfaction than money spent on having. Service: Okun and colleagues' 2013 meta-analysis links volunteering to lower mortality in older adults. Money past sufficiency is the interesting one: Killingsworth (2021) found wellbeing keeps rising with income for most people, but the slope is shallow, and it does nothing for the other seven scales.

**Where it goes wrong**
Scoring all eight and then trying to raise all eight is the usual failure. The audit's job is to find the lowest score and move one hour toward it this week; the other seven are fine for now. The second failure is treating the forms as a ledger of guilt. Sharma's scorecard is a map for choosing, not a verdict.

**Once a week, five minutes**
Score the eight forms, one to five. Find the lowest. Put one hour toward it in next week's calendar. Sunday works, because the app already asks you to look back then.$v$, why_it_matters = $v$The W-Index measures the body and the habits. It does not measure family, craft or what you give. This lesson is the wider scorecard, so a good week in the app can be checked against a good week in the life.$v$, key_takeaways = ARRAY[$v$Eight forms: inner wealth, wellness, family and connection, craft and calling, money as sufficiency, community and network, adventure, impact and legacy.$v$, $v$The lowest score sets the ceiling; move one hour toward it this week.$v$, $v$Connection and wellness carry heavy evidence, experiences and service good evidence; money past sufficiency buys little on the other seven.$v$], try_today = ARRAY[$v$Score the eight forms one to five, honestly, now.$v$, $v$Circle the lowest and write the one hour you will give it this week, with a day and a time.$v$, $v$Tell one person which form you are working on; a named form is harder to forget.$v$], references_json = $v$[{"author": "Note", "title": "Original lesson on the ideas of Robin Sharma; not affiliated with the author or publisher"}, {"author": "Sharma, R.", "title": "The Wealth Money Can't Buy: The 8 Hidden Habits to Live Your Richest Life", "year": 2024}, {"author": "Holt-Lunstad, J., Smith, T. B. & Layton, J. B.", "title": "Social relationships and mortality risk: A meta-analytic review (PLoS Med.)", "year": 2010}, {"author": "Gilovich, T., Kumar, A. & Jampol, L.", "title": "A wonderful life: Experiential consumption and the pursuit of happiness (J. Consum. Psychol.)", "year": 2015}, {"author": "Okun, M. A., Yeung, E. W. & Brown, S.", "title": "Volunteering by older adults and risk of mortality: A meta-analysis (Psychol. Aging)", "year": 2013}, {"author": "Killingsworth, M. A.", "title": "Experienced well-being rises with income, even above $75,000 per year (PNAS)", "year": 2021}]$v$::jsonb, quiz = $v$[{"q": "What is Sharma's rule for which form to work on?", "choices": ["The money form, because it funds the rest", "The one you enjoy most", "The lowest score, because it sets the ceiling on how rich the life feels"], "correct": 2, "explain": "A rule of thumb, not a finding; it points the next hour at the form that is starving."}, {"q": "Which two forms carry the heaviest evidence?", "choices": ["Connection and wellness", "Craft and legacy", "Adventure and money"], "correct": 0, "explain": "Social ties in a 148-study meta-analysis and the whole Longevity shelf."}, {"q": "What does the weekly audit end with?", "choices": ["Eight resolutions", "One hour moved toward the lowest form", "A new scorecard"], "correct": 1, "explain": "Find the lowest, move one hour; the other seven are fine for now."}]$v$::jsonb, practice_minutes = 15, read_time_min = 4, updated_at = now() WHERE slug = 'eight-forms-of-wealth';

INSERT INTO public.vault_articles (category_id, slug, title, subtitle, summary, evidence_tier, read_time_min, benefits, risks, body_md, why_it_matters, key_takeaways, try_today, references_json, quiz, display_order, lesson_number, course_role, master_slug, reflect_prompt, integrate_prompt, practice_minutes) VALUES ($v$wisdom$v$, $v$robbins-unlimited-power$v$, $v$Robbins: Model the Result, Then Change the Body$v$, $v$Tony Robbins' Unlimited Power stripped to what survives: modelling a specific person, beliefs chosen on purpose, rapport by matching, and the body first$v$, $v$Robbins' first book says success is not luck but a sequence that can be copied. Three of its tools survive the eighties packaging: modelling one person's belief, mental sequence and physiology; the seven useful lies as beliefs you adopt on purpose; and rapport by matching. The NLP behind it did not survive testing, and the piece says so.$v$, $v$speculative$v$, 4, ARRAY[$v$A modelling checklist: one person, three things to copy, one week$v$, $v$Seven beliefs to adopt on purpose, read as stances rather than facts$v$, $v$Rapport by matching, the one social tool the shelf did not have$v$], ARRAY[$v$NLP's specific claims failed controlled tests; the chip says speculative because the framework is unsupported even where the exercises are$v$, $v$Matching used as a trick is obvious within a minute; used as attention it is generous. Do not fake it$v$], $v$**A sequence you can copy**
Tony Robbins was twenty-six when Unlimited Power came out in 1986, and the book made him. Its claim is simple: success leaves traces. If someone has the result you want, you can get the same result by copying not their outcome but their process, and the process has three parts. What they believe about themselves and about what is possible. The order in which they think, the mental syntax that runs before they act. And what they do with their body: breath, posture, pace, the face. Robbins called copying those three modelling, and it is the one idea in the book worth building a practice on.

**Modelling one person**
The practice is precise. Not a hero, not a type: one person you can observe or ask, who has your result. Write what they believe about the thing, usually something like "this is normal for people like me". Write the sequence they run, what they do first and what they never do. Write their physiology in the moment it matters. Then run one of the three for a week. Modelling is observational learning with a checklist, and observational learning is among the oldest findings in psychology, described by Bandura (1977). Greene's apprenticeship on this shelf is the long form of the same move.

**The seven useful lies**
Robbins lists seven beliefs he calls lies because they cannot be proved, and worth holding because they work: everything happens for a reason that can serve you; there is no failure, only results; whatever happens, you are responsible; you do not need to know everything to act; people are your greatest resource; work is play; there is no lasting success without commitment. Read them the way this shelf reads everyone. They are not findings; they are stances you adopt on purpose, and the honest version of the exercise is to pick one, hold it for a week, and watch what it does to your Tuesdays. The second one, no failure, only results, is the same move the Inner Work shelf makes when it treats a missed session as data.

**The body first**
Robbins' loudest claim is that you can change a mood in seconds by changing the body: stand up, breathe faster, look up, move. The Inner Work shelf owns that lever in Elevating Your Energy, with the evidence and the caveats; this piece only asks you to notice that Robbins arrived at it a generation earlier, from the stage rather than the lab.

**Rapport by matching**
This is the tool nobody else on the shelf teaches. People trust what feels like them, so Robbins teaches matching: the pace of speech, the posture, the words the other person uses, before you ask for anything. Used as attention it is generous; used as a trick it is obvious within a minute. The practice is to match for the first two minutes of a hard conversation and say nothing about yourself until you have.

**What did not survive**
The book is built on neuro-linguistic programming, and NLP's specific claims, eye-movement cues, representational systems, anchoring as a science, failed controlled tests; Witkowski's 2010 review of thirty-five years of research found almost no support. That is why the chip says speculative. The exercises here have their own support, modelling from Bandura and matching from the rapport literature, and the framework around them does not.

**Where it meets your week**
Someone on a board, in your squad or in your gym has the result you are chasing. Modelling turns them from a rival into a manual.$v$, $v$Boards and squads put people with your result in front of you every day. Robbins' method turns one of them into a manual: their belief, their sequence, their body, copied for a week.$v$, ARRAY[$v$Success leaves traces: copy one person's belief, sequence and physiology, not their outcome.$v$, $v$The seven useful lies are stances chosen on purpose; hold one for a week and watch your Tuesdays.$v$, $v$NLP did not survive testing; modelling and matching have their own evidence, and that is what this piece keeps.$v$], ARRAY[$v$Name one person who has your result and write their belief, their sequence and their physiology in three lines.$v$, $v$Before today's session, spend two minutes in their physiology: their posture, their pace, their breath.$v$, $v$In your next hard conversation, match the other person's pace and words for two minutes before you say anything about yourself.$v$], $v$[{"author": "Note", "title": "Original lesson on the ideas of Tony Robbins; not affiliated with the author or publisher"}, {"author": "Robbins, T.", "title": "Unlimited Power: The New Science of Personal Achievement", "year": 1986}, {"author": "Bandura, A.", "title": "Social Learning Theory", "year": 1977}, {"author": "Witkowski, T.", "title": "Thirty-five years of research on Neuro-Linguistic Programming. NLP research data base. State of the art or pseudoscientific decoration? (Polish Psychological Bulletin)", "year": 2010}]$v$::jsonb, $v$[{"q": "What are the three things Robbins says to model?", "choices": ["Diet, sleep, training", "Belief, mental sequence, physiology", "Income, network, schedule"], "correct": 1, "explain": "Copy the process, not the outcome: what they believe, the order they think in, what they do with the body."}, {"q": "What happened to NLP's specific claims in controlled tests?", "choices": ["They were never tested", "They were confirmed", "They found almost no support"], "correct": 2, "explain": "Witkowski's 2010 review of thirty-five years of studies; the exercises keep their own evidence, the framework does not."}, {"q": "How should the seven useful lies be read?", "choices": ["As stances adopted on purpose and tested for a week", "As jokes", "As proven facts"], "correct": 0, "explain": "Robbins calls them lies himself; the honest exercise is to hold one and watch what it does."}]$v$::jsonb, 324, 24, $v$protocol$v$, $v$robbins$v$, $v$Whose result do you want, and what do they believe about it that you do not?$v$, $v$You spent two minutes in someone else's physiology before a session. What moved first, the body or the mood?$v$, 10) ON CONFLICT (slug) DO NOTHING;
