-- Vault · Strength and Conditioning, rewritten in the house voice (docs/VAULT_VOICE.md).
-- Eight lessons in reading order, every piece with the loop, a quiz, risks and verified references.
-- Retired: the engine builder (a compression of lessons 3 and 4). Deload absorbs active recovery (was on Recovery).
-- Numbers follow the registry: Zone 2 is 2–4 sessions of 45–60 min at conversational pace; the 4×4 is 4 × 4 min
-- at 90–95% of maximum heart rate with 3 min easy, once a week after 4–6 weeks of base; deload every 4–6 weeks
-- with volume cut by 40–50%. Helgerud's gain is 7.2%, not 10%.
-- Machine shape: UPDATE … SET col = $v$…$v$ WHERE slug = '…';

-- Zero members had opened it; lessons 3 and 4 carry its two ingredients with their evidence.
DELETE FROM public.vault_articles WHERE slug IN ('engine-builder-zone2-4x4');

UPDATE public.vault_articles SET title = $v$Training: Stress, Recover, Adapt$v$, subtitle = $v$One loop under every programme on this shelf$v$, summary = $v$Every adaptation follows one loop: stress a little beyond the usual, recovery enough to repair, a rebuild slightly stronger. Get the dose and the recovery right and the programme almost does not matter.$v$, evidence_tier = $v$strong$v$, protocol = $v${}$v$::jsonb, benefits = ARRAY[$v$One mental model for every kind of training$v$, $v$Stops the programme-hopping that costs most people their results$v$, $v$Explains why each lesson that follows works$v$], risks = ARRAY[$v$Not a substitute for coaching with an injury or a competitive goal$v$, $v$The loop assumes recovery is possible; on four hours of sleep, fix that first$v$], body_md = $v$**The loop**
Selye (1950) described how an organism responds to a stressor: alarm, resistance, then either adaptation or exhaustion. Training is the controlled version. You do something slightly harder than the body is used to. You sleep, eat and rest enough to repair. The body rebuilds a little more capable than before. Miss any of the three and nothing happens; most people miss the second.

**Four levers**
This shelf covers the levers with the most evidence behind them across strength and endurance. Progressive overload is the requirement that the stress rises over time. Zone 2 is the sustainable stress that builds the aerobic base. The Norwegian 4×4 is the peak stress that raises the ceiling. Deloads and rest days are the recovery that lets the other three land. Then three practical pieces: a finishable beginner block, the daily movement floor under the gym, and eight minutes of mobility for a body that sits.

**What this shelf skips**
Exercise selection, because a squat and a leg press both work when the overload is real. Splits, for the same reason. Fashion: blood-flow restriction, instability training and daily undulating periodisation are all useful somewhere and none of them is foundational.

**The usual mistake**
Changing programmes every three weeks. The body adapts to the programme you finish, not the one you start. Pick a structure, hold it for eight to twelve weeks with the load rising, deload, then judge it.

**How to read this shelf**
Eight lessons in order. The first four are principles with numbers attached; the last three are things to do on Monday. Each ends with a practice.$v$, why_it_matters = $v$Programmes change. The loop does not. Once it is clear, every lesson on this shelf is an instance of one idea: the right stress, followed by the recovery that turns it into adaptation.$v$, try_today = ARRAY[$v$Look at the last seven days. Write down where you applied stress and where you recovered.$v$, $v$Find one place you are doing too much (every session hard, no rest) or too little (the same weights for months).$v$, $v$That gap is where the next lessons pay first.$v$], key_takeaways = ARRAY[$v$Adaptation is stress plus recovery; skip either and there is no change.$v$, $v$More is not better; the right dose, recovered from, repeated, is better.$v$, $v$Every lesson on this shelf runs on the same loop.$v$], quiz = $v$[{"q": "Where does adaptation happen?", "choices": ["During recovery: sleep, food, rest", "During the warm-up", "During the session"], "correct": 0, "explain": "The session is the stimulus. The rebuild happens afterward, and skipping it forfeits the adaptation."}, {"q": "The most common reason people do not see results?", "choices": ["Wrong exercises", "Changing programmes before adaptation completes", "Bad genetics"], "correct": 1, "explain": "The body adapts to the programme that gets finished. Most are abandoned at week three out of boredom."}]$v$::jsonb, references_json = $v$[{"author": "Selye, H.", "title": "Stress and the general adaptation syndrome (BMJ)", "year": 1950}, {"author": "American College of Sports Medicine (ACSM)", "title": "Progression models in resistance training for healthy adults: position stand (Med. Sci. Sports Exerc.)", "year": 2009}, {"author": "Bompa, T. O. & Haff, G. G.", "title": "Periodization: Theory and Methodology of Training, 5th ed.", "year": 2009}]$v$::jsonb, reflect_prompt = $v$Which half of the loop do you find easier, the stress or the recovery, and what does that say about your last three months?$v$, integrate_prompt = $v$You held one programme for a week without changing it. What did you want to change, and why?$v$, practice_minutes = 5, lesson_number = 1, display_order = 1, course_role = $v$foundations$v$, read_time_min = 2, updated_at = now() WHERE slug = 'foundations-strength-conditioning';

UPDATE public.vault_articles SET title = $v$Progressive Overload$v$, subtitle = $v$The one requirement behind every gain$v$, summary = $v$Training stress has to rise over time or adaptation stops. Add load, reps or sets one at a time, log every working set, and let the numbers climb slowly.$v$, evidence_tier = $v$strong$v$, protocol = $v${"duration": "Every training week", "frequency": "Weekly micro-progression, monthly review", "intensity": "Add 2.5 kg, or 2 to 5%, when the top of the rep range is clean", "prerequisites": "Sound technique on the lifts being progressed"}$v$::jsonb, benefits = ARRAY[$v$Predictable, measurable strength gains$v$, $v$The discipline of tracking$v$, $v$Escape from effort without progress$v$, $v$Compounds across years$v$], risks = ARRAY[$v$Load before technique is the injury path$v$, $v$Joints and tendons adapt slower than muscle; add volume gradually$v$, $v$Without deloads the climb stalls; see lesson 5$v$], body_md = $v$**The principle**
Once a stimulus is mastered, the body stops adapting to it. Progressive overload is the requirement that the stimulus keeps rising: heavier, more reps, more sets, or harder in some other measurable way. The American College of Sports Medicine's position stand on progression (ACSM 2009) puts the load increase at 2 to 10% once the target reps are reached with good technique; for most lifts that is the smallest plate.

**Four levers, in order**
Load: add 2.5 kg, or 2 to 5%, when every set hits the top of the rep range with clean technique. Reps: add a rep per set before adding weight; five sets of five becomes five sets of six, then the load goes up and the reps drop back. Sets: Schoenfeld et al. (2017) pooled fifteen studies and found more growth above ten hard sets per muscle per week than below five, with returns flattening somewhere around twenty. Tempo, range and rest: slower lowering, deeper range, shorter rests, for the weeks when load cannot rise because a joint is cranky or the gym is a hotel basement.

**How to run it**
Pick two to four main lifts across the patterns: squat, hinge, press, pull. Log every working set as weight, reps and how many reps were left in the tank. Use double progression: four sets of six to eight; when all four sets hit eight, add 2.5 kg and start again at six. Every four to six weeks, take the deload from lesson 5.

**Where it fails**
Weight added before the reps are clean, so form breaks and then something else does. Random sessions with no log, so there is no signal to progress against. Ego loading, which fatigues the nervous system without a growth stimulus. And the quiet one: never deloading, so the climb stalls and gets blamed on the programme.

**The compounding**
One rep or one small plate a week looks like nothing. Held for a year, it is a different lifter. The log is the programme.$v$, why_it_matters = $v$People train hard for years and stay the same because nothing rises. The body changes only when it is asked to. A notebook and one variable at a time is the whole method.$v$, try_today = ARRAY[$v$Pick one compound lift. Write down today's weight and reps.$v$, $v$Next session, add one rep, one set or 2.5 kg. One variable, not three.$v$, $v$Log it. Memory lies about last week.$v$], key_takeaways = ARRAY[$v$Progress one variable at a time: load, reps, sets, or quality.$v$, $v$If it is not logged, it is not progressing.$v$, $v$Small and relentless beats big and sloppy; the log is the programme.$v$], quiz = $v$[{"q": "Which is not progressive overload?", "choices": ["One more rep at the same weight", "A slower lowering phase", "Training to failure every set, every session"], "correct": 2, "explain": "Failure every set is junk volume and a recovery debt. Overload is small, trackable increments."}, {"q": "What single habit sustains progression?", "choices": ["Logging every working set", "Pre-workout", "A new programme every month"], "correct": 0, "explain": "You cannot progress what you do not measure. A notebook beats the fanciest programme with no log."}, {"q": "Schoenfeld's 2017 pooled analysis found…", "choices": ["More sets never help", "More growth above ten weekly sets per muscle than below five", "Only load matters"], "correct": 1, "explain": "Fifteen studies; the dose-response flattened somewhere around twenty sets."}]$v$::jsonb, references_json = $v$[{"author": "American College of Sports Medicine (ACSM)", "title": "Progression models in resistance training for healthy adults: position stand (Med. Sci. Sports Exerc.)", "year": 2009}, {"author": "Schoenfeld, B. J., Ogborn, D. & Krieger, J. W.", "title": "Dose-response relationship between weekly resistance training volume and increases in muscle mass: a systematic review and meta-analysis (J. Sports Sci.)", "year": 2017}]$v$::jsonb, reflect_prompt = $v$What is the last lift you can prove went up, and when?$v$, integrate_prompt = $v$After a week of logging, what did the numbers show that your memory did not?$v$, practice_minutes = 5, lesson_number = 2, display_order = 2, course_role = $v$protocol$v$, read_time_min = 2, updated_at = now() WHERE slug = 'progressive-overload';

UPDATE public.vault_articles SET title = $v$Zone 2: The Aerobic Base$v$, subtitle = $v$Conversational pace, most of your cardio minutes$v$, summary = $v$Zone 2 is the hardest pace at which you can still speak in full sentences. Two to four sessions a week of 45–60 minutes builds the mitochondria that every other session runs on.$v$, evidence_tier = $v$strong$v$, protocol = $v${"duration": "45–60 min per session", "frequency": "2–4 sessions a week, 150–180 min in total", "intensity": "60 to 70% of maximum heart rate; full sentences possible", "prerequisites": "No acute cardiac symptoms"}$v$::jsonb, benefits = ARRAY[$v$More mitochondria and better fat oxidation$v$, $v$Lower resting heart rate and blood pressure$v$, $v$The strongest fitness-to-mortality association in cohort data$v$, $v$Stacks with strength training at almost no recovery cost$v$], risks = ARRAY[$v$Most people go too hard; use the talk test, not feel$v$, $v$The time cost is real: two to three hours a week$v$, $v$New to cardio: build the minutes over weeks to spare the joints$v$], body_md = $v$**What it is**
San Millán and Brooks (2018) define the zone in the lab as the highest intensity at which blood lactate stays roughly flat, around two millimoles per litre: the mitochondria are clearing lactate as fast as the muscle makes it. Without a lab, two proxies do the job. Heart rate at 60 to 70% of maximum, with maximum estimated as 208 minus 0.7 times your age (Tanaka et al. 2001). And the talk test: full sentences possible, singing not. Most people go too hard and drift into the zone above, which costs more and builds less.

**Why it is the base**
Mandsager et al. (2018) followed 122,007 patients after a treadmill test at the Cleveland Clinic. Each step up in fitness tracked with lower mortality, and the fittest group had about a fifth of the death rate of the least fit over the follow-up, an effect larger than smoking's in the same data. That is cohort data, and fitness is partly inherited, so the number overstates what training alone delivers; the direction is not in doubt. Zone 2 is where the base is built: more mitochondria, better fat oxidation, a lower resting heart rate, and the capacity that lets the hard session in lesson 4 be hard.

**The dose**
2–4 sessions a week, 45–60 minutes each, 150–180 minutes in total. Brisk uphill walking, cycling, rowing, swimming, or running if your joints are happy. It stacks with strength work, because it costs the nervous system almost nothing. Seiler (2010) found that elite endurance athletes spend about 80% of their training time this easy, and the pattern holds for amateurs with far fewer hours: most minutes easy, a few genuinely hard.

**Where it goes wrong**
Training at 80% of maximum and calling it Zone 2; that is threshold work, and it taxes recovery. One long session a week instead of three shorter ones; the adaptation wants frequency. Skipping it because it feels too easy. It is meant to.

**The point**
The base is boring, slow, and the most important thing in the programme. Everything faster is built on it.$v$, why_it_matters = $v$Mitochondrial function sits under most chronic disease and under every hard session you will ever do. Zone 2 is the only intensity that builds it in volume without a recovery bill.$v$, try_today = ARRAY[$v$Find the pace: full sentences possible, a song not. Slightly uncomfortable, fully sustainable.$v$, $v$This week, 2–4 sessions of 45–60 minutes: incline walk, bike, row or jog.$v$, $v$If you cannot speak in full sentences, slow down. That is the whole test.$v$], key_takeaways = ARRAY[$v$150–180 minutes a week at conversational pace, in 2–4 sessions.$v$, $v$Full sentences possible, singing not: that is the zone.$v$, $v$Boring, slow, and the foundation for everything faster.$v$], quiz = $v$[{"q": "You are in Zone 2 if…", "choices": ["You feel nothing", "You are gasping", "You can speak in full sentences but could not sing"], "correct": 2, "explain": "The talk test is the most reliable marker without a lactate meter."}, {"q": "Weekly target for health and the aerobic base?", "choices": ["150–180 minutes", "10 hours", "30 minutes"], "correct": 0, "explain": "In 2–4 sessions of 45–60 minutes. Frequency matters more than one long outing."}, {"q": "Mandsager's 2018 data are…", "choices": ["A randomised trial", "A cohort of 122,007 patients; a strong association, with fitness partly inherited", "A case series"], "correct": 1, "explain": "The direction is not in doubt; the size of the number is more than training alone delivers."}]$v$::jsonb, references_json = $v$[{"author": "San-Millán, I. & Brooks, G. A.", "title": "Assessment of metabolic flexibility by means of measuring blood lactate, fat, and carbohydrate oxidation responses to exercise in professional endurance athletes and less-fit individuals (Sports Med.)", "year": 2018}, {"author": "Mandsager, K. et al.", "title": "Association of cardiorespiratory fitness with long-term mortality among adults undergoing exercise treadmill testing (JAMA Netw. Open)", "year": 2018}, {"author": "Tanaka, H., Monahan, K. D. & Seals, D. R.", "title": "Age-predicted maximal heart rate revisited (J. Am. Coll. Cardiol.)", "year": 2001}, {"author": "Seiler, S.", "title": "What is best practice for training intensity and duration distribution in endurance athletes? (Int. J. Sports Physiol. Perform.)", "year": 2010}]$v$::jsonb, reflect_prompt = $v$What does your easy pace actually feel like, and when did you last hold it for an hour?$v$, integrate_prompt = $v$Two weeks at conversational pace. Did the hard sessions get harder or easier?$v$, practice_minutes = 45, lesson_number = 3, display_order = 3, course_role = $v$protocol$v$, read_time_min = 3, updated_at = now() WHERE slug = 'zone-2-cardio';

UPDATE public.vault_articles SET title = $v$VO₂max: The Norwegian 4×4$v$, subtitle = $v$One hard session a week, on top of the base$v$, summary = $v$Four minutes hard, three minutes easy, four times, once a week after 4–6 weeks of Zone 2. It is the most efficient known stimulus for raising VO₂max, the strongest modifiable predictor of all-cause mortality in cohort data.$v$, evidence_tier = $v$strong$v$, protocol = $v${"duration": "About 45 min including warm-up and cool-down", "frequency": "Once a week; twice at most, never on consecutive days", "intensity": "4 × 4 min at 90–95% of maximum heart rate, 3 min easy between", "prerequisites": "4–6 weeks of Zone 2; no cardiac symptoms; blood pressure under control"}$v$::jsonb, benefits = ARRAY[$v$The largest VO₂max gains in the trial literature for the time spent$v$, $v$Higher stroke volume$v$, $v$A measurable number that tracks the long game$v$], risks = ARRAY[$v$High recovery cost; never two days in a row$v$, $v$Not for a beginner without a Zone 2 base$v$, $v$Chest pain, dizziness or an irregular heartbeat: stop and get checked$v$, $v$Untreated hypertension or known heart disease: a cardiologist first$v$], body_md = $v$**The session**
Helgerud et al. (2007) compared four ways of training the aerobic system in moderately trained men, matched for total work: long slow distance, lactate threshold running, 15-second intervals, and 4 × 4 minutes at 90–95% of maximum heart rate with 3 minutes easy between. Over eight weeks, the 4×4 group raised VO₂max by 7.2% and the 15/15 group by 5.5%; the two steady groups did not change it measurably. Stroke volume, the heart's output per beat, rose with it. The trial ran three sessions a week; the dose here is one, because the people on this shelf also lift and have jobs.

**How to run it**
Warm up ten minutes easy. Then four rounds: four minutes at 90–95% of maximum heart rate, which feels like single words only, then three minutes at an easy jog or spin. Cool down five minutes. About 45 minutes door to door. Any tool that loads big muscles works: bike, rower, ski erg, a hill, a treadmill. Track the splits and the heart rate; they should hold or improve week to week.

**Why it matters**
VO₂max is the strongest modifiable predictor of all-cause mortality in cohort data (Mandsager et al. 2018), and it falls about 10% a decade from the thirties unless it is trained. The 4×4 is the cheapest known way to push it up. This lesson owns the ceiling; the base that makes it possible is lesson 3.

**Where it fits**
After 4–6 weeks of Zone 2, not before; without the base the intervals feel impossible and the recovery costs the rest of the week. Once a week if you lift three times; twice at most if cardio is the priority, never on consecutive days. Put it on a day without heavy legs, with a day either side of the next hard session.

**When to skip it**
If the morning heart rate has been five beats high for three days, or the HRV trend from the Recovery shelf has fallen for five, do Zone 2 instead. The session is potent, and potency cuts both ways. Chest pain, dizziness or an irregular heartbeat during any session ends it and gets checked.$v$, why_it_matters = $v$The 4×4 is 45 minutes a week that raises the one fitness number most tightly tied to how long you live. It is also the session most likely to be done wrong: too early, too often, or on a body that has not recovered.$v$, try_today = ARRAY[$v$Pick the tool: bike, rower, hill or treadmill. Warm up ten minutes.$v$, $v$Four rounds: four minutes at single-word effort, three minutes easy.$v$, $v$Once a week. Do not add a second session in the first month.$v$], key_takeaways = ARRAY[$v$4 × 4 minutes at 90–95% of maximum heart rate, 3 minutes easy between, once a week.$v$, $v$7.2% more VO₂max in eight weeks in the original trial; the steady groups gained none.$v$, $v$Only after 4–6 weeks of Zone 2, and never on consecutive days.$v$], quiz = $v$[{"q": "Work-to-rest in the Norwegian 4×4?", "choices": ["30 seconds hard, 4 minutes easy", "1:1", "4 minutes hard, 3 minutes easy"], "correct": 2, "explain": "Four rounds at 90–95% of maximum heart rate with an easy three minutes between."}, {"q": "Why limit it to once or twice a week?", "choices": ["Near-maximal effort; more sessions build fatigue faster than fitness", "It stops working", "Equipment cost"], "correct": 0, "explain": "Each round sits near VO₂max. Recovery, not the session, is the limiting factor."}, {"q": "What comes before the first 4×4?", "choices": ["Nothing", "4–6 weeks of Zone 2", "A strength deload"], "correct": 1, "explain": "Without the base the intervals feel impossible and the recovery costs the week."}]$v$::jsonb, references_json = $v$[{"author": "Helgerud, J. et al.", "title": "Aerobic high-intensity intervals improve VO2max more than moderate training (Med. Sci. Sports Exerc.)", "year": 2007}, {"author": "Mandsager, K. et al.", "title": "Association of cardiorespiratory fitness with long-term mortality among adults undergoing exercise treadmill testing (JAMA Netw. Open)", "year": 2018}]$v$::jsonb, reflect_prompt = $v$Is your base ready for this, honestly, or is the hard session simply the part you like?$v$, integrate_prompt = $v$After the first two 4×4 sessions, what happened to your splits, and what happened to the rest of the week?$v$, practice_minutes = 45, lesson_number = 4, display_order = 4, course_role = $v$protocol$v$, read_time_min = 3, updated_at = now() WHERE slug = 'vo2max-4x4';

UPDATE public.vault_articles SET title = $v$Deload Weeks and Rest Days$v$, subtitle = $v$Planned easy weeks, and what a rest day is for$v$, summary = $v$Every 4–6 weeks, one week with volume cut by 40–50% and the load kept lets fatigue clear and the slow tissues catch up. Rest days are for moving gently, not for the couch.$v$, evidence_tier = $v$promising$v$, protocol = $v${"duration": "1 week", "frequency": "Every 4–6 weeks, or when three fatigue signs stack up", "intensity": "Volume cut by 40–50%; load 75 to 85% of working weights", "prerequisites": "A hard block of three or more weeks"}$v$::jsonb, benefits = ARRAY[$v$Joints and tendons catch up$v$, $v$Sleep, mood and drive rebound$v$, $v$The next block starts fresh$v$, $v$Fewer overuse injuries$v$], risks = ARRAY[$v$Skipping deloads does not toughen you; the fatigue accumulates$v$, $v$Too light defeats the point; keep the weights near working loads$v$, $v$Newer lifters can often run six weeks before needing one$v$], body_md = $v$**Why a planned easy week**
Muscle adapts in days. The nervous system recovers in days and accumulates fatigue across weeks. Tendons and joint capsules adapt over months. Train hard for twelve weeks straight and the muscles are ready for more while the elbows and the drive are not. Bell et al. (2020) reviewed the strength-sport literature on overreaching: the early signs are falling bar speed at the same load, worse sleep, a flat mood and joints that hurt in lifts that were fine a fortnight ago. A deload is the planned way to spend that fatigue before it spends you.

**What the evidence says, honestly**
The case for deloads rests on fatigue management and tendon health, not on muscle growth. Coleman et al. (2024) ran the one controlled trial: nine weeks of supervised training with or without a deload week in the middle produced the same muscle and strength gains. So a deload does not cost you muscle, and it does not add any. What it buys is the next block, which is why the chip says promising rather than strong.

**The deload**
One week. Volume cut by 40–50%: twelve working sets per muscle becomes six or seven. Load kept at 75 to 85% of the working weights, heavy enough to feel real. No sets to failure, no drop sets, no max attempts. Then straight into the next block. Every 4–6 weeks on a fixed schedule, or sooner when three of the signs above stack up.

**What a deload is not**
A week off, which loses the groove of the lifts. A week of random circuits, which is the same total stress in a different costume. A diet break, which is a separate decision.

**Rest days**
Rest is not nothing. Twenty to thirty minutes of easy walking, the mobility session from lesson 8, an easy spin or a sauna clears soreness faster than the sofa does. The rule of thumb is movement that raises blood flow without adding fatigue. And when you are genuinely run down, sleep wins; fatigue is information.$v$, why_it_matters = $v$Fitness shows up during recovery, not during the session. Without planned easy weeks, fatigue quietly masks fitness: you feel weaker, sleep worse and plateau, and blame the programme.$v$, try_today = ARRAY[$v$Open your training calendar. Find the next deload; if there is none, put one in week 4, 5 or 6.$v$, $v$For that week, cut the sets by 40–50% and keep the weights.$v$, $v$On the next rest day, walk for 25 minutes instead of sitting.$v$], key_takeaways = ARRAY[$v$Every 4–6 weeks: volume cut by 40–50%, load kept, one week.$v$, $v$Deloads manage fatigue and tendons; the one trial found no muscle cost and no muscle gain.$v$, $v$Rest days are for easy movement, not the couch.$v$], quiz = $v$[{"q": "What does a deload week look like?", "choices": ["New random movements", "No training", "Same lifts, about half the sets, most of the weight"], "correct": 2, "explain": "Keep the movement patterns, cut the work. Total rest loses the groove; random circuits are the same stress in a costume."}, {"q": "The controlled trial on deloads found…", "choices": ["The same muscle and strength gains with or without one", "Deloads caused muscle loss", "Deloads doubled growth"], "correct": 0, "explain": "Coleman 2024: no cost, no gain. The case for deloads is fatigue and tendons, not hypertrophy."}, {"q": "Which tissue adapts slowest?", "choices": ["Muscle", "Tendon and joint capsule", "The lungs"], "correct": 1, "explain": "Months, against days for muscle. That gap is what a deload closes."}]$v$::jsonb, references_json = $v$[{"author": "Bell, L., Ruddock, A., Maden-Wilkinson, T. & Rogerson, D.", "title": "Overreaching and overtraining in strength sports and resistance training: a scoping review (J. Sports Sci.)", "year": 2020}, {"author": "Coleman, M. et al.", "title": "Gaining more from doing less? The effects of a one-week deload period during supervised resistance training on muscular adaptations (PeerJ)", "year": 2024}, {"author": "Israetel, M., Hoffmann, J. & Smith, C. W.", "title": "Scientific Principles of Hypertrophy Training", "year": 2021}]$v$::jsonb, reflect_prompt = $v$When did you last plan an easy week, rather than have one forced on you?$v$, integrate_prompt = $v$After a deload week, what came back first: bar speed, sleep or appetite for the gym?$v$, practice_minutes = 10, lesson_number = 5, display_order = 5, course_role = $v$protocol$v$, read_time_min = 3, updated_at = now() WHERE slug = 'deload-periodization';

UPDATE public.vault_articles SET title = $v$A Four-Week Beginner Strength Block$v$, subtitle = $v$Three sessions a week, two workouts, one rule$v$, summary = $v$A complete, finishable block built on the lifts that matter, with the sets, the reps and the rule for adding weight. Three days a week; the whole point is finishing it.$v$, evidence_tier = $v$strong$v$, protocol = $v${"duration": "45 min per session", "frequency": "3 sessions a week, a day between", "intensity": "Last rep hard and clean; add 2.5 kg or one rep each week", "prerequisites": "Able to squat and hinge without pain"}$v$::jsonb, benefits = ARRAY[$v$Full-body strength in four weeks$v$, $v$Simple enough to finish$v$, $v$Teaches progressive overload by doing it$v$], risks = ARRAY[$v$Sharp joint pain is a stop signal; soreness is not$v$, $v$Learn the hinge and the squat from a coach or a mirror before loading them$v$, $v$If you have not trained in years, start with two sessions a week$v$], body_md = $v$**The structure**
Three sessions a week with a day between, Monday, Wednesday and Friday for most people. Two workouts, alternated, so week one runs A, B, A and week two runs B, A, B. Rest 90 to 120 seconds between sets. Every session starts with five minutes of easy movement and a light set of the first lift.

**Workout A**
Squat, goblet or back, 3 sets of 8. Push-up or bench press, 3 sets of 8. Dumbbell row, 3 sets of 10. Plank, 3 holds of 30 seconds.

**Workout B**
Romanian deadlift, 3 sets of 8. Overhead press, 3 sets of 8. Lat pulldown or assisted pull-up, 3 sets of 10. Hanging knee raise, 3 sets of 12.

**The rule**
Week one, find the weight where the last rep of each set is hard and clean. Each week after that, add 2.5 kg on the lower-body lifts and 1 to 2.5 kg on the upper-body lifts, or one rep per set if the plate is too big a jump. That is the progressive overload from lesson 2, applied. Week four is the peak; the week after is a deload from lesson 5, or the block restarted a little heavier.

**Why this and not more**
The American College of Sports Medicine's guidance for novices is two to three full-body sessions a week of one to three sets per exercise at 8 to 12 reps, progressing when the reps are clean (ACSM 2009). Ralston et al. (2017) pooled the strength trials and found that moderate weekly volume, roughly five to nine sets per lift, gains as much strength as high volume in people who are new to lifting. More is not the lever. Finishing is.

**Form over ego**
A clean set of eight beats a sloppy set of twelve every session. If a rep grinds or the back rounds, the weight stays where it is next week.$v$, why_it_matters = $v$Beginners gain fast on almost anything they finish and gain nothing on the programme they abandon in week three. This block is short enough to complete and structured enough to teach the one rule that matters.$v$, try_today = ARRAY[$v$Put the three sessions in the calendar now, with the day between.$v$, $v$Do Workout A today. The only goal is finding the starting weights.$v$, $v$Write the weights down. Next session, one of them goes up.$v$], key_takeaways = ARRAY[$v$Three full-body sessions a week, two workouts alternated, four weeks.$v$, $v$Add 2.5 kg or one rep each week; that is the whole programme.$v$, $v$A clean eight beats a sloppy twelve.$v$], quiz = $v$[{"q": "How do you progress from week to week?", "choices": ["Add a fourth session", "Change the exercises", "Add 2.5 kg or one rep per set"], "correct": 2, "explain": "One small increase, every week, on the same lifts. That is the lesson the block teaches."}, {"q": "For a new lifter, what did the pooled trials say about volume?", "choices": ["Moderate weekly volume gains as much strength as high", "Volume does not matter", "More is always better"], "correct": 0, "explain": "Ralston 2017: five to nine sets per lift per week matched higher volumes in novices."}]$v$::jsonb, references_json = $v$[{"author": "American College of Sports Medicine (ACSM)", "title": "Progression models in resistance training for healthy adults: position stand (Med. Sci. Sports Exerc.)", "year": 2009}, {"author": "Ralston, G. W., Kilgore, L., Wyatt, F. B. & Baker, J. S.", "title": "The effect of weekly set volume on strength gain: a meta-analysis (Sports Med.)", "year": 2017}]$v$::jsonb, reflect_prompt = $v$What has stopped you finishing a programme before, and is it in this one?$v$, integrate_prompt = $v$After the first week, which lift went up, and which one needs the weight to stay put?$v$, practice_minutes = 45, lesson_number = 6, display_order = 6, course_role = $v$protocol$v$, read_time_min = 2, updated_at = now() WHERE slug = 'beginner-strength-4-week-block';

UPDATE public.vault_articles SET title = $v$Daily Movement: The Floor Under the Gym$v$, subtitle = $v$Steps and broken-up sitting, which count even if you train$v$, summary = $v$An hour in the gym does not undo fifteen hours of sitting. Total daily movement is its own lever: 7,000 to 8,000 steps captures most of the benefit, and two minutes of walking every half hour blunts the glucose from a meal.$v$, evidence_tier = $v$promising$v$, protocol = $v${"duration": "All day", "frequency": "Two minutes of movement every 30 to 45 minutes of sitting", "intensity": "Walking pace; 7,000 to 8,000 steps a day", "prerequisites": "None; build gradually if currently sedentary"}$v$::jsonb, benefits = ARRAY[$v$Lower all-cause mortality across fifteen cohorts$v$, $v$Lower post-meal glucose and insulin$v$, $v$Steadier energy and mood through the day$v$], risks = ARRAY[$v$Build the volume over weeks if you are currently sedentary$v$, $v$The step data are cohorts; part of the effect is who walks, not only the walking$v$], body_md = $v$**Two separate levers**
A trained person who sits all day carries some of the risks of a sedentary one. Ekelund et al. (2016) pooled data on more than a million adults: the mortality risk of eight hours of daily sitting disappeared only in the people who also moved for 60 to 75 minutes a day at a moderate pace. Sitting and exercise are separate lines in the ledger; the gym pays one of them.

**Steps**
Paluch et al. (2022) pooled fifteen cohorts and 47,471 adults and found the mortality curve flattening at 6,000 to 8,000 steps a day for people over sixty and 8,000 to 10,000 for younger adults. Ten thousand was a marketing number from a Japanese pedometer; the real floor is lower, and most desk workers are well under it. The benefit is the curve, not a threshold: every thousand steps above three thousand shows a drop.

**Breaking up sitting**
Dunstan et al. (2012) had overweight adults sit for five hours and, on other days, walk for two minutes every twenty minutes. The light walking cut the glucose rise after a meal by about 24% and the insulin rise by about 23%. It is a small, sharp trial, and it says the same thing as the cohorts: the length of a sitting bout matters on its own. Stand or walk for two or three minutes every 30 to 45 minutes.

**Movement snacks**
A flight of stairs, twenty squats, a walk while taking a call, the long way to the kitchen. One or two minutes at a time. After a meal is the best time, because that is when the glucose is rising.

**How to hit the floor without a treadmill**
Walk the first and last kilometre of a commute. Take calls on foot. Put the printer far away. Count steps for two weeks to learn what a day looks like, then stop counting and keep the habits.$v$, why_it_matters = $v$The gym is the stimulus; daily movement is the foundation under it. Most people have the first and not the second, and the second is nearly free.$v$, try_today = ARRAY[$v$Today, walk two minutes every 45 minutes of sitting. Set a timer.$v$, $v$Do one movement snack after lunch: stairs or twenty squats.$v$, $v$Check your step count tonight and note the gap to 7,000.$v$], key_takeaways = ARRAY[$v$7,000 to 8,000 steps a day captures most of the mortality benefit; 10,000 was marketing.$v$, $v$Sitting and training are separate lines; break the sitting up every 30 to 45 minutes.$v$, $v$Two minutes of walking after a meal blunts the glucose rise.$v$], quiz = $v$[{"q": "Where does the steps-to-mortality curve flatten for adults under sixty?", "choices": ["3,000", "8,000 to 10,000", "20,000"], "correct": 1, "explain": "Paluch 2022, fifteen cohorts. Over sixty it flattens earlier, at 6,000 to 8,000."}, {"q": "In the Dunstan 2012 trial, two-minute walks every twenty minutes…", "choices": ["Raised blood pressure", "Did nothing", "Cut the post-meal glucose rise by about a quarter"], "correct": 2, "explain": "About 24% off the glucose rise and 23% off the insulin rise, against five hours of unbroken sitting."}, {"q": "Does an hour of training cancel a day of sitting?", "choices": ["Only at 60 to 75 minutes of moderate activity a day, in the pooled data", "Sitting is harmless", "Yes"], "correct": 0, "explain": "Ekelund 2016, more than a million adults. Below that, the sitting risk stays."}]$v$::jsonb, references_json = $v$[{"author": "Paluch, A. E. et al.", "title": "Daily steps and all-cause mortality: a meta-analysis of 15 international cohorts (Lancet Public Health)", "year": 2022}, {"author": "Dunstan, D. W. et al.", "title": "Breaking up prolonged sitting reduces postprandial glucose and insulin responses (Diabetes Care)", "year": 2012}, {"author": "Ekelund, U. et al.", "title": "Does physical activity attenuate, or even eliminate, the detrimental association of sitting time with mortality? A harmonised meta-analysis of data from more than 1 million men and women (Lancet)", "year": 2016}]$v$::jsonb, reflect_prompt = $v$How many hours did you sit yesterday, and how many of them were in one unbroken stretch?$v$, integrate_prompt = $v$A week of broken-up sitting. What did the afternoons feel like compared with the week before?$v$, practice_minutes = 10, lesson_number = 7, display_order = 7, course_role = $v$protocol$v$, read_time_min = 2, updated_at = now() WHERE slug = 'daily-steps-movement-floor';

UPDATE public.vault_articles SET title = $v$Mobility: Eight Minutes for the Desk Body$v$, subtitle = $v$Hips, upper back and shoulders, daily$v$, summary = $v$Sitting shortens the hip flexors, rounds the upper back and locks the shoulders. Eight minutes a day on those three areas keeps the lifts clean and the body moving; the evidence is for range of motion, not for pain.$v$, evidence_tier = $v$promising$v$, protocol = $v${"duration": "8 min", "frequency": "Daily", "intensity": "45 to 60 seconds per movement, no pain", "prerequisites": "None"}$v$::jsonb, benefits = ARRAY[$v$Better range in the hips, upper back and shoulders$v$, $v$Cleaner squat and press positions$v$, $v$A daily counter to desk posture$v$], risks = ARRAY[$v$Sharp pain is a stop signal; mobility work should not hurt$v$, $v$Persistent pain needs a physiotherapist, not more stretching$v$, $v$Long static holds right before lifting reduce force; keep them short or move them to after$v$], body_md = $v$**What sitting does**
Hours in a chair hold the hips at ninety degrees, curl the upper back and roll the shoulders forward. None of it is damage. It is a position the body has been told to keep, and it keeps it. The fix is to visit the other positions every day.

**What the evidence supports**
Range of motion improves reliably with a small daily dose: Thomas et al. (2018) pooled the stretching trials and found around five minutes a week per muscle group enough to gain range, with daily short sessions beating occasional long ones. Behm et al. (2016) reviewed the effects on performance: static holds over 60 seconds right before a strength session can blunt force output, while holds under 60 seconds, or stretching at another time of day, do not. So stretch daily, keep the holds under a minute before lifting, and do not expect a stretch to fix pain that a stretch did not cause. That is why the chip says promising.

**The routine, 45 to 60 seconds each**
1. Half-kneeling hip flexor stretch, pelvis tucked, lean forward. Both sides.
2. Ninety-ninety hip rotations, seated, knees swinging side to side.
3. Thoracic rotations on all fours, one hand behind the head, open toward the ceiling. Both sides.
4. Cat and cow, slowly, the whole spine.
5. Doorway chest stretch, forearms on the frame, step through.
6. Deep squat hold, heels down, elbows pushing the knees out.

**When**
As a morning primer before the first coffee, or as the midday desk reset. It pairs with the two-minute walks from lesson 7. The rule is daily and short; a long Sunday session does less than eight minutes on six days.

**Pain**
Sharp pain is a stop signal. Stiffness that eases as you move is normal. Pain that persists for more than two weeks, or that changes how you walk, needs a physiotherapist, not a longer stretch.$v$, why_it_matters = $v$A body that sits all day needs a daily reminder of its other positions. Eight minutes is enough to keep the hinges working and the lifts safe; it is not a treatment, and it should not be sold as one.$v$, try_today = ARRAY[$v$Run the six movements once today, 45 to 60 seconds each.$v$, $v$Set a midday reminder for the deep squat hold and the chest stretch.$v$, $v$Keep the holds under a minute if you are about to lift.$v$], key_takeaways = ARRAY[$v$Hips, upper back and shoulders: the three places sitting shortens.$v$, $v$Daily and short beats occasional and long; five minutes a week per muscle is enough for range.$v$, $v$Holds over a minute before lifting cost force; stretch after, or at another time.$v$], quiz = $v$[{"q": "What does the stretching evidence reliably support?", "choices": ["Curing back pain", "Gains in range of motion from small daily doses", "Injury prevention"], "correct": 1, "explain": "Thomas 2018: about five minutes a week per muscle group, best as short daily sessions."}, {"q": "Long static holds right before a strength session…", "choices": ["Have no effect", "Improve force", "Can blunt force output"], "correct": 2, "explain": "Behm 2016: over 60 seconds costs force; under 60 seconds, or at another time, does not."}]$v$::jsonb, references_json = $v$[{"author": "Thomas, E., Bianco, A., Paoli, A. & Palma, A.", "title": "The relation between stretching typology and stretching duration: the effects on range of motion (Int. J. Sports Med.)", "year": 2018}, {"author": "Behm, D. G., Blazevich, A. J., Kay, A. D. & McHugh, M.", "title": "Acute effects of muscle stretching on physical performance, range of motion, and injury incidence in healthy active individuals: a systematic review (Appl. Physiol. Nutr. Metab.)", "year": 2016}]$v$::jsonb, reflect_prompt = $v$Which of the three areas is stiffest for you, and what did you do today that made it so?$v$, integrate_prompt = $v$A week of eight minutes. Which lift, or which chair, felt different?$v$, practice_minutes = 8, lesson_number = 8, display_order = 8, course_role = $v$protocol$v$, read_time_min = 2, updated_at = now() WHERE slug = 'mobility-posture-8-min';
