require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'

# Use modular headers globally so Capacitor + RevenueCat resolve as Swift modules.
# This replaces the old `patch_capacitor_module_maps` hack which stripped
# `s.module_map` entries and broke `CapacitorCordova does not define modules`.
use_modular_headers!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorAppLauncher', :path => '../../node_modules/@capacitor/app-launcher'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      library_search_paths = Array(config.build_settings['LIBRARY_SEARCH_PATHS'])
      framework_search_paths = Array(config.build_settings['FRAMEWORK_SEARCH_PATHS'])
      swift_include_paths = Array(config.build_settings['SWIFT_INCLUDE_PATHS'])
      invalid_toolchain_path = '$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)'

      config.build_settings['LIBRARY_SEARCH_PATHS'] = library_search_paths.reject { |path| path == invalid_toolchain_path }
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] = framework_search_paths.reject { |path| path == invalid_toolchain_path }
      config.build_settings['SWIFT_INCLUDE_PATHS'] = swift_include_paths.reject { |path| path == invalid_toolchain_path }
      config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
      config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
      if ['Capacitor', 'CapacitorCordova', 'RevenuecatPurchasesCapacitor'].include?(target.name)
        config.build_settings['DEFINES_MODULE'] = 'YES'
      end
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # Suppress deprecation warnings from third-party pods
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
    end
  end

  installer.aggregate_targets.each do |target|
    target.user_project.native_targets.each do |native_target|
      native_target.build_configurations.each do |config|
        config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
        config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
      end
    end
    target.user_project.save
  end
end
